-- =====================================================================
-- T0(법정필수)·T1(조건부필수) 항목 시딩
--
-- 근거: 'DPP_데이터항목_분류.xlsx' 배터리/철강/섬유패션 시트에서 등급이 T0 또는 T1인
-- 320개 행. 도메인 간 중복(제조일·GTIN 등)과 기존 필드와 같은 뜻인 행을 접어서
-- 실제로는 305행이 된다.
--
-- ■ 기존 필드코드를 유지하는 이유
--   HEAT_NO, STEEL_GRADE, NET_WEIGHT_T, BATTERY_CHEMISTRY 같은 코드 26개는 BE 인제스트
--   서비스 6종과 DocumentSlotService, FE makerVals.js 에 문자열로 박혀 있다. 분류표의
--   Steel_Batch_or_Heat_Number 를 그대로 새 코드로 만들면 제강성적서 업로드가 존재하지
--   않는 field_code 로 INSERT 하면서 FK 위반으로 죽는다. 그래서 분류표 항목을 기존
--   코드에 흡수시키고(아래 '기존 코드 흡수' 주석), 근거·공개범위·출처 메타데이터만 덮어쓴다.
--
-- ■ is_required 를 T0 에만 주는 이유
--   FE 는 필수 필드가 하나라도 비면 DPP 발급 버튼을 막는다(makerVals.js 발급 게이트).
--   T1 까지 전부 필수로 잡으면 305개 중 200개 가까이가 필수가 되어 데모에서 발급이
--   아예 불가능해진다. T1 은 '조건이 충족될 때만 발동'이므로 선택으로 두고, 조건은
--   t1_condition 컬럼에 남겨서 나중에 조건부 검증 규칙으로 승격할 수 있게 했다.
--   추가로 is_mvp=FALSE(분류표 MVP 열이 N - 보유 목데이터로 값이 안 나오는 항목)인
--   T0 도 필수에서 뺐다. 값을 채울 방법이 없는 필드를 필수로 잡으면 완성도가 영원히
--   100%에 못 닿는다.
--
-- ■ sort_order 재배치
--   기존 배치는 섹션당 100칸(IDENTIFIER 101~, OPERATOR 201~ ...)이었는데 섹션이 8개에서
--   21개로 늘고 항목도 80 -> 300+ 이 되면서 100칸으로는 넘친다. 섹션당 1000칸으로 넓히고
--   기존 행도 같은 규칙으로 다시 매긴다(sort_order 는 정렬 외에 아무 데도 안 쓰인다).
--   분류표에서 온 행은 밴드 앞쪽(1~99), 분류표에 없는 기존 행은 뒤쪽(500~599)에 둬서
--   같은 섹션 안에서 번호가 겹치지 않게 한다.
-- =====================================================================

-- ── 기존 코드 흡수 (24건) ──────────────────────────────────────
-- 분류표 항목명 -> 이미 쓰이고 있는 field_code. 철자를 바꾸지 않는다.
--   COMMON   DPP_URI                                  <- Battery_Passport_ID
--   COMMON   GTIN                                     <- GTIN_Code
--   COMMON   UOI_MANUFACTURER                         <- EORI_Number
--   BATTERY  BATTERY_MODEL_NO                         <- Battery_Model_Identifier
--   BATTERY  BATTERY_CATEGORY                         <- Battery_Category (EV, LMT, SLI 등)
--   BATTERY  BATTERY_NET_WEIGHT_KG                    <- Total_Weight_kg
--   COMMON   OPERATOR_MANUFACTURER                    <- Manufacturer_Name
--   BATTERY  BATTERY_PLANT_ID                         <- Manufacturing_Facility_Name
--   COMMON   PRODUCTION_DATE                          <- Date_of_Manufacture (YYYY-MM)
--   BATTERY  BATTERY_CHEMISTRY                        <- Cell_Chemistry_Class
--   COMMON   DISMANTLING_INFO                         <- End_of_Life_Information_URL
--   STEEL    HEAT_NO                                  <- Steel_Batch_or_Heat_Number
--   STEEL    LOT_NO                                   <- Coil_Plate_or_Pipe_ID
--   STEEL    STEEL_GRADE                              <- Steel_Grade_Name (예: S355JR)
--   STEEL    STEEL_STANDARD                           <- Applied_Standard_1 (예: EN 10025)
--   STEEL    PRODUCT_FORM                             <- Product_Form (코일, 후판, 강관 등)
--   STEEL    NET_WEIGHT_T                             <- Product_Net_Weight_kg
--   COMMON   UFI_PLANT                                <- Production_Facility_Name
--   COMMON   PCF_VALUE                                <- Specific_Embedded_Emissions_tCO2e_per_t
--   COMMON   ORIGIN_COUNTRY                           <- Country_of_Origin_Code (ISO 3166-1)
--   TEXTILE  FABRIC_LOT_NO                            <- Batch_or_Lot_Number
--   TEXTILE  FABRIC_TYPE                              <- Product_Category
--   TEXTILE  NET_WEIGHT_KG                            <- Product_Net_Weight_g
--   COMMON   RECYCLABILITY_NOTE                       <- Consumer_Sorting_Instructions

INSERT INTO requirement_field
 (field_code, domain, section, label_ko, label_en, data_type, unit,
  is_required, is_auto, responsible_role, sort_order,
  tier, binding_strength, legal_basis, t1_condition, disclosure_scope,
  data_source, spec_ref, is_mvp, review_note)
VALUES
('DPP_URI', 'COMMON', 'IDENTIFIER', '배터리 여권 ID', 'Battery Passport ID', 'URL', NULL, FALSE, TRUE, NULL, 1001,
 'T0', '구속(여권 2027-02-18)', '배터리규정(EU)2023/1542 Art.77(3) 고유식별자 (여권 데이터포인트 1) / ESPR 등록부 Impl.Reg.(EU)2026/1778', NULL, 'PUBLIC', 'SYSTEM', 'BATTERY#1,STEEL#1,TEXTILE#1', TRUE, '여권은 item(개별 배터리) 단위로 부여'),
('GTIN', 'COMMON', 'IDENTIFIER', 'GS1 상품코드(GTIN)', 'GTIN Code', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 1002,
 'T1', '조건부 구속', 'Annex III(c)/GS1 등 식별자 표준', '데이터캐리어 표준으로 GTIN 채택 시', 'PUBLIC', 'MANUAL', 'BATTERY#2,STEEL#2,TEXTILE#2', TRUE, '배터리규정이 GTIN을 직접 의무화하지는 않음'),
('TARIC_CODE', 'BATTERY', 'IDENTIFIER', 'TARIC 코드', 'TARIC Code', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 1003,
 'T1', '조건부 구속', '통관 신고 데이터요소(Del.Reg.(EU)2015/2446 Annex B)', 'EU 수입 시', 'PUBLIC', 'MANUAL', 'BATTERY#3', FALSE, '여권 항목이 아니라 통관 항목'),
('UOI_MANUFACTURER', 'COMMON', 'IDENTIFIER', 'EORI 번호', 'EORI Number', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 1004,
 'T1', '조건부 구속', 'UCC EORI', 'EU 수입자·수출자 등록 시', 'RESTRICTED', 'MANUAL', 'BATTERY#4,STEEL#222', FALSE, '여권 항목 아님'),
('BATTERY_MODEL_NO', 'BATTERY', 'IDENTIFIER', '배터리 모델 식별자', 'Battery Model Identifier', 'STRING', NULL, TRUE, FALSE, 'MANUFACTURER', 1005,
 'T0', '구속(여권 2027-02-18)', 'Annex VI Part A(2) 모델 식별자 (데이터포인트 7)', NULL, 'PUBLIC', 'MANUAL', 'BATTERY#5', TRUE, NULL),
('BATCH_OR_LOT_NUMBER', 'BATTERY', 'IDENTIFIER', '배치·로트 번호', 'Batch or Lot Number', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 1006,
 'T1', '조건부 구속', 'Annex XIII 4(d) 기록 단위 / 배치 추적', '배치 단위 이력을 남길 때', 'PUBLIC', 'MANUAL', 'BATTERY#6', TRUE, NULL),
('BATTERY_CATEGORY', 'BATTERY', 'IDENTIFIER', '배터리 분류', 'Battery Category', 'CODE', NULL, TRUE, FALSE, 'MANUFACTURER', 1007,
 'T0', '구속(여권 2027-02-18)', 'Annex VI Part A(2) 배터리 카테고리 (데이터포인트 6)', NULL, 'PUBLIC', 'MANUAL', 'BATTERY#7', TRUE, NULL),
('BATTERY_STATUS', 'BATTERY', 'IDENTIFIER', '배터리 상태(신품/재목적)', 'Battery Status', 'CODE', NULL, FALSE, TRUE, NULL, 1008,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 4(c) 배터리 상태 (데이터포인트 67) — 원상태/재목적/재사용/재제조/폐기물', NULL, 'RESTRICTED', 'SYSTEM', 'BATTERY#8', TRUE, NULL),
('BATTERY_NET_WEIGHT_KG', 'BATTERY', 'IDENTIFIER', '총 중량', 'Total Weight kg', 'NUMBER', 'kg', TRUE, FALSE, 'MANUFACTURER', 1009,
 'T0', '구속(여권 2027-02-18)', 'Annex VI Part A(5) 중량 (데이터포인트 10)', NULL, 'PUBLIC', 'PARSER', 'BATTERY#9', TRUE, NULL),
('OPERATOR_MANUFACTURER', 'COMMON', 'IDENTIFIER', '제조사명', 'Manufacturer Name', 'STRING', NULL, TRUE, FALSE, 'MANUFACTURER', 1010,
 'T0', '구속(여권 2027-02-18)', 'Annex VI Part A(1) 제조자 명칭·상표 (데이터포인트 3)', NULL, 'PUBLIC', 'MANUAL', 'BATTERY#10,STEEL#21,TEXTILE#19', TRUE, NULL),
('MANUFACTURER_REGISTERED_ADDRESS', 'BATTERY', 'IDENTIFIER', '제조사 등기 주소', 'Manufacturer Registered Address', 'STRING', NULL, TRUE, FALSE, 'MANUFACTURER', 1011,
 'T0', '구속(여권 2027-02-18)', 'Annex VI Part A(1) 제조자 우편주소 (데이터포인트 4)', NULL, 'PUBLIC', 'MANUAL', 'BATTERY#11', TRUE, NULL),
('MANUFACTURER_EMAIL_CONTACT', 'BATTERY', 'IDENTIFIER', '제조사 연락 이메일', 'Manufacturer Email Contact', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 1012,
 'T1', '조건부 구속', 'Annex VI Part A(1) 웹·이메일 (데이터포인트 5) — ''가용한 경우''', '연락 수단이 있는 경우', 'PUBLIC', 'MANUAL', 'BATTERY#12', TRUE, '집행위 가이던스상 Optional'),
('MANUFACTURER_WEBSITE', 'BATTERY', 'IDENTIFIER', '제조사 웹사이트', 'Manufacturer Website', 'URL', NULL, FALSE, FALSE, 'MANUFACTURER', 1013,
 'T1', '조건부 구속', 'Annex VI Part A(1) (데이터포인트 5) — ''가용한 경우''', '동상', 'PUBLIC', 'MANUAL', 'BATTERY#13', FALSE, NULL),
('BATTERY_PLANT_ID', 'BATTERY', 'IDENTIFIER', '생산시설명', 'Manufacturing Facility Name', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 1014,
 'T1', '조건부 구속', 'Annex VI Part A(3) 제조 장소 (데이터포인트 8)', NULL, 'PUBLIC', 'MANUAL', 'BATTERY#14', TRUE, '규정이 요구하는 것은 ''제조 장소''이며 설비 ''명칭''은 아님'),
('MANUFACTURING_FACILITY_LONGITUDE', 'BATTERY', 'IDENTIFIER', '생산시설 경도', 'Manufacturing Facility Longitude', 'NUMBER', NULL, FALSE, FALSE, 'MANUFACTURER', 1015,
 'T1', '조건부 구속', 'Annex VI Part A(3) 제조 장소의 특정 수단', '좌표로 장소를 특정할 때', 'PUBLIC', 'MANUAL', 'BATTERY#16', TRUE, '⚠원본 ''필수''는 과잉. 규정은 좌표 형식을 지정하지 않음'),
('MANUFACTURING_FACILITY_LATITUDE', 'BATTERY', 'IDENTIFIER', '생산시설 위도', 'Manufacturing Facility Latitude', 'NUMBER', NULL, FALSE, FALSE, 'MANUFACTURER', 1016,
 'T1', '조건부 구속', 'Annex VI Part A(3) 제조 장소의 특정 수단', '좌표로 장소를 특정할 때', 'PUBLIC', 'MANUAL', 'BATTERY#17', TRUE, '⚠원본 ''필수''는 과잉. 규정은 좌표 형식을 지정하지 않음'),
('PRODUCTION_DATE', 'COMMON', 'IDENTIFIER', '제조일', 'Date of Manufacture', 'DATE', NULL, TRUE, FALSE, 'MANUFACTURER', 1017,
 'T0', '구속(여권 2027-02-18)', 'Annex VI Part A(4) 제조일(월/년) (데이터포인트 9)', NULL, 'PUBLIC', 'PARSER', 'BATTERY#18,STEEL#19,TEXTILE#16', TRUE, NULL),
('DATE_OF_PLACING_ON_MARKET', 'BATTERY', 'IDENTIFIER', '시장 출시일', 'Date of Placing on Market', 'DATE', NULL, FALSE, FALSE, 'MANUFACTURER', 1018,
 'T1', '조건부 구속', '시장 출시일 — Annex VII Part B 수명 산정 기산점', '기대수명·SoH 산정에 사용할 때', 'PUBLIC', 'MANUAL', 'BATTERY#19', TRUE, NULL),
('EU_DECLARATION_OF_CONFORMITY_ID', 'BATTERY', 'IDENTIFIER', 'EU 적합성선언서 번호', 'EU Declaration of Conformity ID', 'STRING', NULL, TRUE, FALSE, 'MANUFACTURER', 1019,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 1(r) EU 적합성선언 (데이터포인트 42) / Art.18 + Annex IX', NULL, 'PUBLIC', 'PARSER', 'BATTERY#20', TRUE, NULL),
('DIGITAL_LINK_URI_SYNTAX_STANDARD', 'BATTERY', 'IDENTIFIER', '디지털링크 URI 표준', 'Digital Link URI Syntax Standard', 'STRING', NULL, FALSE, TRUE, NULL, 1020,
 'T1', '조건부 구속', 'Art.77(3) 고유식별자의 표준 준수 / EN 18219·18220', '식별자 구문 표준을 명시할 때', 'PUBLIC', 'SYSTEM', 'BATTERY#214', TRUE, NULL),
('PHYSICAL_QR_CODE_PLACEMENT_LOCATION', 'BATTERY', 'IDENTIFIER', 'QR 코드 부착 위치', 'Physical QR Code Placement Location', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 1021,
 'T1', '조건부 구속', 'Art.13(6) QR 코드 (2027-02-18) + Annex VI Part C', 'QR 부착 위치를 여권에 기재할 때', 'PUBLIC', 'MANUAL', 'BATTERY#226', TRUE, '규정이 요구하는 것은 QR 부착 자체이며 ''위치 문자열 필드''는 아님'),
('DATA_MODEL_SCHEMA_REVISION_NUMBER', 'BATTERY', 'IDENTIFIER', '데이터모델 개정번호', 'Data Model Schema Revision Number', 'STRING', NULL, FALSE, TRUE, NULL, 1022,
 'T1', '조건부 구속', 'Art.77(8) 위임법(여권 기술설계) 대기 / 운영 필요', '스키마 버전 관리를 할 때', 'PUBLIC', 'SYSTEM', 'BATTERY#251', TRUE, 'No.181과 중복'),
('PASSPORT_ISSUANCE_TIMESTAMP', 'BATTERY', 'IDENTIFIER', '여권 발급 시각', 'Passport Issuance Timestamp', 'DATETIME', NULL, FALSE, TRUE, NULL, 1023,
 'T1', '조건부 구속', 'Art.77 여권 생성 시점 기록', '운영상 필요', 'PUBLIC', 'SYSTEM', 'BATTERY#287', TRUE, NULL),
('CN_CODE_8_DIGIT', 'STEEL', 'IDENTIFIER', 'EU 관세코드(CN 8자리)', 'CN Code 8 Digit', 'STRING', NULL, TRUE, FALSE, 'MANUFACTURER', 1024,
 'T0', '구속', 'CBAM(EU)2023/956 Annex I 대상재 판별 / CN 코드 근거 Reg.(EEC)2658/87 + Del.Reg.(EU)2015/2446 Annex B', NULL, 'PUBLIC', 'MANUAL', 'STEEL#4', TRUE, 'ESPR Art.13(1)의 등록부 commodity code는 ''자유유통 반입'' 대상에 한정'),
('HEAT_NO', 'STEEL', 'IDENTIFIER', '용강 배치/히트 번호', 'Steel Batch or Heat Number', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 1025,
 'T1', '위임법 대기', 'ESPR Art.9(2)(d)는 여권 단위(모델/배치/item)만 규정 / EN 10204 3.1은 자발적 표준', '배치 단위 여권으로 설계할 때', 'PUBLIC', 'PARSER', 'STEEL#5', TRUE, '⚠법정 필수 항목이 아님. Art.9(2)(d)는 ''어느 단위로 여권을 만들지''를 위임법이 정하라는 규정일 뿐'),
('LOT_NO', 'STEEL', 'IDENTIFIER', '코일·후판·강관 ID', 'Coil Plate or Pipe ID', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 1026,
 'T1', '위임법 대기', 'ESPR Art.9(2)(d) item 단위 여권', '여권 단위를 item으로 설계할 때', 'PUBLIC', 'PARSER', 'STEEL#6', TRUE, NULL),
('STEEL_GRADE', 'STEEL', 'IDENTIFIER', '강종명', 'Steel Grade Name', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 1027,
 'T1', '조건부 구속', 'CPR(EU)2024/3110 + EN 10025-1 등 하모나이즈드 제품표준 DoP', '건설용 구조용강 등 CPR 적용 제품일 때', 'PUBLIC', 'PARSER', 'STEEL#8', TRUE, '⚠근거 재확인 필요: EN 10025-1의 OJ 인용 상태 확인할 것'),
('STEEL_STANDARD', 'STEEL', 'IDENTIFIER', '적용 표준', 'Applied Standard 1', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 1028,
 'T1', '조건부 구속', 'CPR + 적용 제품표준', '동상', 'PUBLIC', 'PARSER', 'STEEL#9', TRUE, NULL),
('PRODUCT_FORM', 'STEEL', 'IDENTIFIER', '제품 형상', 'Product Form', 'CODE', NULL, FALSE, FALSE, 'MANUFACTURER', 1029,
 'T1', '조건부 구속', 'CBAM Impl.Reg.(EU)2025/2547 Annex I 집합재 카테고리 판별', NULL, 'PUBLIC', 'MANUAL', 'STEEL#11', TRUE, NULL),
('NET_WEIGHT_T', 'STEEL', 'IDENTIFIER', '제품 순중량', 'Product Net Weight kg', 'NUMBER', 't', TRUE, FALSE, 'MANUFACTURER', 1030,
 'T0', '구속', 'CBAM Art.6(2)(a) 연간 총 수량(t) / 면제 임계는 CBAM Art.2a + Annex VII pt.1((EU)2025/2083 신설)', NULL, 'PUBLIC', 'PARSER', 'STEEL#17', TRUE, 'Art.6(2)(a)는 연간 집계 수량이며 개별 제품 중량 필드를 요구하는 것은 아님'),
('FABRIC_LOT_NO', 'TEXTILE', 'IDENTIFIER', '배치·로트 번호', 'Batch or Lot Number', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 1031,
 'T1', '조건부 구속', 'GPSR(EU)2023/988 Art.9(5) — 유형/배치/일련번호 중 택일 가능', '제품 식별자로 배치번호를 채택할 때', 'PUBLIC', 'MANUAL', 'TEXTILE#4', TRUE, 'Art.9(5)는 선택적 열거이므로 ''배치번호'' 자체가 법정 필수인 것은 아님'),
('SERIAL_NUMBER', 'TEXTILE', 'IDENTIFIER', '시리얼 번호', 'Serial Number', 'STRING', NULL, FALSE, TRUE, NULL, 1032,
 'T1', '위임법 대기', 'ESPR Art.9(2)(d) item 단위 여권', '여권 단위를 item으로 설계할 때', 'PUBLIC', 'SYSTEM', 'TEXTILE#5', FALSE, NULL),
('FABRIC_TYPE', 'TEXTILE', 'IDENTIFIER', '제품 카테고리', 'Product Category', 'CODE', NULL, FALSE, FALSE, 'MANUFACTURER', 1033,
 'T1', '조건부 구속', 'REACH SCIP ''Article category''(TARIC/CN 기반) / ESPR Annex III(d) commodity code', 'SCIP 신고 대상일 때', 'PUBLIC', 'MANUAL', 'TEXTILE#6', TRUE, '자유 Enum이 아니라 CN/TARIC 코드로 정규화 권장'),
('PRODUCT_SUB_CATEGORY', 'TEXTILE', 'IDENTIFIER', '제품 세부 카테고리', 'Product Sub Category', 'CODE', NULL, FALSE, FALSE, 'MANUFACTURER', 1034,
 'T1', '조건부 구속', 'REACH SCIP ''Article category''(TARIC/CN 기반) / ESPR Annex III(d) commodity code', 'SCIP 신고 대상일 때', 'PUBLIC', 'MANUAL', 'TEXTILE#7', TRUE, '자유 Enum이 아니라 CN/TARIC 코드로 정규화 권장'),
('NET_WEIGHT_KG', 'TEXTILE', 'IDENTIFIER', '제품 순중량', 'Product Net Weight g', 'NUMBER', 'kg', FALSE, FALSE, 'MANUFACTURER', 1035,
 'T1', '조건부 구속', '1007/2011 Art.9(1) 중량비 산정의 기준값', '섬유 조성 % 검증을 시스템에서 수행할 때', 'PUBLIC', 'MANUAL', 'TEXTILE#14', TRUE, NULL),
('BRAND_CONTACT_EMAIL', 'TEXTILE', 'IDENTIFIER', '브랜드 연락 이메일', 'Brand Contact Email', 'STRING', NULL, TRUE, FALSE, 'MANUFACTURER', 1036,
 'T0', '구속', 'GPSR(EU)2023/988 Art.9(6) 우편 주소 및 전자 주소', NULL, 'PUBLIC', 'MANUAL', 'TEXTILE#20', TRUE, NULL),
('MANUFACTURER_COUNTRY', 'STEEL', 'OPERATOR', '제조사 소재국', 'Manufacturer Country', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 2001,
 'T1', '조건부 구속', 'UCC(EU)952/2013 Art.60 원산지 / CBAM Art.10(2)(b) ''완전한 주소''에 포함', '운영자가 CBAM 설비 등록을 한 경우(Art.10(1)은 ''운영자 요청 시'' 등록)', 'PUBLIC', 'MANUAL', 'STEEL#22', TRUE, '⚠Art.10(2)(a)에는 국가 요소가 없음(인용 수정)'),
('MANUFACTURER_BUSINESS_REG_NUMBER', 'STEEL', 'OPERATOR', '제조사 사업자등록번호', 'Manufacturer Business Reg Number', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 2002,
 'T1', '조건부 구속', 'CBAM Art.10(2)(a) 법인·사업자 등록번호', '운영자가 CBAM 설비 등록을 한 경우(Art.10(1)은 ''운영자 요청 시'' 등록)', 'PUBLIC', 'MANUAL', 'STEEL#23', TRUE, NULL),
('UFI_PLANT', 'COMMON', 'OPERATOR', '생산시설명', 'Production Facility Name', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 2003,
 'T1', '조건부 구속', 'CBAM Art.10(2)(b)', '운영자가 CBAM 설비 등록을 한 경우(Art.10(1)은 ''운영자 요청 시'' 등록)', 'PUBLIC', 'MANUAL', 'STEEL#24', TRUE, '⚠Art.10(2)(b)가 요구하는 것은 소재지·완전한 주소·좌표이며 설비 ''명칭''은 아님'),
('PRODUCTION_FACILITY_COUNTRY', 'STEEL', 'OPERATOR', '생산시설 소재국', 'Production Facility Country', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 2004,
 'T1', '조건부 구속', 'CBAM Art.10(2)(b)', '운영자가 CBAM 설비 등록을 한 경우(Art.10(1)은 ''운영자 요청 시'' 등록)', 'PUBLIC', 'MANUAL', 'STEEL#25', TRUE, NULL),
('PRODUCTION_FACILITY_ADDRESS', 'STEEL', 'OPERATOR', '생산시설 주소', 'Production Facility Address', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 2005,
 'T1', '조건부 구속', 'CBAM Art.10(2)(b) 완전한 주소', '운영자가 CBAM 설비 등록을 한 경우(Art.10(1)은 ''운영자 요청 시'' 등록)', 'PUBLIC', 'MANUAL', 'STEEL#26', TRUE, NULL),
('FACILITY_GPS_LATITUDE', 'STEEL', 'OPERATOR', '시설 GPS 위도', 'Facility GPS Latitude', 'NUMBER', NULL, FALSE, FALSE, 'MANUFACTURER', 2006,
 'T1', '조건부 구속', 'CBAM Art.10(2)(b) 위도·경도 소수점 6자리', '운영자가 CBAM 설비 등록을 한 경우(Art.10(1)은 ''운영자 요청 시'' 등록)', 'PUBLIC', 'MANUAL', 'STEEL#27', TRUE, '⚠원본 ''선택''은 하향 오분류. 등록 설비라면 소수점 6자리 좌표가 법정 요구사항'),
('FACILITY_GPS_LONGITUDE', 'STEEL', 'OPERATOR', '시설 GPS 경도', 'Facility GPS Longitude', 'NUMBER', NULL, FALSE, FALSE, 'MANUFACTURER', 2007,
 'T1', '조건부 구속', 'CBAM Art.10(2)(b) 위도·경도 소수점 6자리', '운영자가 CBAM 설비 등록을 한 경우(Art.10(1)은 ''운영자 요청 시'' 등록)', 'PUBLIC', 'MANUAL', 'STEEL#28', TRUE, '⚠원본 ''선택''은 하향 오분류. 등록 설비라면 소수점 6자리 좌표가 법정 요구사항'),
('CBAM_INSTALLATION_ID', 'STEEL', 'OPERATOR', 'CBAM 설비 등록번호', 'CBAM Installation ID', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 2008,
 'T1', '조건부 구속', 'CBAM Art.10(1)~(3) 설비 등록', '해당 설비가 CBAM 등록을 마친 경우', 'PUBLIC', 'MANUAL', 'STEEL#30', TRUE, NULL),
('CBAM_OPERATOR_NAME', 'STEEL', 'OPERATOR', 'CBAM 운영자명', 'CBAM Operator Name', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 2009,
 'T1', '조건부 구속', 'CBAM Art.10(2)(a) 운영자명', '운영자가 CBAM 설비 등록을 한 경우(Art.10(1)은 ''운영자 요청 시'' 등록)', 'PUBLIC', 'MANUAL', 'STEEL#31', TRUE, 'No.21과 내용 중복. 하나로 통합 권장'),
('BATTERY_CHEMISTRY', 'BATTERY', 'COMPOSITION', '셀 화학 계열', 'Cell Chemistry Class', 'CODE', NULL, TRUE, FALSE, 'MANUFACTURER', 4001,
 'T0', '구속(여권 2027-02-18)', 'Annex VI Part A(7) 화학조성 (데이터포인트 12)', NULL, 'PUBLIC', 'PARSER', 'BATTERY#27', TRUE, NULL),
('NUMBER_OF_CELLS', 'BATTERY', 'COMPOSITION', '셀 수', 'Number of Cells', 'NUMBER', NULL, FALSE, FALSE, 'MANUFACTURER', 4002,
 'T1', '조건부 구속', 'Annex XIII 2(c) 해체 정보(셀 수량·배치)', '해체 정보 제공 대상일 때', 'RESTRICTED', 'PARSER', 'BATTERY#28', TRUE, NULL),
('NUMBER_OF_MODULES', 'BATTERY', 'COMPOSITION', '모듈 수', 'Number of Modules', 'NUMBER', NULL, FALSE, FALSE, 'MANUFACTURER', 4003,
 'T1', '조건부 구속', 'Annex XIII 2(c) 해체 정보(셀 수량·배치)', '해체 정보 제공 대상일 때', 'RESTRICTED', 'PARSER', 'BATTERY#29', TRUE, NULL),
('CATHODE_ACTIVE_MATERIAL_FAMILY', 'BATTERY', 'COMPOSITION', '양극 활물질 계열', 'Cathode Active Material Family', 'STRING', NULL, TRUE, FALSE, 'MANUFACTURER', 4004,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 2(a) 상세 조성 — 양극재 (데이터포인트 45)', NULL, 'RESTRICTED', 'PARSER', 'BATTERY#30', TRUE, '⚠영지식증명 대상이 아님. Annex XIII 2(a)는 ''정당한 이익 보유자와 집행위에게 실제 값을 공개''하라는 의무이므로 값을 숨기는 ZKP로 대체할 수 없다. 접근을 제한하되 값 자체는 보관·제공 가능해야 함'),
('CATHODE_COMPOSITION_DETAILS', 'BATTERY', 'COMPOSITION', '양극 조성 상세', 'Cathode Composition Details', 'STRING', NULL, TRUE, FALSE, 'MANUFACTURER', 4005,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 2(a) 상세 조성 — 양극재 (데이터포인트 45)', NULL, 'RESTRICTED', 'PARSER', 'BATTERY#31', TRUE, '⚠영지식증명 대상이 아님. Annex XIII 2(a)는 ''정당한 이익 보유자와 집행위에게 실제 값을 공개''하라는 의무이므로 값을 숨기는 ZKP로 대체할 수 없다. 접근을 제한하되 값 자체는 보관·제공 가능해야 함'),
('CATHODE_BINDER_MATERIAL', 'BATTERY', 'COMPOSITION', '양극 바인더', 'Cathode Binder Material', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 4006,
 'T1', '조건부 구속', 'Annex XIII 2(a) 상세 조성의 하위 구성', '바인더·도전재까지 기재할 때', 'RESTRICTED', 'PARSER', 'BATTERY#32', FALSE, '⚠영지식증명 대상이 아님. Annex XIII 2(a)는 ''정당한 이익 보유자와 집행위에게 실제 값을 공개''하라는 의무이므로 값을 숨기는 ZKP로 대체할 수 없다. 접근을 제한하되 값 자체는 보관·제공 가능해야 함'),
('CATHODE_CONDUCTIVE_ADDITIVE', 'BATTERY', 'COMPOSITION', '양극 도전재', 'Cathode Conductive Additive', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 4007,
 'T1', '조건부 구속', 'Annex XIII 2(a) 상세 조성의 하위 구성', '바인더·도전재까지 기재할 때', 'RESTRICTED', 'PARSER', 'BATTERY#33', FALSE, '⚠영지식증명 대상이 아님. Annex XIII 2(a)는 ''정당한 이익 보유자와 집행위에게 실제 값을 공개''하라는 의무이므로 값을 숨기는 ZKP로 대체할 수 없다. 접근을 제한하되 값 자체는 보관·제공 가능해야 함'),
('ANODE_ACTIVE_MATERIAL_FAMILY', 'BATTERY', 'COMPOSITION', '음극 활물질 계열', 'Anode Active Material Family', 'STRING', NULL, TRUE, FALSE, 'MANUFACTURER', 4008,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 2(a) 상세 조성 — 음극재 (데이터포인트 45)', NULL, 'RESTRICTED', 'PARSER', 'BATTERY#34', TRUE, '⚠영지식증명 대상이 아님. Annex XIII 2(a)는 ''정당한 이익 보유자와 집행위에게 실제 값을 공개''하라는 의무이므로 값을 숨기는 ZKP로 대체할 수 없다. 접근을 제한하되 값 자체는 보관·제공 가능해야 함'),
('ANODE_COMPOSITION_DETAILS', 'BATTERY', 'COMPOSITION', '음극 조성 상세', 'Anode Composition Details', 'STRING', NULL, TRUE, FALSE, 'MANUFACTURER', 4009,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 2(a) 상세 조성 — 음극재 (데이터포인트 45)', NULL, 'RESTRICTED', 'PARSER', 'BATTERY#35', TRUE, '⚠영지식증명 대상이 아님. Annex XIII 2(a)는 ''정당한 이익 보유자와 집행위에게 실제 값을 공개''하라는 의무이므로 값을 숨기는 ZKP로 대체할 수 없다. 접근을 제한하되 값 자체는 보관·제공 가능해야 함'),
('ANODE_BINDER_MATERIAL', 'BATTERY', 'COMPOSITION', '음극 바인더', 'Anode Binder Material', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 4010,
 'T1', '조건부 구속', 'Annex XIII 2(a) 상세 조성의 하위 구성', '바인더·도전재까지 기재할 때', 'RESTRICTED', 'PARSER', 'BATTERY#36', FALSE, '⚠영지식증명 대상이 아님. Annex XIII 2(a)는 ''정당한 이익 보유자와 집행위에게 실제 값을 공개''하라는 의무이므로 값을 숨기는 ZKP로 대체할 수 없다. 접근을 제한하되 값 자체는 보관·제공 가능해야 함'),
('ANODE_CONDUCTIVE_ADDITIVE', 'BATTERY', 'COMPOSITION', '음극 도전재', 'Anode Conductive Additive', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 4011,
 'T1', '조건부 구속', 'Annex XIII 2(a) 상세 조성의 하위 구성', '바인더·도전재까지 기재할 때', 'RESTRICTED', 'PARSER', 'BATTERY#37', FALSE, '⚠영지식증명 대상이 아님. Annex XIII 2(a)는 ''정당한 이익 보유자와 집행위에게 실제 값을 공개''하라는 의무이므로 값을 숨기는 ZKP로 대체할 수 없다. 접근을 제한하되 값 자체는 보관·제공 가능해야 함'),
('ELECTROLYTE_TYPE', 'BATTERY', 'COMPOSITION', '전해질 유형', 'Electrolyte Type', 'CODE', NULL, TRUE, FALSE, 'MANUFACTURER', 4012,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 2(a) 상세 조성 — 전해질 (데이터포인트 45)', NULL, 'RESTRICTED', 'PARSER', 'BATTERY#38', TRUE, '⚠영지식증명 대상이 아님. Annex XIII 2(a)는 ''정당한 이익 보유자와 집행위에게 실제 값을 공개''하라는 의무이므로 값을 숨기는 ZKP로 대체할 수 없다. 접근을 제한하되 값 자체는 보관·제공 가능해야 함'),
('ELECTROLYTE_SOLVENT', 'BATTERY', 'COMPOSITION', '전해질 용매', 'Electrolyte Solvent', 'STRING', NULL, TRUE, FALSE, 'MANUFACTURER', 4013,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 2(a) 상세 조성 — 전해질 (데이터포인트 45)', NULL, 'RESTRICTED', 'PARSER', 'BATTERY#39', TRUE, '⚠영지식증명 대상이 아님. Annex XIII 2(a)는 ''정당한 이익 보유자와 집행위에게 실제 값을 공개''하라는 의무이므로 값을 숨기는 ZKP로 대체할 수 없다. 접근을 제한하되 값 자체는 보관·제공 가능해야 함'),
('ELECTROLYTE_SALT', 'BATTERY', 'COMPOSITION', '전해질 염', 'Electrolyte Salt', 'STRING', NULL, TRUE, FALSE, 'MANUFACTURER', 4014,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 2(a) 상세 조성 — 전해질 (데이터포인트 45)', NULL, 'RESTRICTED', 'PARSER', 'BATTERY#40', TRUE, '⚠영지식증명 대상이 아님. Annex XIII 2(a)는 ''정당한 이익 보유자와 집행위에게 실제 값을 공개''하라는 의무이므로 값을 숨기는 ZKP로 대체할 수 없다. 접근을 제한하되 값 자체는 보관·제공 가능해야 함'),
('SEPARATOR_MATERIAL', 'BATTERY', 'COMPOSITION', '분리막 재질', 'Separator Material', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 4015,
 'T1', '조건부 구속', 'Annex XIII 2(a) 상세 조성에 포함될 수 있음', '분리막을 조성 항목으로 기재할 때', 'RESTRICTED', 'PARSER', 'BATTERY#41', FALSE, '⚠영지식증명 대상이 아님. Annex XIII 2(a)는 ''정당한 이익 보유자와 집행위에게 실제 값을 공개''하라는 의무이므로 값을 숨기는 ZKP로 대체할 수 없다. 접근을 제한하되 값 자체는 보관·제공 가능해야 함'),
('BATTERY_CASING_MATERIAL_TYPE', 'BATTERY', 'COMPOSITION', '배터리 케이싱 재질', 'Battery Casing Material Type', 'CODE', NULL, FALSE, FALSE, 'MANUFACTURER', 4016,
 'T1', '조건부 구속', 'Annex XIII 2(c) 해체 정보 / Annex XIII 1(s) 폐기물 관리 정보', '해체·재활용 정보 제공 시', 'RESTRICTED', 'MANUAL', 'BATTERY#140', FALSE, '⚠원본 ''필수''이나 케이스 재질 단독 항목의 규정 근거는 약함'),
('PACK_ENCLOSURE_PROTECTION_RATING', 'BATTERY', 'COMPOSITION', '팩 외함 보호등급(IP)', 'Pack Enclosure Protection Rating', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 4017,
 'T1', '조건부 구속', 'Art.12 + Annex V 정치형 ESS 안전 요건', '정치형 배터리 에너지저장시스템일 때', 'PUBLIC', 'PARSER', 'BATTERY#189', FALSE, NULL),
('SHELL_COMPONENT_NAME', 'TEXTILE', 'MATERIAL', '겉감 부품명', 'Shell Component Name', 'STRING', NULL, TRUE, FALSE, 'MANUFACTURER', 5001,
 'T0', '구속', '1007/2011 Art.11(1) 다중구성품 제품의 구성품별 표시', NULL, 'PUBLIC', 'PARSER', 'TEXTILE#21', TRUE, 'Art.11(1)이 요구하는 것은 구성품별 ''섬유 조성''이며 구성품 ''명칭'' 자체는 아님'),
('SHELL_MATERIAL_1_TYPE', 'TEXTILE', 'MATERIAL', '겉감 소재 1 종류', 'Shell Material 1 Type', 'CODE', NULL, TRUE, FALSE, 'MANUFACTURER', 5002,
 'T0', '구속', '1007/2011 Art.5(1)+Art.9(1) Annex I 섬유명 + 중량비(내림차순)', NULL, 'PUBLIC', 'PARSER', 'TEXTILE#22', TRUE, 'Art.9(2)의 ''기타 섬유''(개별 5% 이하 또는 합계 15% 이하) 완화 규정 확인 필요'),
('SHELL_MATERIAL_1_PERCENTAGE_PCT', 'TEXTILE', 'MATERIAL', '겉감 소재 1 혼용률', 'Shell Material 1 Percentage %', 'NUMBER', '%', TRUE, FALSE, 'MANUFACTURER', 5003,
 'T0', '구속', '1007/2011 Art.5(1)+Art.9(1) Annex I 섬유명 + 중량비(내림차순)', NULL, 'PUBLIC', 'PARSER', 'TEXTILE#23', TRUE, 'Art.7(2) 2%(소면 5%)·Art.20 제조공차 3%·Art.10 장식섬유 7% 등 공차 규칙을 판정 로직에 반영할 것'),
('SHELL_MATERIAL_2_TYPE', 'TEXTILE', 'MATERIAL', '겉감 소재 2 종류', 'Shell Material 2 Type', 'CODE', NULL, FALSE, FALSE, 'MANUFACTURER', 5004,
 'T1', '조건부 구속', '1007/2011 Art.9(1)', '혼방 구성 섬유가 2종 이상일 때', 'PUBLIC', 'PARSER', 'TEXTILE#24', TRUE, NULL),
('SHELL_MATERIAL_2_PERCENTAGE_PCT', 'TEXTILE', 'MATERIAL', '겉감 소재 2 혼용률', 'Shell Material 2 Percentage %', 'NUMBER', '%', FALSE, FALSE, 'MANUFACTURER', 5005,
 'T1', '조건부 구속', '1007/2011 Art.9(1)', '혼방 구성 섬유가 2종 이상일 때', 'PUBLIC', 'PARSER', 'TEXTILE#25', TRUE, NULL),
('SHELL_MATERIAL_3_TYPE', 'TEXTILE', 'MATERIAL', '겉감 소재 3 종류', 'Shell Material 3 Type', 'CODE', NULL, FALSE, FALSE, 'MANUFACTURER', 5006,
 'T1', '조건부 구속', '1007/2011 Art.9(1)', '혼방 구성 섬유가 2종 이상일 때', 'PUBLIC', 'PARSER', 'TEXTILE#26', TRUE, NULL),
('SHELL_MATERIAL_3_PERCENTAGE_PCT', 'TEXTILE', 'MATERIAL', '겉감 소재 3 혼용률', 'Shell Material 3 Percentage %', 'NUMBER', '%', FALSE, FALSE, 'MANUFACTURER', 5007,
 'T1', '조건부 구속', '1007/2011 Art.9(1)', '혼방 구성 섬유가 2종 이상일 때', 'PUBLIC', 'PARSER', 'TEXTILE#27', TRUE, NULL),
('LINING_COMPONENT_NAME', 'TEXTILE', 'MATERIAL', '안감 부품명', 'Lining Component Name', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 5008,
 'T1', '조건부 구속', '1007/2011 Art.11(2) 주 안감은 중량 무관 별도 표시', '안감이 있는 제품', 'PUBLIC', 'PARSER', 'TEXTILE#34', TRUE, NULL),
('LINING_MATERIAL_1_TYPE', 'TEXTILE', 'MATERIAL', '안감 소재 1 종류', 'Lining Material 1 Type', 'CODE', NULL, FALSE, FALSE, 'MANUFACTURER', 5009,
 'T1', '조건부 구속', '1007/2011 Art.11(1)~(2) 주 안감 조성', '안감이 주 안감일 때', 'PUBLIC', 'PARSER', 'TEXTILE#35', TRUE, NULL),
('LINING_MATERIAL_1_PERCENTAGE_PCT', 'TEXTILE', 'MATERIAL', '안감 소재 1 혼용률', 'Lining Material 1 Percentage %', 'NUMBER', '%', FALSE, FALSE, 'MANUFACTURER', 5010,
 'T1', '조건부 구속', '1007/2011 Art.11(1)~(2) 주 안감 조성', '안감이 주 안감일 때', 'PUBLIC', 'PARSER', 'TEXTILE#36', TRUE, NULL),
('LINING_MATERIAL_2_TYPE', 'TEXTILE', 'MATERIAL', '안감 소재 2 종류', 'Lining Material 2 Type', 'CODE', NULL, FALSE, FALSE, 'MANUFACTURER', 5011,
 'T1', '조건부 구속', '1007/2011 Art.9(1)', '안감이 혼방일 때', 'PUBLIC', 'PARSER', 'TEXTILE#37', FALSE, NULL),
('LINING_MATERIAL_2_PERCENTAGE_PCT', 'TEXTILE', 'MATERIAL', '안감 소재 2 혼용률', 'Lining Material 2 Percentage %', 'NUMBER', '%', FALSE, FALSE, 'MANUFACTURER', 5012,
 'T1', '조건부 구속', '1007/2011 Art.9(1)', '안감이 혼방일 때', 'PUBLIC', 'PARSER', 'TEXTILE#38', FALSE, NULL),
('PADDING_COMPONENT_NAME', 'TEXTILE', 'MATERIAL', '충전재 부품명', 'Padding Component Name', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 5013,
 'T1', '조건부 구속', '1007/2011 Art.11(1) 30% 이상 구성품', '충전재가 총중량 30% 이상일 때', 'PUBLIC', 'PARSER', 'TEXTILE#42', TRUE, NULL),
('PADDING_MATERIAL_TYPE', 'TEXTILE', 'MATERIAL', '충전재 종류', 'Padding Material Type', 'CODE', NULL, FALSE, FALSE, 'MANUFACTURER', 5014,
 'T1', '조건부 구속', '1007/2011 Art.11(1) 30% 이상 구성품', '충전재가 총중량 30% 이상일 때', 'PUBLIC', 'PARSER', 'TEXTILE#43', TRUE, NULL),
('PADDING_PERCENTAGE_PCT', 'TEXTILE', 'MATERIAL', '충전재 혼용률', 'Padding Percentage %', 'NUMBER', '%', FALSE, FALSE, 'MANUFACTURER', 5015,
 'T1', '조건부 구속', '1007/2011 Art.11(1) 30% 이상 구성품', '충전재가 총중량 30% 이상일 때', 'PUBLIC', 'PARSER', 'TEXTILE#44', TRUE, NULL),
('PADDING_ANIMAL_WELFARE_CERT', 'TEXTILE', 'MATERIAL', '충전재 동물복지 인증', 'Padding Animal Welfare Cert', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 5016,
 'T1', '조건부 구속', '1007/2011 Art.12(1) ''비섬유성 동물유래 부분 함유'' 표기', '다운·깃털 등 동물유래 소재일 때', 'PUBLIC', 'PARSER', 'TEXTILE#46', TRUE, '법정 요구는 인증ID가 아니라 Art.12(1)의 고정 문구. 별도 boolean 필드 신설 권장'),
('CHEMICAL_ANALYSIS_TYPE', 'STEEL', 'CHEMISTRY', '화학분석 구분(레이들/제품)', 'Chemical Analysis Type', 'CODE', NULL, FALSE, FALSE, 'MANUFACTURER', 6001,
 'T1', '계약·표준', 'EN 10204 3.1 / 적용 시험표준', '성적서 파싱 대상일 때', 'PUBLIC', 'PARSER', 'STEEL#32', TRUE, NULL),
('CHEMICAL_TEST_STANDARD', 'STEEL', 'CHEMISTRY', '화학시험 표준', 'Chemical Test Standard', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 6002,
 'T1', '계약·표준', 'EN 10204 3.1 / 적용 시험표준', '성적서 파싱 대상일 때', 'PUBLIC', 'PARSER', 'STEEL#33', TRUE, NULL),
('CHEM_MN_ACTUAL_PCT', 'STEEL', 'CHEMISTRY', '화학성분 Mn 실측', 'Chem Mn Actual %', 'NUMBER', '%', TRUE, FALSE, 'MANUFACTURER', 6003,
 'T0', '구속', 'CBAM Impl.Reg.(EU)2025/2547 Annex IV pt.2 운영자 배출보고서 추가 파라미터(Mn 질량%)', NULL, 'TRADE_SECRET', 'PARSER', 'STEEL#37', TRUE, NULL),
('CHEM_CR_ACTUAL_PCT', 'STEEL', 'CHEMISTRY', '화학성분 Cr 실측', 'Chem Cr Actual %', 'NUMBER', '%', TRUE, FALSE, 'MANUFACTURER', 6004,
 'T0', '구속', 'CBAM Impl.Reg.(EU)2025/2547 Annex IV pt.2 추가 파라미터(Cr 질량%)', NULL, 'TRADE_SECRET', 'PARSER', 'STEEL#47', TRUE, NULL),
('CHEM_NI_ACTUAL_PCT', 'STEEL', 'CHEMISTRY', '화학성분 Ni 실측', 'Chem Ni Actual %', 'NUMBER', '%', TRUE, FALSE, 'MANUFACTURER', 6005,
 'T0', '구속', 'CBAM Impl.Reg.(EU)2025/2547 Annex IV pt.2 추가 파라미터(Ni 질량%)', NULL, 'TRADE_SECRET', 'PARSER', 'STEEL#50', TRUE, NULL),
('CHEM_MO_ACTUAL_PCT', 'STEEL', 'CHEMISTRY', '화학성분 Mo 실측', 'Chem Mo Actual %', 'NUMBER', '%', FALSE, FALSE, 'MANUFACTURER', 6006,
 'T1', '조건부 구속', 'CBAM Impl.Reg.(EU)2025/2547 Annex IV pt.2 ''기타 합금원소'' 질량%', '합금강일 때', 'TRADE_SECRET', 'PARSER', 'STEEL#53', TRUE, NULL),
('CHEM_ZR_ACTUAL_PCT', 'STEEL', 'CHEMISTRY', '화학성분 Zr 실측', 'Chem Zr Actual %', 'NUMBER', '%', FALSE, FALSE, 'MANUFACTURER', 6007,
 'T1', '조건부 구속', 'CBAM Impl.Reg.(EU)2025/2547 Annex IV pt.2 ''기타 합금원소'' 질량%', '특수강·합금강일 때', 'TRADE_SECRET', 'PARSER', 'STEEL#228', FALSE, NULL),
('CHEM_CE_ACTUAL_PCT', 'STEEL', 'CHEMISTRY', '화학성분 Ce 실측', 'Chem Ce Actual %', 'NUMBER', '%', FALSE, FALSE, 'MANUFACTURER', 6008,
 'T1', '조건부 구속', 'CBAM Impl.Reg.(EU)2025/2547 Annex IV pt.2 ''기타 합금원소'' 질량%', '특수강·합금강일 때', 'TRADE_SECRET', 'PARSER', 'STEEL#229', FALSE, NULL),
('CHEM_W_ACTUAL_PCT', 'STEEL', 'CHEMISTRY', '화학성분 W 실측', 'Chem W Actual %', 'NUMBER', '%', FALSE, FALSE, 'MANUFACTURER', 6009,
 'T1', '조건부 구속', 'CBAM Impl.Reg.(EU)2025/2547 Annex IV pt.2 ''기타 합금원소'' 질량%', '특수강·합금강일 때', 'TRADE_SECRET', 'PARSER', 'STEEL#230', FALSE, NULL),
('CHEM_CO_ACTUAL_PCT', 'STEEL', 'CHEMISTRY', '화학성분 Co 실측', 'Chem Co Actual %', 'NUMBER', '%', FALSE, FALSE, 'MANUFACTURER', 6010,
 'T1', '조건부 구속', 'CBAM Impl.Reg.(EU)2025/2547 Annex IV pt.2 ''기타 합금원소'' 질량%', '특수강·합금강일 때', 'TRADE_SECRET', 'PARSER', 'STEEL#231', FALSE, NULL),
('CHEM_SB_ACTUAL_PCT', 'STEEL', 'CHEMISTRY', '화학성분 Sb 실측', 'Chem Sb Actual %', 'NUMBER', '%', FALSE, FALSE, 'MANUFACTURER', 6011,
 'T1', '조건부 구속', 'CBAM Impl.Reg.(EU)2025/2547 Annex IV pt.2 ''기타 합금원소'' 질량%', '특수강·합금강일 때', 'TRADE_SECRET', 'PARSER', 'STEEL#232', FALSE, NULL),
('CHEM_ZN_ACTUAL_PCT', 'STEEL', 'CHEMISTRY', '화학성분 Zn 실측', 'Chem Zn Actual %', 'NUMBER', '%', FALSE, FALSE, 'MANUFACTURER', 6012,
 'T1', '조건부 구속', 'CBAM Impl.Reg.(EU)2025/2547 Annex IV pt.2 ''기타 합금원소'' 질량%', '특수강·합금강일 때', 'TRADE_SECRET', 'PARSER', 'STEEL#233', FALSE, NULL),
('TENSILE_TEST_STANDARD', 'STEEL', 'MECHANICAL', '인장시험 표준', 'Tensile Test Standard', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 7001,
 'T1', '조건부 구속', 'CPR(EU)2024/3110 + EN 10025-1 DoP 선언 성능', 'CPR 적용 구조용강일 때', 'PUBLIC', 'PARSER', 'STEEL#77', TRUE, '⚠CPR 적용 여부·하모나이즈드 표준 인용 상태 재확인 필요'),
('TEST_DIRECTION', 'STEEL', 'MECHANICAL', '시편 채취 방향', 'Test Direction', 'CODE', NULL, FALSE, FALSE, 'MANUFACTURER', 7002,
 'T1', '조건부 구속', 'CPR(EU)2024/3110 + EN 10025-1 DoP 선언 성능', 'CPR 적용 구조용강일 때', 'PUBLIC', 'PARSER', 'STEEL#78', TRUE, '⚠CPR 적용 여부·하모나이즈드 표준 인용 상태 재확인 필요'),
('YIELD_STRENGTH_ACTUAL_MPA', 'STEEL', 'MECHANICAL', '항복강도 실측', 'Yield Strength Actual MPa', 'NUMBER', 'MPa', FALSE, FALSE, 'MANUFACTURER', 7003,
 'T1', '조건부 구속', 'CPR(EU)2024/3110 + EN 10025-1 DoP 선언 성능', 'CPR 적용 구조용강일 때', 'PUBLIC', 'PARSER', 'STEEL#79', TRUE, '⚠CPR 적용 여부·하모나이즈드 표준 인용 상태 재확인 필요'),
('YIELD_STRENGTH_MIN_MPA', 'STEEL', 'MECHANICAL', '항복강도 규격 하한', 'Yield Strength Min MPa', 'NUMBER', 'MPa', FALSE, FALSE, 'MANUFACTURER', 7004,
 'T1', '조건부 구속', 'CPR(EU)2024/3110 + EN 10025-1 DoP 선언 성능', 'CPR 적용 구조용강일 때', 'PUBLIC', 'PARSER', 'STEEL#80', TRUE, '⚠CPR 적용 여부·하모나이즈드 표준 인용 상태 재확인 필요'),
('TENSILE_STRENGTH_ACTUAL_MPA', 'STEEL', 'MECHANICAL', '인장강도 실측', 'Tensile Strength Actual MPa', 'NUMBER', 'MPa', FALSE, FALSE, 'MANUFACTURER', 7005,
 'T1', '조건부 구속', 'CPR(EU)2024/3110 + EN 10025-1 DoP 선언 성능', 'CPR 적용 구조용강일 때', 'PUBLIC', 'PARSER', 'STEEL#82', TRUE, '⚠CPR 적용 여부·하모나이즈드 표준 인용 상태 재확인 필요'),
('TENSILE_STRENGTH_MIN_MPA', 'STEEL', 'MECHANICAL', '인장강도 규격 하한', 'Tensile Strength Min MPa', 'NUMBER', 'MPa', FALSE, FALSE, 'MANUFACTURER', 7006,
 'T1', '조건부 구속', 'CPR(EU)2024/3110 + EN 10025-1 DoP 선언 성능', 'CPR 적용 구조용강일 때', 'PUBLIC', 'PARSER', 'STEEL#83', TRUE, '⚠CPR 적용 여부·하모나이즈드 표준 인용 상태 재확인 필요'),
('TENSILE_STRENGTH_MAX_MPA', 'STEEL', 'MECHANICAL', '인장강도 규격 상한', 'Tensile Strength Max MPa', 'NUMBER', 'MPa', FALSE, FALSE, 'MANUFACTURER', 7007,
 'T1', '조건부 구속', 'CPR(EU)2024/3110 + EN 10025-1 DoP 선언 성능', 'CPR 적용 구조용강일 때', 'PUBLIC', 'PARSER', 'STEEL#84', TRUE, '⚠CPR 적용 여부·하모나이즈드 표준 인용 상태 재확인 필요'),
('ELONGATION_ACTUAL_PCT', 'STEEL', 'MECHANICAL', '연신율 실측', 'Elongation Actual %', 'NUMBER', '%', FALSE, FALSE, 'MANUFACTURER', 7008,
 'T1', '조건부 구속', 'CPR(EU)2024/3110 + EN 10025-1 DoP 선언 성능', 'CPR 적용 구조용강일 때', 'PUBLIC', 'PARSER', 'STEEL#85', TRUE, '⚠CPR 적용 여부·하모나이즈드 표준 인용 상태 재확인 필요'),
('ELONGATION_MIN_PCT', 'STEEL', 'MECHANICAL', '연신율 규격 하한', 'Elongation Min %', 'NUMBER', '%', FALSE, FALSE, 'MANUFACTURER', 7009,
 'T1', '조건부 구속', 'CPR(EU)2024/3110 + EN 10025-1 DoP 선언 성능', 'CPR 적용 구조용강일 때', 'PUBLIC', 'PARSER', 'STEEL#86', TRUE, '⚠CPR 적용 여부·하모나이즈드 표준 인용 상태 재확인 필요'),
('GAUGE_LENGTH_MM', 'STEEL', 'MECHANICAL', '연신율 측정 표점거리', 'Gauge Length mm', 'NUMBER', 'mm', FALSE, FALSE, 'MANUFACTURER', 7010,
 'T1', '조건부 구속', 'CPR(EU)2024/3110 + EN 10025-1 DoP 선언 성능', 'CPR 적용 구조용강일 때', 'PUBLIC', 'PARSER', 'STEEL#87', TRUE, '⚠CPR 적용 여부·하모나이즈드 표준 인용 상태 재확인 필요'),
('RATED_CAPACITY_AH', 'BATTERY', 'PERFORMANCE', '정격 용량', 'Rated Capacity Ah', 'NUMBER', 'Ah', TRUE, FALSE, 'MANUFACTURER', 8001,
 'T0', '구속(여권 2027-02-18)', 'Annex VI Part A(6) 용량 (데이터포인트 11)', NULL, 'PUBLIC', 'PARSER', 'BATTERY#72', TRUE, NULL),
('RATED_CAPACITY_MEASUREMENT_METHOD', 'BATTERY', 'PERFORMANCE', '정격 용량 측정방법', 'Rated Capacity Measurement Method', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 8002,
 'T1', '조건부 구속', 'Annex IV Part B 측정 요소 — 시험조건', '실측값을 여권에 넣을 때', 'PUBLIC', 'PARSER', 'BATTERY#73', TRUE, NULL),
('NOMINAL_ENERGY_WH', 'BATTERY', 'PERFORMANCE', '공칭 에너지', 'Nominal Energy Wh', 'NUMBER', 'Wh', FALSE, FALSE, 'MANUFACTURER', 8003,
 'T1', '조건부 구속', 'Annex IV Part A 정격 에너지', NULL, 'PUBLIC', 'PARSER', 'BATTERY#74', TRUE, NULL),
('NOMINAL_VOLTAGE_V', 'BATTERY', 'PERFORMANCE', '공칭 전압', 'Nominal Voltage V', 'NUMBER', 'V', TRUE, FALSE, 'MANUFACTURER', 8004,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 1(h) 공칭 전압 (데이터포인트 27)', NULL, 'PUBLIC', 'PARSER', 'BATTERY#77', TRUE, '1(h)는 전압을 ''해당 시 온도 범위와 함께'' 요구한다. 온도 범위 연계 필드 필요'),
('MAXIMUM_VOLTAGE_V', 'BATTERY', 'PERFORMANCE', '최대 전압', 'Maximum Voltage V', 'NUMBER', 'V', TRUE, FALSE, 'MANUFACTURER', 8005,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 1(h) 최대 전압 (데이터포인트 28)', NULL, 'PUBLIC', 'PARSER', 'BATTERY#78', TRUE, NULL),
('MINIMUM_VOLTAGE_V', 'BATTERY', 'PERFORMANCE', '최소 전압', 'Minimum Voltage V', 'NUMBER', 'V', TRUE, FALSE, 'MANUFACTURER', 8006,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 1(h) 최소 전압 (데이터포인트 26)', NULL, 'PUBLIC', 'PARSER', 'BATTERY#79', TRUE, NULL),
('MAXIMUM_ALLOWED_DISCHARGE_POWER_W', 'BATTERY', 'PERFORMANCE', '허용 최대 방전출력', 'Maximum Allowed Discharge Power W', 'NUMBER', 'W', TRUE, FALSE, 'MANUFACTURER', 8007,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 1(i) 최초 출력 능력·출력 한계 (데이터포인트 29·30)', NULL, 'PUBLIC', 'PARSER', 'BATTERY#80', TRUE, 'Annex XIII 1(i)는 ''최초 출력 능력(W)''(데이터포인트 29)과 ''출력 한계''(데이터포인트 30)를 별도로 요구한다. 현재 항목은 30만 충족하며 29가 누락됨'),
('MAXIMUM_ALLOWED_CHARGE_POWER_W', 'BATTERY', 'PERFORMANCE', '허용 최대 충전출력', 'Maximum Allowed Charge Power W', 'NUMBER', 'W', TRUE, FALSE, 'MANUFACTURER', 8008,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 1(i) 최초 출력 능력·출력 한계 (데이터포인트 29·30)', NULL, 'PUBLIC', 'PARSER', 'BATTERY#81', TRUE, NULL),
('OPERATING_TEMPERATURE_MAX_C', 'BATTERY', 'PERFORMANCE', '사용 온도 상한', 'Operating Temperature Max C', 'NUMBER', '℃', FALSE, FALSE, 'MANUFACTURER', 8009,
 'T1', '조건부 구속', 'Annex XIII 1(h)·1(i) 전압·출력에 부기되는 온도 범위 (데이터포인트 26~28·30)', '정격 사양으로 기재할 때', 'PUBLIC', 'PARSER', 'BATTERY#84', TRUE, '⚠1(l) 인용은 오류. 1(l)은 ''미사용 시(not in use)'' 온도이며 No.87·88이 여기에 해당. 실사용 중 측정치라면 Annex XIII 4(d) 데이터포인트 70(제한 계층)으로 가야 함'),
('OPERATING_TEMPERATURE_MIN_C', 'BATTERY', 'PERFORMANCE', '사용 온도 하한', 'Operating Temperature Min C', 'NUMBER', '℃', FALSE, FALSE, 'MANUFACTURER', 8010,
 'T1', '조건부 구속', 'Annex XIII 1(h)·1(i) 전압·출력에 부기되는 온도 범위 (데이터포인트 26~28·30)', '정격 사양으로 기재할 때', 'PUBLIC', 'PARSER', 'BATTERY#85', TRUE, '⚠1(l) 인용은 오류. No.84 참조'),
('STORAGE_TEMPERATURE_MAX_C', 'BATTERY', 'PERFORMANCE', '보관 온도 상한', 'Storage Temperature Max C', 'NUMBER', '℃', TRUE, FALSE, 'MANUFACTURER', 8011,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 1(l) 미사용 시 견딜 수 있는 온도 범위 (데이터포인트 34)', NULL, 'PUBLIC', 'PARSER', 'BATTERY#87', TRUE, '⚠원본 ''선택''은 하향 오분류. 1(l)에 정확히 대응하는 항목은 작동 온도가 아니라 보관 온도다'),
('STORAGE_TEMPERATURE_MIN_C', 'BATTERY', 'PERFORMANCE', '보관 온도 하한', 'Storage Temperature Min C', 'NUMBER', '℃', TRUE, FALSE, 'MANUFACTURER', 8012,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 1(l) 미사용 시 견딜 수 있는 온도 범위 (데이터포인트 34)', NULL, 'PUBLIC', 'PARSER', 'BATTERY#88', TRUE, '⚠원본 ''선택''은 하향 오분류. No.87 참조'),
('INITIAL_INTERNAL_RESISTANCE_MOHM', 'BATTERY', 'PERFORMANCE', '초기 내부저항', 'Initial Internal Resistance mOhm', 'NUMBER', 'mΩ', TRUE, FALSE, 'MANUFACTURER', 8013,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 1(o) 셀·팩 저항 (데이터포인트 38)', NULL, 'PUBLIC', 'PARSER', 'BATTERY#89', TRUE, NULL),
('INTERNAL_RESISTANCE_MEASUREMENT_METHOD', 'BATTERY', 'PERFORMANCE', '내부저항 측정방법', 'Internal Resistance Measurement Method', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 8014,
 'T1', '조건부 구속', 'Annex IV Part B 측정 요소', '측정 방법을 명시할 때', 'PUBLIC', 'PARSER', 'BATTERY#90', TRUE, NULL),
('EXPECTED_CYCLE_LIFE_COUNT', 'BATTERY', 'PERFORMANCE', '기대 사이클 수명', 'Expected Cycle Life Count', 'NUMBER', '회', TRUE, FALSE, 'MANUFACTURER', 8015,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 1(j) 사이클 기준 기대수명 (데이터포인트 31)', NULL, 'PUBLIC', 'PARSER', 'BATTERY#91', TRUE, NULL),
('REFERENCE_TEST_CONDITIONS_FOR_CYCLE_LIFE', 'BATTERY', 'PERFORMANCE', '사이클 수명 기준 시험조건', 'Reference Test Conditions for Cycle Life', 'STRING', NULL, TRUE, FALSE, 'MANUFACTURER', 8016,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 1(j) 기준 시험 (데이터포인트 32)', NULL, 'PUBLIC', 'PARSER', 'BATTERY#92', TRUE, NULL),
('CAPACITY_FADE_THRESHOLD_PCT', 'BATTERY', 'PERFORMANCE', '용량 감소 임계값', 'Capacity Fade Threshold %', 'NUMBER', '%', FALSE, FALSE, 'MANUFACTURER', 8017,
 'T1', '조건부 구속', 'Annex XIII 1(k) 용량 소진 임계값 (데이터포인트 33)', 'EV 배터리에 한함(LMT·산업용은 ''기재하지 않음'')', 'PUBLIC', 'PARSER', 'BATTERY#93', TRUE, '집행위 가이던스상 EV만 Mandatory'),
('MAXIMUM_CONTINUOUS_DISCHARGE_CURRENT_A', 'BATTERY', 'PERFORMANCE', '최대 연속 방전전류', 'Maximum Continuous Discharge Current A', 'NUMBER', 'A', FALSE, FALSE, 'MANUFACTURER', 8018,
 'T1', '조건부 구속', 'Annex XIII 1(i) 출력 한계의 세부', '한계값을 세분해 기재할 때', 'PUBLIC', 'PARSER', 'BATTERY#146', FALSE, '⚠원본 ''필수''이나 별도 조항 근거 없음'),
('MAXIMUM_PULSE_DISCHARGE_CURRENT_A', 'BATTERY', 'PERFORMANCE', '최대 펄스 방전전류', 'Maximum Pulse Discharge Current A', 'NUMBER', 'A', FALSE, FALSE, 'MANUFACTURER', 8019,
 'T1', '조건부 구속', 'Annex XIII 1(i) 출력 한계의 세부', '한계값을 세분해 기재할 때', 'PUBLIC', 'PARSER', 'BATTERY#147', FALSE, '⚠원본 ''필수''이나 별도 조항 근거 없음'),
('RECOMMENDED_CUT_OFF_VOLTAGE_V', 'BATTERY', 'PERFORMANCE', '권장 차단 전압', 'Recommended Cut off Voltage V', 'NUMBER', 'V', FALSE, FALSE, 'MANUFACTURER', 8020,
 'T1', '조건부 구속', 'Annex XIII 1(i) 출력 한계의 세부', '한계값을 세분해 기재할 때', 'PUBLIC', 'PARSER', 'BATTERY#148', FALSE, '⚠원본 ''필수''이나 별도 조항 근거 없음'),
('ENERGY_EFFICIENCY_ROUND_TRIP_PCT', 'BATTERY', 'PERFORMANCE', '왕복 에너지효율', 'Energy Efficiency Round Trip %', 'NUMBER', '%', TRUE, FALSE, 'MANUFACTURER', 8021,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 1(n) 최초 왕복효율 (데이터포인트 36)', NULL, 'PUBLIC', 'PARSER', 'BATTERY#199', TRUE, '⚠1(n)은 ''최초 왕복효율''과 ''사이클수명 50% 시점 왕복효율'' 두 값을 요구(데이터포인트 36·37, EV·LMT 모두 필수). 현재 1개 필드로는 데이터포인트 37이 누락됨'),
('CALENDAR_LIFE_EXPECTANCY_YEARS', 'BATTERY', 'PERFORMANCE', '달력수명 기대치', 'Calendar Life Expectancy Years', 'NUMBER', '년', FALSE, FALSE, 'MANUFACTURER', 8022,
 'T1', '조건부 구속', 'Annex XIII 4(a) 달력수명(연) (데이터포인트 60)', NULL, 'RESTRICTED', 'PARSER', 'BATTERY#220', TRUE, NULL),
('VIBRATION_TEST_STANDARD_UN38_3_PASSED', 'BATTERY', 'PERFORMANCE', 'UN 38.3 진동시험 합격 여부', 'Vibration Test Standard UN38 3 Passed', 'BOOLEAN', NULL, FALSE, FALSE, 'MANUFACTURER', 8023,
 'T1', '조건부 구속', 'UN 38.3(운송법: ADR·IMDG·IATA / Dir.2008/68/EC)', 'EU 역내 운송 시', 'PUBLIC', 'PARSER', 'BATTERY#280', FALSE, '⚠배터리규정 요건이 아님. 운송 위험물 규정 소관'),
('MECHANICAL_SHOCK_TEST_PASSED', 'BATTERY', 'PERFORMANCE', '기계적 충격시험 합격 여부', 'Mechanical Shock Test Passed', 'BOOLEAN', NULL, FALSE, FALSE, 'MANUFACTURER', 8024,
 'T1', '조건부 구속', 'UN 38.3 T4 기계적 충격', '동상', 'PUBLIC', 'PARSER', 'BATTERY#292', FALSE, '⚠배터리규정 요건 아님'),
('MAIN_PRODUCTION_ROUTE', 'STEEL', 'PROCESS', '주 생산경로(BF-BOF/EAF)', 'Main Production Route', 'CODE', NULL, TRUE, FALSE, 'MANUFACTURER', 9001,
 'T0', '구속', 'CBAM Impl.Reg.(EU)2025/2547 Annex IV pt.2 — ''사용된 주 환원제(main reducing agent)''', NULL, 'PUBLIC', 'MANUAL', 'STEEL#107', TRUE, '⚠필드 정의 수정 필요: 규정이 요구하는 것은 BF-BOF/EAF 생산경로가 아니라 ''주 환원제'''),
('IRONMAKING_PROCESS', 'STEEL', 'PROCESS', '제선 공정', 'Ironmaking Process', 'CODE', NULL, FALSE, FALSE, 'MANUFACTURER', 9002,
 'T1', '조건부 구속', 'CBAM Impl.Reg.(EU)2025/2547 Annex IV pt.2 — ''사용된 주 환원제'' 판정 보조', '생산경로 세분이 필요한 경우', 'PUBLIC', 'MANUAL', 'STEEL#108', TRUE, NULL),
('STEELMAKING_PROCESS', 'STEEL', 'PROCESS', '제강 공정', 'Steelmaking Process', 'CODE', NULL, FALSE, FALSE, 'MANUFACTURER', 9003,
 'T1', '조건부 구속', 'CBAM Impl.Reg.(EU)2025/2547 Annex IV pt.2 — ''사용된 주 환원제'' 판정 보조', '생산경로 세분이 필요한 경우', 'PUBLIC', 'MANUAL', 'STEEL#109', TRUE, NULL),
('SURFACE_TREATMENT_TYPE', 'STEEL', 'PROCESS', '표면처리 방식', 'Surface Treatment Type', 'CODE', NULL, FALSE, FALSE, 'MANUFACTURER', 9004,
 'T1', '조건부 구속', 'REACH Annex XVII·RoHS 연계 판단의 전제(도금 여부)', '도금·도장 제품일 때', 'PUBLIC', 'PARSER', 'STEEL#123', TRUE, NULL),
('TOTAL_SCRAP_INPUT_RATIO_PCT', 'STEEL', 'RESOURCE', '총 스크랩 투입비', 'Total Scrap Input Ratio %', 'NUMBER', '%', TRUE, FALSE, 'MANUFACTURER', 10001,
 'T0', '구속', 'CBAM Impl.Reg.(EU)2025/2547 Annex IV pt.2 — 제품 1t 생산에 사용된 스크랩 t', NULL, 'PUBLIC', 'MANUAL', 'STEEL#135', TRUE, '⚠단위 오류: 규정 단위는 %가 아니라 t/t'),
('PRE_CONSUMER_SCRAP_RATIO_PCT', 'STEEL', 'RESOURCE', '공정 스크랩 비율', 'Pre Consumer Scrap Ratio %', 'NUMBER', '%', TRUE, FALSE, 'MANUFACTURER', 10002,
 'T0', '구속', 'CBAM Impl.Reg.(EU)2025/2547 Annex IV pt.2 — 스크랩 중 pre-consumer 비율(%)', NULL, 'PUBLIC', 'MANUAL', 'STEEL#136', TRUE, NULL),
('CRM_COBALT_WEIGHT_KG', 'BATTERY', 'CRM', 'CRM 코발트 함유중량', 'CRM Cobalt Weight kg', 'NUMBER', 'kg', FALSE, FALSE, 'MANUFACTURER', 11001,
 'T1', '조건부 구속', 'Annex VI Part A(10) 중량 0.1% 초과 핵심원자재 (데이터포인트 15)', '해당 CRM이 중량 0.1%를 초과할 때', 'PUBLIC', 'PARSER', 'BATTERY#44', TRUE, '규정이 요구하는 것은 ''0.1% 초과 CRM의 존재''이며 kg 단위 중량은 아님'),
('CRM_COBALT_PERCENTAGE', 'BATTERY', 'CRM', 'CRM 코발트 함유비율', 'CRM Cobalt Percentage', 'NUMBER', NULL, FALSE, FALSE, 'MANUFACTURER', 11002,
 'T1', '조건부 구속', 'Annex VI Part A(10) 0.1% 초과 CRM (데이터포인트 15)', '해당 CRM이 0.1%를 초과할 때', 'PUBLIC', 'PARSER', 'BATTERY#45', TRUE, '⚠A(10)이 요구하는 것은 ''0.1%를 초과해 존재하는 CRM의 식별''이며 CRM별 함량 비율이 아니다. 집행위 데이터포인트도 15번 하나뿐. CRM 목록 필드 1개로 통합하고 비율은 자체 부가로 둘 것'),
('CRM_LITHIUM_WEIGHT_KG', 'BATTERY', 'CRM', 'CRM 리튬 함유중량', 'CRM Lithium Weight kg', 'NUMBER', 'kg', FALSE, FALSE, 'MANUFACTURER', 11003,
 'T1', '조건부 구속', 'Annex VI Part A(10) 중량 0.1% 초과 핵심원자재 (데이터포인트 15)', '해당 CRM이 중량 0.1%를 초과할 때', 'PUBLIC', 'PARSER', 'BATTERY#46', TRUE, '규정이 요구하는 것은 ''0.1% 초과 CRM의 존재''이며 kg 단위 중량은 아님'),
('CRM_LITHIUM_PERCENTAGE', 'BATTERY', 'CRM', 'CRM 리튬 함유비율', 'CRM Lithium Percentage', 'NUMBER', NULL, FALSE, FALSE, 'MANUFACTURER', 11004,
 'T1', '조건부 구속', 'Annex VI Part A(10) 0.1% 초과 CRM (데이터포인트 15)', '해당 CRM이 0.1%를 초과할 때', 'PUBLIC', 'PARSER', 'BATTERY#47', TRUE, 'No.45 참조'),
('CRM_NICKEL_WEIGHT_KG', 'BATTERY', 'CRM', 'CRM 니켈 함유중량', 'CRM Nickel Weight kg', 'NUMBER', 'kg', FALSE, FALSE, 'MANUFACTURER', 11005,
 'T1', '조건부 구속', 'Annex VI Part A(10) 중량 0.1% 초과 핵심원자재 (데이터포인트 15)', '해당 CRM이 중량 0.1%를 초과할 때', 'PUBLIC', 'PARSER', 'BATTERY#48', TRUE, '규정이 요구하는 것은 ''0.1% 초과 CRM의 존재''이며 kg 단위 중량은 아님'),
('CRM_NICKEL_PERCENTAGE', 'BATTERY', 'CRM', 'CRM 니켈 함유비율', 'CRM Nickel Percentage', 'NUMBER', NULL, FALSE, FALSE, 'MANUFACTURER', 11006,
 'T1', '조건부 구속', 'Annex VI Part A(10) 0.1% 초과 CRM (데이터포인트 15)', '해당 CRM이 0.1%를 초과할 때', 'PUBLIC', 'PARSER', 'BATTERY#49', TRUE, 'No.45 참조'),
('CRM_MANGANESE_WEIGHT_KG', 'BATTERY', 'CRM', 'CRM 망간 함유중량', 'CRM Manganese Weight kg', 'NUMBER', 'kg', FALSE, FALSE, 'MANUFACTURER', 11007,
 'T1', '조건부 구속', 'Annex VI Part A(10) 중량 0.1% 초과 핵심원자재 (데이터포인트 15)', '해당 CRM이 중량 0.1%를 초과할 때', 'PUBLIC', 'PARSER', 'BATTERY#50', TRUE, '규정이 요구하는 것은 ''0.1% 초과 CRM의 존재''이며 kg 단위 중량은 아님'),
('CRM_MANGANESE_PERCENTAGE', 'BATTERY', 'CRM', 'CRM 망간 함유비율', 'CRM Manganese Percentage', 'NUMBER', NULL, FALSE, FALSE, 'MANUFACTURER', 11008,
 'T1', '조건부 구속', 'Annex VI Part A(10) 0.1% 초과 CRM (데이터포인트 15)', '해당 CRM이 0.1%를 초과할 때', 'PUBLIC', 'PARSER', 'BATTERY#51', TRUE, 'No.45 참조'),
('CRM_NATURAL_GRAPHITE_WEIGHT_KG', 'BATTERY', 'CRM', 'CRM 천연흑연 함유중량', 'CRM Natural Graphite Weight kg', 'NUMBER', 'kg', FALSE, FALSE, 'MANUFACTURER', 11009,
 'T1', '조건부 구속', 'Annex VI Part A(10) 중량 0.1% 초과 핵심원자재 (데이터포인트 15)', '해당 CRM이 중량 0.1%를 초과할 때', 'PUBLIC', 'PARSER', 'BATTERY#52', TRUE, '규정이 요구하는 것은 ''0.1% 초과 CRM의 존재''이며 kg 단위 중량은 아님'),
('CRM_NATURAL_GRAPHITE_PERCENTAGE', 'BATTERY', 'CRM', 'CRM 천연흑연 함유비율', 'CRM Natural Graphite Percentage', 'NUMBER', NULL, FALSE, FALSE, 'MANUFACTURER', 11010,
 'T1', '조건부 구속', 'Annex VI Part A(10) 0.1% 초과 CRM (데이터포인트 15)', '해당 CRM이 0.1%를 초과할 때', 'PUBLIC', 'PARSER', 'BATTERY#53', TRUE, 'No.45 참조'),
('CRM_LEAD_WEIGHT_KG', 'BATTERY', 'CRM', 'CRM 납 함유중량', 'CRM Lead Weight kg', 'NUMBER', 'kg', FALSE, FALSE, 'MANUFACTURER', 11011,
 'T1', '조건부 구속', 'Annex I 납 제한 / Annex VI Part A(10) 중량 0.1% 초과 핵심원자재 (데이터포인트 15)', '납축전지일 때', 'PUBLIC', 'PARSER', 'BATTERY#54', FALSE, NULL),
('CRM_LEAD_PERCENTAGE', 'BATTERY', 'CRM', 'CRM 납 함유비율', 'CRM Lead Percentage', 'NUMBER', NULL, FALSE, FALSE, 'MANUFACTURER', 11012,
 'T1', '조건부 구속', 'Annex VI Part A(10) 중량 0.1% 초과 핵심원자재 (데이터포인트 15)', '납이 0.1%를 초과할 때', 'PUBLIC', 'PARSER', 'BATTERY#55', FALSE, NULL),
('CRM_COPPER_WEIGHT_KG', 'BATTERY', 'CRM', 'CRM 구리 함유중량', 'CRM Copper Weight kg', 'NUMBER', 'kg', FALSE, FALSE, 'MANUFACTURER', 11013,
 'T1', '조건부 구속', 'Annex VI Part A(10) 중량 0.1% 초과 핵심원자재 (데이터포인트 15)', '해당 원소가 CRM 목록에 있고 0.1%를 초과할 때', 'PUBLIC', 'PARSER', 'BATTERY#56', FALSE, 'Cu·Al·Fe·P는 EU CRM 목록 해당 여부를 확인해야 함'),
('CRM_ALUMINUM_WEIGHT_KG', 'BATTERY', 'CRM', 'CRM 알루미늄 함유중량', 'CRM Aluminum Weight kg', 'NUMBER', 'kg', FALSE, FALSE, 'MANUFACTURER', 11014,
 'T1', '조건부 구속', 'Annex VI Part A(10) 중량 0.1% 초과 핵심원자재 (데이터포인트 15)', '해당 원소가 CRM 목록에 있고 0.1%를 초과할 때', 'PUBLIC', 'PARSER', 'BATTERY#57', FALSE, 'Cu·Al·Fe·P는 EU CRM 목록 해당 여부를 확인해야 함'),
('CRM_IRON_WEIGHT_KG', 'BATTERY', 'CRM', 'CRM 철 함유중량', 'CRM Iron Weight kg', 'NUMBER', 'kg', FALSE, FALSE, 'MANUFACTURER', 11015,
 'T1', '조건부 구속', 'Annex VI Part A(10) 중량 0.1% 초과 핵심원자재 (데이터포인트 15)', '해당 원소가 CRM 목록에 있고 0.1%를 초과할 때', 'PUBLIC', 'PARSER', 'BATTERY#58', FALSE, 'Cu·Al·Fe·P는 EU CRM 목록 해당 여부를 확인해야 함'),
('CRM_PHOSPHORUS_WEIGHT_KG', 'BATTERY', 'CRM', 'CRM 인 함유중량', 'CRM Phosphorus Weight kg', 'NUMBER', 'kg', FALSE, FALSE, 'MANUFACTURER', 11016,
 'T1', '조건부 구속', 'Annex VI Part A(10) 중량 0.1% 초과 핵심원자재 (데이터포인트 15)', '해당 원소가 CRM 목록에 있고 0.1%를 초과할 때', 'PUBLIC', 'PARSER', 'BATTERY#59', FALSE, 'Cu·Al·Fe·P는 EU CRM 목록 해당 여부를 확인해야 함'),
('CRM_TANTALUM_WEIGHT_KG', 'BATTERY', 'CRM', 'CRM 탄탈럼 함유중량', 'CRM Tantalum Weight kg', 'NUMBER', 'kg', FALSE, FALSE, 'MANUFACTURER', 11017,
 'T1', '조건부 구속', 'Annex VI Part A(10) 중량 0.1% 초과 핵심원자재 (데이터포인트 15)', '해당 원소가 0.1%를 초과할 때', 'PUBLIC', 'PARSER', 'BATTERY#142', FALSE, NULL),
('CRM_SILICON_WEIGHT_KG', 'BATTERY', 'CRM', 'CRM 실리콘 함유중량', 'CRM Silicon Weight kg', 'NUMBER', 'kg', FALSE, FALSE, 'MANUFACTURER', 11018,
 'T1', '조건부 구속', 'Annex VI Part A(10) 중량 0.1% 초과 핵심원자재 (데이터포인트 15)', '해당 원소가 0.1%를 초과할 때', 'PUBLIC', 'PARSER', 'BATTERY#143', FALSE, NULL),
('BLOCKCHAIN_TRACEABILITY_PLATFORM_ID', 'BATTERY', 'CRM', '블록체인 추적 플랫폼 ID', 'Blockchain Traceability Platform ID', 'STRING', NULL, FALSE, TRUE, NULL, 11019,
 'T1', '조건부 구속', 'Art.77(8) 여권 기술설계 위임법(미채택) / 자사 아키텍처', '블록체인 원장 채택 시', 'PUBLIC', 'SYSTEM', 'BATTERY#242', TRUE, '⚠원본 ''선택''이나 본 프로젝트의 핵심 차별화 요소. MVP 필수 승격 권장'),
('SHARE_OF_RENEWABLE_ENERGY_USED_PCT', 'BATTERY', 'CARBON', '재생에너지 사용 비율', 'Share of Renewable Energy Used %', 'NUMBER', '%', FALSE, FALSE, 'TEST_LAB', 12001,
 'T1', '조건부 구속', 'Annex XIII 1(f) 재생가능 함량 비중 (데이터포인트 24)', NULL, 'PUBLIC', 'MANUAL', 'BATTERY#112', TRUE, '⚠필드 정의 확인 필요: 1(f)는 ''재생가능 원료 함량''이며 ''제조 시 재생에너지 사용 비율''과 다름'),
('PCF_VALUE', 'COMMON', 'CARBON', '단위당 내재배출량', 'Specific Embedded Emissions tCO2e per t', 'NUMBER', NULL, TRUE, FALSE, 'TEST_LAB', 12002,
 'T0', '구속', 'CBAM Art.6(2)(b) 제품 t당 내재배출량', NULL, 'PUBLIC', 'PARSER', 'STEEL#148', TRUE, NULL),
('CBAM_DIRECT_EMISSIONS_TCO2E_PER_T', 'STEEL', 'CARBON', 'CBAM 직접배출량', 'CBAM Direct Emissions tCO2e per t', 'NUMBER', 'tCO2e/t', TRUE, FALSE, 'TEST_LAB', 12003,
 'T0', '구속', 'CBAM Art.7(1) + Annex IV(산정방법), Annex II(직접배출만 대상 goods)', NULL, 'PUBLIC', 'PARSER', 'STEEL#149', TRUE, NULL),
('CBAM_INDIRECT_EMISSIONS_TCO2E_PER_T', 'STEEL', 'CARBON', 'CBAM 간접배출량', 'CBAM Indirect Emissions tCO2e per t', 'NUMBER', 'tCO2e/t', FALSE, FALSE, 'TEST_LAB', 12004,
 'T1', '조건부 구속', 'CBAM Art.7(1) — 철강은 Annex II ''직접배출만'' 대상', '소결광(CN 2601 12 00) 또는 전구체로 유입된 소결광 간접배출분에 한함', 'PUBLIC', 'PARSER', 'STEEL#150', TRUE, '⚠원본 ''CBAM 필수''는 과잉. 선철·DRI·조강·강재는 간접배출 산정·납부 대상이 아님'),
('CBAM_ACTUAL_DATA_USED_RATIO_PCT', 'STEEL', 'CARBON', 'CBAM 실측데이터 사용비율', 'CBAM Actual Data Used Ratio %', 'NUMBER', '%', FALSE, FALSE, 'TEST_LAB', 12005,
 'T1', '조건부 구속', 'CBAM Impl.Reg.2025/2547 Art.15 실측·기본값 혼용', '실측값과 기본값을 혼용할 때', 'PUBLIC', 'PARSER', 'STEEL#151', TRUE, NULL),
('CBAM_DEFAULT_VALUE_USED_RATIO_PCT', 'STEEL', 'CARBON', 'CBAM 기본값 사용비율', 'CBAM Default Value Used Ratio %', 'NUMBER', '%', FALSE, FALSE, 'TEST_LAB', 12006,
 'T1', '조건부 구속', 'CBAM Impl.Reg.2025/2547 Art.15 실측·기본값 혼용', '실측값과 기본값을 혼용할 때', 'PUBLIC', 'PARSER', 'STEEL#152', TRUE, NULL),
('ELECTRICITY_EMISSION_FACTOR_TCO2E_PER_MWH', 'STEEL', 'CARBON', '전력 배출계수', 'Electricity Emission Factor tCO2e per MWh', 'NUMBER', 'tCO2e/MWh', FALSE, FALSE, 'TEST_LAB', 12007,
 'T1', '조건부 구속', 'CBAM Impl.Reg.2025/2547 Art.8~9 전력 배출계수', '간접배출이 대상인 소결광에 한함', 'TRADE_SECRET', 'PARSER', 'STEEL#153', FALSE, '⚠원본 ''CBAM 필수''는 오류. 전기로 조강의 계통 배출계수는 CBAM 산정 입력이 아님'),
('ELECTRICITY_SOURCE', 'STEEL', 'CARBON', '전력 조달 방식', 'Electricity Source', 'CODE', NULL, FALSE, FALSE, 'TEST_LAB', 12008,
 'T1', '조건부 구속', 'CBAM Impl.Reg.2025/2547 Art.8~9 전력 배출계수', '간접배출이 대상인 소결광에 한함', 'TRADE_SECRET', 'PARSER', 'STEEL#154', FALSE, '⚠원본 ''CBAM 필수''는 오류. 전기로 조강의 계통 배출계수는 CBAM 산정 입력이 아님'),
('CARBON_PRICE_PAID_IN_ORIGIN_COUNTRY', 'STEEL', 'CARBON', '원산지국 납부 탄소가격', 'Carbon Price Paid in Origin Country', 'NUMBER', NULL, FALSE, FALSE, 'TEST_LAB', 12009,
 'T1', '조건부 구속', 'CBAM Art.9 원산국 탄소가격 공제 청구', '공제를 청구할 때만(확정 규정에서는 의무 항목 아님)', 'RESTRICTED', 'MANUAL', 'STEEL#171', FALSE, '⚠원본 ''CBAM 필수''는 전환기 기준. 확정 규정에서는 선택적 청구 항목이며 환급·무상할당분을 차감해야 함'),
('CARBON_PRICE_CURRENCY', 'STEEL', 'CARBON', '탄소가격 통화', 'Carbon Price Currency', 'STRING', NULL, FALSE, FALSE, 'TEST_LAB', 12010,
 'T1', '조건부 구속', 'CBAM Art.9 원산국 탄소가격 공제 청구', '공제를 청구할 때만(확정 규정에서는 의무 항목 아님)', 'RESTRICTED', 'MANUAL', 'STEEL#172', FALSE, '⚠원본 ''CBAM 필수''는 전환기 기준. 확정 규정에서는 선택적 청구 항목이며 환급·무상할당분을 차감해야 함'),
('CARBON_PRICE_REBATE_OR_FREE_ALLOCATION_PCT', 'STEEL', 'CARBON', '탄소가격 환급·무상할당 비율', 'Carbon Price Rebate or Free Allocation %', 'NUMBER', '%', FALSE, FALSE, 'TEST_LAB', 12011,
 'T1', '조건부 구속', 'CBAM Art.9 원산국 탄소가격 공제 청구', '공제를 청구할 때만(확정 규정에서는 의무 항목 아님)', 'RESTRICTED', 'MANUAL', 'STEEL#173', FALSE, '⚠원본 ''CBAM 필수''는 전환기 기준. 확정 규정에서는 선택적 청구 항목이며 환급·무상할당분을 차감해야 함'),
('PRECURSOR_1_NAME', 'STEEL', 'CARBON', '전구체 1 명칭', 'Precursor 1 Name', 'STRING', NULL, FALSE, FALSE, 'TEST_LAB', 12012,
 'T1', '조건부 구속', 'CBAM Art.7(1)+Annex IV / Impl.Reg.2025/2547 Art.13~14 전구체', 'Annex I 대상재인 전구체를 투입한 경우', 'TRADE_SECRET', 'PARSER', 'STEEL#174', TRUE, NULL),
('PRECURSOR_1_QUANTITY_T_PER_T', 'STEEL', 'CARBON', '전구체 1 투입량', 'Precursor 1 Quantity t per t', 'NUMBER', 't/t', FALSE, FALSE, 'TEST_LAB', 12013,
 'T1', '조건부 구속', 'CBAM Art.7(1)+Annex IV / Impl.Reg.2025/2547 Art.13~14 전구체', 'Annex I 대상재인 전구체를 투입한 경우', 'TRADE_SECRET', 'PARSER', 'STEEL#175', TRUE, NULL),
('PRECURSOR_1_SPECIFIC_EMISSIONS', 'STEEL', 'CARBON', '전구체 1 단위 배출량', 'Precursor 1 Specific Emissions', 'NUMBER', NULL, FALSE, FALSE, 'TEST_LAB', 12014,
 'T1', '조건부 구속', 'CBAM Art.7(1)+Annex IV / Impl.Reg.2025/2547 Art.13~14 전구체', 'Annex I 대상재인 전구체를 투입한 경우', 'TRADE_SECRET', 'PARSER', 'STEEL#176', TRUE, NULL),
('PRECURSOR_2_NAME', 'STEEL', 'CARBON', '전구체 2 명칭', 'Precursor 2 Name', 'STRING', NULL, FALSE, FALSE, 'TEST_LAB', 12015,
 'T1', '계약·표준', '동상(전구체 2·3)', '전구체가 복수일 때', 'TRADE_SECRET', 'PARSER', 'STEEL#265', FALSE, '10개 슬롯 플랫 컬럼 대신 전구체 자식 테이블로 정규화 권장'),
('PRECURSOR_2_QUANTITY_T_PER_T', 'STEEL', 'CARBON', '전구체 2 투입량', 'Precursor 2 Quantity t per t', 'NUMBER', 't/t', FALSE, FALSE, 'TEST_LAB', 12016,
 'T1', '계약·표준', '동상(전구체 2·3)', '전구체가 복수일 때', 'TRADE_SECRET', 'PARSER', 'STEEL#266', FALSE, '10개 슬롯 플랫 컬럼 대신 전구체 자식 테이블로 정규화 권장'),
('PRECURSOR_2_SPECIFIC_EMISSIONS', 'STEEL', 'CARBON', '전구체 2 단위 배출량', 'Precursor 2 Specific Emissions', 'NUMBER', NULL, FALSE, FALSE, 'TEST_LAB', 12017,
 'T1', '계약·표준', '동상(전구체 2·3)', '전구체가 복수일 때', 'TRADE_SECRET', 'PARSER', 'STEEL#267', FALSE, '10개 슬롯 플랫 컬럼 대신 전구체 자식 테이블로 정규화 권장'),
('PRECURSOR_3_NAME', 'STEEL', 'CARBON', '전구체 3 명칭', 'Precursor 3 Name', 'STRING', NULL, FALSE, FALSE, 'TEST_LAB', 12018,
 'T1', '계약·표준', '동상(전구체 2·3)', '전구체가 복수일 때', 'TRADE_SECRET', 'PARSER', 'STEEL#268', FALSE, '10개 슬롯 플랫 컬럼 대신 전구체 자식 테이블로 정규화 권장'),
('PRECURSOR_3_QUANTITY_T_PER_T', 'STEEL', 'CARBON', '전구체 3 투입량', 'Precursor 3 Quantity t per t', 'NUMBER', 't/t', FALSE, FALSE, 'TEST_LAB', 12019,
 'T1', '계약·표준', '동상(전구체 2·3)', '전구체가 복수일 때', 'TRADE_SECRET', 'PARSER', 'STEEL#269', FALSE, '10개 슬롯 플랫 컬럼 대신 전구체 자식 테이블로 정규화 권장'),
('PRECURSOR_3_SPECIFIC_EMISSIONS', 'STEEL', 'CARBON', '전구체 3 단위 배출량', 'Precursor 3 Specific Emissions', 'NUMBER', NULL, FALSE, FALSE, 'TEST_LAB', 12020,
 'T1', '계약·표준', '동상(전구체 2·3)', '전구체가 복수일 때', 'TRADE_SECRET', 'PARSER', 'STEEL#270', FALSE, '10개 슬롯 플랫 컬럼 대신 전구체 자식 테이블로 정규화 권장'),
('CBAM_EMISSIONS_VERIFIED_BY_THIRD_PARTY', 'STEEL', 'CARBON', 'CBAM 배출량 제3자 검증 여부', 'CBAM Emissions Verified By Third Party', 'BOOLEAN', NULL, FALSE, FALSE, 'TEST_LAB', 12021,
 'T1', '조건부 구속', 'CBAM Art.8 + Annex VI / Impl.Reg.(EU)2025/2546 검증', '실측값을 사용할 때만(기본값만 쓰면 검증 불요)', 'PUBLIC', 'PARSER', 'STEEL#271', TRUE, NULL),
('CBAM_VERIFICATION_BODY_NAME', 'STEEL', 'CARBON', 'CBAM 검증기관명', 'CBAM Verification Body Name', 'STRING', NULL, FALSE, FALSE, 'TEST_LAB', 12022,
 'T1', '조건부 구속', 'CBAM Art.8 + Annex VI / Impl.Reg.(EU)2025/2546 검증', '실측값을 사용할 때만(기본값만 쓰면 검증 불요)', 'PUBLIC', 'PARSER', 'STEEL#272', TRUE, NULL),
('CBAM_VERIFICATION_REPORT_URL', 'STEEL', 'CARBON', 'CBAM 검증보고서 URL', 'CBAM Verification Report URL', 'URL', NULL, FALSE, FALSE, 'TEST_LAB', 12023,
 'T1', '조건부 구속', 'CBAM Art.8 + Annex VI / Impl.Reg.(EU)2025/2546 검증', '실측값을 사용할 때만(기본값만 쓰면 검증 불요)', 'PUBLIC', 'PARSER', 'STEEL#273', TRUE, NULL),
('SVHC_PRESENT', 'BATTERY', 'HAZARD', 'SVHC 함유 여부', 'SVHC Present', 'BOOLEAN', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13001,
 'T1', '조건부 구속', 'REACH Art.33(1) + SCIP', 'SVHC가 0.1% w/w를 초과할 때', 'PUBLIC', 'PARSER', 'BATTERY#94', TRUE, '⚠Annex VI A(8) 인용은 오류. A(8)은 CLP(EC)1272/2008상 ''유해물질''(수은·카드뮴·납 제외)이고 SVHC는 REACH Art.57·59 후보물질목록 개념으로 서로 다른 집합이다. A(8)에 대응하는 필드(데이터포인트 13)는 별도로 신설해야 함'),
('SVHC_SUBSTANCE_NAME_1', 'BATTERY', 'HAZARD', 'SVHC 1 물질명', 'SVHC Substance Name 1', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13002,
 'T1', '조건부 구속', 'REACH Art.33(1) 물질명 / SCIP', 'SVHC가 0.1% w/w를 초과할 때', 'PUBLIC', 'PARSER', 'BATTERY#95', TRUE, '배터리규정 여권 데이터포인트가 아님. REACH·SCIP 근거로만 유지'),
('SVHC_SUBSTANCE_CAS_NUMBER_1', 'BATTERY', 'HAZARD', 'SVHC 1 CAS 번호', 'SVHC Substance CAS Number 1', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13003,
 'T1', '계약·표준', 'SCIP는 EC·CAS를 ''확인 가능한 경우''에 한해 요구', 'CAS가 확인되는 경우', 'PUBLIC', 'PARSER', 'BATTERY#96', TRUE, NULL),
('SVHC_CONCENTRATION_PCT_1', 'BATTERY', 'HAZARD', 'SVHC 1 농도', 'SVHC Concentration % 1', 'NUMBER', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13004,
 'T1', '조건부 구속', '폐기물기본지침 Art.9(1)(i) SCIP 농도구간', 'SVHC가 0.1% w/w를 초과할 때', 'PUBLIC', 'PARSER', 'BATTERY#97', TRUE, 'SCIP는 정확한 수치가 아니라 사전정의 밴드를 요구'),
('SVHC_LOCATION_IN_BATTERY_1', 'BATTERY', 'HAZARD', 'SVHC 1 함유 부위', 'SVHC Location in Battery 1', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13005,
 'T1', '계약·표준', 'SCIP complex object 계층 — ''as appropriate''', '구성품 단위 위치 특정이 적절한 경우', 'PUBLIC', 'PARSER', 'BATTERY#98', TRUE, NULL),
('SVHC_SUBSTANCE_NAME_2', 'BATTERY', 'HAZARD', 'SVHC 2 물질명', 'SVHC Substance Name 2', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13006,
 'T1', '조건부 구속', 'REACH Art.33(1) 물질명 / SCIP', 'SVHC가 2종 이상일 때', 'PUBLIC', 'PARSER', 'BATTERY#151', TRUE, '배터리규정 여권 데이터포인트 아님'),
('SVHC_SUBSTANCE_CAS_NUMBER_2', 'BATTERY', 'HAZARD', 'SVHC 2 CAS 번호', 'SVHC Substance CAS Number 2', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13007,
 'T1', '계약·표준', 'SCIP는 EC·CAS를 ''확인 가능한 경우''에 한해 요구', 'CAS가 확인되는 경우', 'PUBLIC', 'PARSER', 'BATTERY#152', TRUE, NULL),
('SVHC_CONCENTRATION_PCT_2', 'BATTERY', 'HAZARD', 'SVHC 2 농도', 'SVHC Concentration % 2', 'NUMBER', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13008,
 'T1', '조건부 구속', '폐기물기본지침 Art.9(1)(i) SCIP 농도구간', 'SVHC가 0.1% w/w를 초과할 때', 'PUBLIC', 'PARSER', 'BATTERY#153', TRUE, 'SCIP는 정확한 수치가 아니라 사전정의 밴드를 요구'),
('SVHC_LOCATION_IN_BATTERY_2', 'BATTERY', 'HAZARD', 'SVHC 2 함유 부위', 'SVHC Location in Battery 2', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13009,
 'T1', '계약·표준', 'SCIP complex object 계층 — ''as appropriate''', '구성품 단위 위치 특정이 적절한 경우', 'PUBLIC', 'PARSER', 'BATTERY#154', TRUE, NULL),
('SVHC_SUBSTANCE_NAME_3', 'BATTERY', 'HAZARD', 'SVHC 3 물질명', 'SVHC Substance Name 3', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13010,
 'T1', '조건부 구속', 'REACH Art.33(1) 물질명 / SCIP', 'SVHC가 3종 이상일 때', 'PUBLIC', 'PARSER', 'BATTERY#155', TRUE, '배터리규정 여권 데이터포인트 아님'),
('SVHC_SUBSTANCE_CAS_NUMBER_3', 'BATTERY', 'HAZARD', 'SVHC 3 CAS 번호', 'SVHC Substance CAS Number 3', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13011,
 'T1', '계약·표준', 'SCIP는 EC·CAS를 ''확인 가능한 경우''에 한해 요구', 'CAS가 확인되는 경우', 'PUBLIC', 'PARSER', 'BATTERY#156', TRUE, NULL),
('SVHC_CONCENTRATION_PCT_3', 'BATTERY', 'HAZARD', 'SVHC 3 농도', 'SVHC Concentration % 3', 'NUMBER', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13012,
 'T1', '조건부 구속', '폐기물기본지침 Art.9(1)(i) SCIP 농도구간', 'SVHC가 0.1% w/w를 초과할 때', 'PUBLIC', 'PARSER', 'BATTERY#157', TRUE, 'SCIP는 정확한 수치가 아니라 사전정의 밴드를 요구'),
('REACH_CANDIDATE_LIST_UPDATE_VERSION', 'BATTERY', 'HAZARD', 'REACH 후보목록 개정판', 'REACH Candidate List Update Version', 'STRING', NULL, FALSE, TRUE, NULL, 13013,
 'T1', '조건부 구속', 'REACH 후보물질목록 갱신 대응(운영 관리)', '후보목록 개정 시 재판정할 때', 'PUBLIC', 'SYSTEM', 'BATTERY#232', TRUE, '규정 필드는 아니나 판정 로직 버전 관리에 필요'),
('HAZARDOUS_WASTE_CLASSIFICATION_CODE', 'BATTERY', 'HAZARD', '유해폐기물 분류코드', 'Hazardous Waste Classification Code', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13014,
 'T1', '조건부 구속', '폐기물목록결정 2000/532/EC 폐기물 분류코드', '폐기 단계 정보를 기재할 때', 'PUBLIC', 'MANUAL', 'BATTERY#245', FALSE, NULL),
('INCINERATION_RESTRICTION_NOTICE_URL', 'BATTERY', 'HAZARD', '소각 금지 고지 URL', 'Incineration Restriction Notice URL', 'URL', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13015,
 'T1', '조건부 구속', 'Annex XIII 1(s) / Art.74(1) 폐기물 예방·관리 정보', NULL, 'PUBLIC', 'MANUAL', 'BATTERY#281', FALSE, NULL),
('REACH_ARTICLE_33_COMMUNICATION_CHECK', 'BATTERY', 'HAZARD', 'REACH 33조 정보전달 확인', 'REACH Article 33 Communication Check', 'BOOLEAN', NULL, FALSE, TRUE, NULL, 13016,
 'T1', '조건부 구속', 'REACH Art.33(1) 이행 확인(운영)', 'SVHC 0.1% 초과 시', 'PUBLIC', 'SYSTEM', 'BATTERY#293', FALSE, NULL),
('SVHC_PRESENCE_IN_COATING', 'STEEL', 'HAZARD', '도금·도장층 SVHC 함유 여부', 'SVHC Presence in Coating', 'BOOLEAN', NULL, TRUE, FALSE, 'RAW_SUPPLIER', 13017,
 'T0', '구속', 'REACH Art.33(1) 0.1% w/w 초과 SVHC 통지 / 폐기물기본지침 Art.9(1)(i) SCIP', NULL, 'PUBLIC', 'PARSER', 'STEEL#193', TRUE, 'Art.33(1)은 공급망(B2B) 통지 의무이며 소비자에게는 Art.33(2)에 따라 ''요청 시'' 45일 내 제공'),
('SVHC_SUBSTANCE_NAME', 'STEEL', 'HAZARD', 'SVHC 물질명', 'SVHC Substance Name', 'STRING', NULL, TRUE, FALSE, 'RAW_SUPPLIER', 13018,
 'T0', '구속', 'REACH Art.33(1) — 물질명은 법정 최소 항목 / SCIP 신고 필수 요소', NULL, 'PUBLIC', 'PARSER', 'STEEL#194', TRUE, NULL),
('SVHC_CAS_NUMBER', 'STEEL', 'HAZARD', 'SVHC CAS 번호', 'SVHC CAS Number', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13019,
 'T1', '위임법 대기', 'SCIP는 EC·CAS를 ''확인 가능한 경우''에 한해 요구 / ESPR Art.7(5)(a)(iv)도 ''if available''', 'CAS 번호가 확인되는 경우', 'PUBLIC', 'PARSER', 'STEEL#195', TRUE, '⚠법정 필수 항목이 아님. 원본 ''검출시 필수''보다 약함'),
('SVHC_CONCENTRATION_PCT', 'STEEL', 'HAZARD', 'SVHC 농도', 'SVHC Concentration %', 'NUMBER', '%', TRUE, FALSE, 'RAW_SUPPLIER', 13020,
 'T0', '구속', '폐기물기본지침 2008/98/EC Art.9(1)(i) SCIP 농도구간(필수 요소)', NULL, 'PUBLIC', 'PARSER', 'STEEL#196', TRUE, 'SCIP는 정확한 수치가 아니라 사전정의 농도 밴드를 요구. Float 대신 Enum 권장'),
('ROHS_COMPLIANT_STATUS', 'STEEL', 'HAZARD', 'RoHS 적합 여부', 'RoHS Compliant Status', 'BOOLEAN', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13021,
 'T1', '계약·표준', 'RoHS 2011/65/EU', '해당 강재가 전기전자제품(EEE)에 편입되는 경우에 한함', 'PUBLIC', 'PARSER', 'STEEL#197', FALSE, '⚠강재 자체는 RoHS 적용 대상이 아님. 원본 ''해당시 필수''의 조건을 EEE 편입으로 명시할 것'),
('HEXAVALENT_CHROMIUM_CR6_PRESENCE', 'STEEL', 'HAZARD', '6가크롬 함유 여부', 'Hexavalent Chromium Cr6 Presence', 'BOOLEAN', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13022,
 'T1', '조건부 구속', 'REACH Annex XVII / 크롬산 계열 authorisation', '도금·표면처리 제품일 때', 'PUBLIC', 'PARSER', 'STEEL#198', TRUE, NULL),
('DYEING_METHOD', 'TEXTILE', 'HAZARD', '염색 방식', 'Dyeing Method', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13023,
 'T1', '조건부 구속', 'REACH Annex XVII 43(아조염료)·72(폼알데하이드 등) 적합성 판단의 전제', '염색 공정을 거친 제품', 'PUBLIC', 'MANUAL', 'TEXTILE#61', TRUE, NULL),
('SVHC_1_SUBSTANCE_NAME', 'TEXTILE', 'HAZARD', 'SVHC 1 물질명', 'SVHC 1 Substance Name', 'STRING', NULL, TRUE, FALSE, 'RAW_SUPPLIER', 13024,
 'T0', '구속', 'REACH Art.33(1) 물질명 / ESPR Art.7(5)(a) / SCIP', NULL, 'PUBLIC', 'PARSER', 'TEXTILE#63', TRUE, NULL),
('SVHC_1_CAS_NUMBER', 'TEXTILE', 'HAZARD', 'SVHC 1 CAS 번호', 'SVHC 1 CAS Number', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13025,
 'T1', '위임법 대기', 'SCIP는 EC·CAS를 ''확인 가능한 경우''에 한해 요구 / ESPR Art.7(5)(a)(iv) ''if available''', 'CAS 번호가 확인되는 경우', 'PUBLIC', 'PARSER', 'TEXTILE#64', TRUE, NULL),
('SVHC_1_CONCENTRATION_PCT', 'TEXTILE', 'HAZARD', 'SVHC 1 농도', 'SVHC 1 Concentration %', 'NUMBER', '%', TRUE, FALSE, 'RAW_SUPPLIER', 13026,
 'T0', '구속', '폐기물기본지침 2008/98/EC Art.9(1)(i) SCIP 농도구간(필수 요소)', NULL, 'PUBLIC', 'PARSER', 'TEXTILE#65', TRUE, 'SCIP는 사전정의 밴드를 요구. Float 대신 Enum(밴드) 권장'),
('SVHC_1_LOCATION_IN_PRODUCT', 'TEXTILE', 'HAZARD', 'SVHC 1 함유 부위', 'SVHC 1 Location in Product', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13027,
 'T1', '위임법 대기', 'SCIP complex object 계층 — ''as appropriate'' 요건 / ESPR Art.7(5)(b)', '구성품 단위 위치 특정이 적절한 경우', 'PUBLIC', 'PARSER', 'TEXTILE#66', TRUE, 'SCIP는 자유 텍스트가 아닌 구성품 계층 구조를 요구'),
('SVHC_1_TEST_REPORT_URL', 'TEXTILE', 'HAZARD', 'SVHC 1 시험성적서 URL', 'SVHC 1 Test Report URL', 'URL', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13028,
 'T1', '계약·표준', '시험성적서(증빙)', '시험을 수행한 경우', 'RESTRICTED', 'PARSER', 'TEXTILE#67', TRUE, NULL),
('SVHC_2_SUBSTANCE_NAME', 'TEXTILE', 'HAZARD', 'SVHC 2 물질명', 'SVHC 2 Substance Name', 'STRING', NULL, TRUE, FALSE, 'RAW_SUPPLIER', 13029,
 'T0', '구속', 'REACH Art.33(1) 물질명 / ESPR Art.7(5)(a) / SCIP', NULL, 'PUBLIC', 'PARSER', 'TEXTILE#68', TRUE, NULL),
('SVHC_2_CAS_NUMBER', 'TEXTILE', 'HAZARD', 'SVHC 2 CAS 번호', 'SVHC 2 CAS Number', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13030,
 'T1', '계약·표준', 'SCIP는 EC·CAS를 ''확인 가능한 경우''에 한해 요구', 'CAS 번호가 확인되는 경우', 'PUBLIC', 'PARSER', 'TEXTILE#69', TRUE, NULL),
('SVHC_2_CONCENTRATION_PCT', 'TEXTILE', 'HAZARD', 'SVHC 2 농도', 'SVHC 2 Concentration %', 'NUMBER', '%', TRUE, FALSE, 'RAW_SUPPLIER', 13031,
 'T0', '구속', '폐기물기본지침 2008/98/EC Art.9(1)(i) SCIP 농도구간(필수 요소)', NULL, 'PUBLIC', 'PARSER', 'TEXTILE#70', TRUE, 'SCIP는 사전정의 밴드를 요구. Float 대신 Enum(밴드) 권장'),
('SVHC_2_LOCATION_IN_PRODUCT', 'TEXTILE', 'HAZARD', 'SVHC 2 함유 부위', 'SVHC 2 Location in Product', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13032,
 'T1', '위임법 대기', 'SCIP complex object 계층 — ''as appropriate'' 요건 / ESPR Art.7(5)(b)', '구성품 단위 위치 특정이 적절한 경우', 'PUBLIC', 'PARSER', 'TEXTILE#71', TRUE, 'SCIP는 자유 텍스트가 아닌 구성품 계층 구조를 요구'),
('SVHC_2_TEST_REPORT_URL', 'TEXTILE', 'HAZARD', 'SVHC 2 시험성적서 URL', 'SVHC 2 Test Report URL', 'URL', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13033,
 'T1', '계약·표준', '시험성적서(증빙)', '시험을 수행한 경우', 'RESTRICTED', 'PARSER', 'TEXTILE#72', TRUE, NULL),
('SVHC_3_SUBSTANCE_NAME', 'TEXTILE', 'HAZARD', 'SVHC 3 물질명', 'SVHC 3 Substance Name', 'STRING', NULL, TRUE, FALSE, 'RAW_SUPPLIER', 13034,
 'T0', '구속', 'REACH Art.33(1) 물질명 / ESPR Art.7(5)(a) / SCIP', NULL, 'PUBLIC', 'PARSER', 'TEXTILE#73', TRUE, NULL),
('SVHC_3_CAS_NUMBER', 'TEXTILE', 'HAZARD', 'SVHC 3 CAS 번호', 'SVHC 3 CAS Number', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13035,
 'T1', '계약·표준', 'SCIP는 EC·CAS를 ''확인 가능한 경우''에 한해 요구', 'CAS 번호가 확인되는 경우', 'PUBLIC', 'PARSER', 'TEXTILE#74', TRUE, NULL),
('PFAS_PRESENCE', 'TEXTILE', 'HAZARD', 'PFAS 함유 여부', 'PFAS Presence', 'BOOLEAN', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13036,
 'T1', '조건부 구속', 'REACH Annex XVII 79(PFHxA, (EU)2024/2462) 소비자 의류·신발 2026-10-10 적용 / POPs(EU)2019/1021 PFOA 0.025mg/kg', NULL, 'PUBLIC', 'PARSER', 'TEXTILE#75', TRUE, '⚠Boolean은 부적합. PFHxA 25ppb·관련물질 1000ppb 등 한계값 대비 ''측정치''여야 판정 가능. 범용 PFAS 제한은 2026-08 현재 미채택(ECHA SEAC 의견 단계)'),
('AZO_DYES_PRESENCE', 'TEXTILE', 'HAZARD', '아조염료 함유 여부', 'Azo Dyes Presence', 'BOOLEAN', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13037,
 'T1', '조건부 구속', 'REACH Annex XVII 43 — 방향족아민 30mg/kg 초과 방출 금지', '피부 접촉 제품', 'PUBLIC', 'PARSER', 'TEXTILE#76', TRUE, '⚠Boolean은 부적합. 30mg/kg 대비 측정치 필요'),
('PHTHALATES_PRESENCE', 'TEXTILE', 'HAZARD', '프탈레이트 함유 여부', 'Phthalates Presence', 'BOOLEAN', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13038,
 'T1', '조건부 구속', 'REACH Annex XVII 51 — DEHP·DBP·BBP·DIBP 합계 0.1% (가소화 소재 기준)', '가소화 소재(PVC 프린트·인조가죽 등) 포함 시', 'PUBLIC', 'PARSER', 'TEXTILE#77', TRUE, '⚠Boolean은 부적합. 0.1% 대비 측정치 필요'),
('FORMALDEHYDE_PRESENCE', 'TEXTILE', 'HAZARD', '폼알데하이드 함유 여부', 'Formaldehyde Presence', 'BOOLEAN', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13039,
 'T1', '조건부 구속', 'REACH Annex XVII 72 — 폼알데하이드 75mg/kg (2020-11-01 적용)', '피부 접촉 의류·신발·침구', 'PUBLIC', 'PARSER', 'TEXTILE#78', TRUE, '⚠Boolean은 부적합. 75mg/kg 대비 측정치 필요'),
('SVHC_4_SUBSTANCE_NAME', 'TEXTILE', 'HAZARD', 'SVHC 4 물질명', 'SVHC 4 Substance Name', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13040,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 4~5)', 'SVHC가 4종 이상 검출될 때', 'PUBLIC', 'PARSER', 'TEXTILE#195', FALSE, 'SVHC 10개 플랫 슬롯 대신 자식 테이블로 정규화 권장'),
('SVHC_4_CAS_NUMBER', 'TEXTILE', 'HAZARD', 'SVHC 4 CAS 번호', 'SVHC 4 CAS Number', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13041,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 4~5)', 'SVHC가 4종 이상 검출될 때', 'PUBLIC', 'PARSER', 'TEXTILE#196', FALSE, 'SVHC 10개 플랫 슬롯 대신 자식 테이블로 정규화 권장'),
('SVHC_4_CONCENTRATION_PCT', 'TEXTILE', 'HAZARD', 'SVHC 4 농도', 'SVHC 4 Concentration %', 'NUMBER', '%', FALSE, FALSE, 'RAW_SUPPLIER', 13042,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 4~5)', 'SVHC가 4종 이상 검출될 때', 'PUBLIC', 'PARSER', 'TEXTILE#197', FALSE, 'SVHC 10개 플랫 슬롯 대신 자식 테이블로 정규화 권장'),
('SVHC_4_LOCATION_IN_PRODUCT', 'TEXTILE', 'HAZARD', 'SVHC 4 함유 부위', 'SVHC 4 Location in Product', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13043,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 4~5)', 'SVHC가 4종 이상 검출될 때', 'PUBLIC', 'PARSER', 'TEXTILE#198', FALSE, 'SVHC 10개 플랫 슬롯 대신 자식 테이블로 정규화 권장'),
('SVHC_5_SUBSTANCE_NAME', 'TEXTILE', 'HAZARD', 'SVHC 5 물질명', 'SVHC 5 Substance Name', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13044,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 4~5)', 'SVHC가 4종 이상 검출될 때', 'PUBLIC', 'PARSER', 'TEXTILE#199', FALSE, 'SVHC 10개 플랫 슬롯 대신 자식 테이블로 정규화 권장'),
('SVHC_5_CAS_NUMBER', 'TEXTILE', 'HAZARD', 'SVHC 5 CAS 번호', 'SVHC 5 CAS Number', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13045,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 4~5)', 'SVHC가 4종 이상 검출될 때', 'PUBLIC', 'PARSER', 'TEXTILE#200', FALSE, 'SVHC 10개 플랫 슬롯 대신 자식 테이블로 정규화 권장'),
('SVHC_5_CONCENTRATION_PCT', 'TEXTILE', 'HAZARD', 'SVHC 5 농도', 'SVHC 5 Concentration %', 'NUMBER', '%', FALSE, FALSE, 'RAW_SUPPLIER', 13046,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 4~5)', 'SVHC가 4종 이상 검출될 때', 'PUBLIC', 'PARSER', 'TEXTILE#201', FALSE, 'SVHC 10개 플랫 슬롯 대신 자식 테이블로 정규화 권장'),
('SVHC_5_LOCATION_IN_PRODUCT', 'TEXTILE', 'HAZARD', 'SVHC 5 함유 부위', 'SVHC 5 Location in Product', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13047,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 4~5)', 'SVHC가 4종 이상 검출될 때', 'PUBLIC', 'PARSER', 'TEXTILE#202', FALSE, 'SVHC 10개 플랫 슬롯 대신 자식 테이블로 정규화 권장'),
('SVHC_6_SUBSTANCE_NAME', 'TEXTILE', 'HAZARD', 'SVHC 6 물질명', 'SVHC 6 Substance Name', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13048,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 6~10)', '동상', 'PUBLIC', 'PARSER', 'TEXTILE#252', FALSE, NULL),
('SVHC_6_CAS_NUMBER', 'TEXTILE', 'HAZARD', 'SVHC 6 CAS 번호', 'SVHC 6 CAS Number', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13049,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 6~10)', '동상', 'PUBLIC', 'PARSER', 'TEXTILE#253', FALSE, NULL),
('SVHC_6_CONCENTRATION_PCT', 'TEXTILE', 'HAZARD', 'SVHC 6 농도', 'SVHC 6 Concentration %', 'NUMBER', '%', FALSE, FALSE, 'RAW_SUPPLIER', 13050,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 6~10)', '동상', 'PUBLIC', 'PARSER', 'TEXTILE#254', FALSE, NULL),
('SVHC_7_SUBSTANCE_NAME', 'TEXTILE', 'HAZARD', 'SVHC 7 물질명', 'SVHC 7 Substance Name', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13051,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 6~10)', '동상', 'PUBLIC', 'PARSER', 'TEXTILE#255', FALSE, NULL),
('SVHC_7_CAS_NUMBER', 'TEXTILE', 'HAZARD', 'SVHC 7 CAS 번호', 'SVHC 7 CAS Number', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13052,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 6~10)', '동상', 'PUBLIC', 'PARSER', 'TEXTILE#256', FALSE, NULL),
('SVHC_7_CONCENTRATION_PCT', 'TEXTILE', 'HAZARD', 'SVHC 7 농도', 'SVHC 7 Concentration %', 'NUMBER', '%', FALSE, FALSE, 'RAW_SUPPLIER', 13053,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 6~10)', '동상', 'PUBLIC', 'PARSER', 'TEXTILE#257', FALSE, NULL),
('SVHC_8_SUBSTANCE_NAME', 'TEXTILE', 'HAZARD', 'SVHC 8 물질명', 'SVHC 8 Substance Name', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13054,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 6~10)', '동상', 'PUBLIC', 'PARSER', 'TEXTILE#258', FALSE, NULL),
('SVHC_8_CAS_NUMBER', 'TEXTILE', 'HAZARD', 'SVHC 8 CAS 번호', 'SVHC 8 CAS Number', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13055,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 6~10)', '동상', 'PUBLIC', 'PARSER', 'TEXTILE#259', FALSE, NULL),
('SVHC_8_CONCENTRATION_PCT', 'TEXTILE', 'HAZARD', 'SVHC 8 농도', 'SVHC 8 Concentration %', 'NUMBER', '%', FALSE, FALSE, 'RAW_SUPPLIER', 13056,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 6~10)', '동상', 'PUBLIC', 'PARSER', 'TEXTILE#260', FALSE, NULL),
('SVHC_9_SUBSTANCE_NAME', 'TEXTILE', 'HAZARD', 'SVHC 9 물질명', 'SVHC 9 Substance Name', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13057,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 6~10)', '동상', 'PUBLIC', 'PARSER', 'TEXTILE#261', FALSE, NULL),
('SVHC_9_CAS_NUMBER', 'TEXTILE', 'HAZARD', 'SVHC 9 CAS 번호', 'SVHC 9 CAS Number', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13058,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 6~10)', '동상', 'PUBLIC', 'PARSER', 'TEXTILE#262', FALSE, NULL),
('SVHC_9_CONCENTRATION_PCT', 'TEXTILE', 'HAZARD', 'SVHC 9 농도', 'SVHC 9 Concentration %', 'NUMBER', '%', FALSE, FALSE, 'RAW_SUPPLIER', 13059,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 6~10)', '동상', 'PUBLIC', 'PARSER', 'TEXTILE#263', FALSE, NULL),
('SVHC_10_SUBSTANCE_NAME', 'TEXTILE', 'HAZARD', 'SVHC 10 물질명', 'SVHC 10 Substance Name', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13060,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 6~10)', '동상', 'PUBLIC', 'PARSER', 'TEXTILE#264', FALSE, NULL),
('SVHC_10_CAS_NUMBER', 'TEXTILE', 'HAZARD', 'SVHC 10 CAS 번호', 'SVHC 10 CAS Number', 'STRING', NULL, FALSE, FALSE, 'RAW_SUPPLIER', 13061,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 6~10)', '동상', 'PUBLIC', 'PARSER', 'TEXTILE#265', FALSE, NULL),
('SVHC_10_CONCENTRATION_PCT', 'TEXTILE', 'HAZARD', 'SVHC 10 농도', 'SVHC 10 Concentration %', 'NUMBER', '%', FALSE, FALSE, 'RAW_SUPPLIER', 13062,
 'T1', '조건부 구속', 'REACH Art.33·SCIP(SVHC 6~10)', '동상', 'PUBLIC', 'PARSER', 'TEXTILE#266', FALSE, NULL),
('DISMANTLING_INFO', 'COMMON', 'CIRCULAR', '폐기·수거 안내 URL', 'End of Life Information URL', 'URL', NULL, TRUE, FALSE, 'RECYCLER', 14001,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 1(s) + Art.74(1)(a)~(f) 폐기물 예방·관리 정보 (데이터포인트 43)', NULL, 'PUBLIC', 'MANUAL', 'BATTERY#125', TRUE, NULL),
('DISMANTLING_MANUAL_URL', 'BATTERY', 'CIRCULAR', '해체 매뉴얼 URL', 'Dismantling Manual URL', 'URL', NULL, TRUE, FALSE, 'RECYCLER', 14002,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 2(c) 해체 정보 (데이터포인트 48)', NULL, 'RESTRICTED', 'MANUAL', 'BATTERY#126', TRUE, NULL),
('DISMANTLING_STEP_1_DESCRIPTION', 'BATTERY', 'CIRCULAR', '해체 절차 1단계', 'Dismantling Step 1 Description', 'STRING', NULL, FALSE, FALSE, 'RECYCLER', 14003,
 'T1', '조건부 구속', 'Annex XIII 2(c) 해체 순서', '해체 절차를 단계별로 기재할 때', 'RESTRICTED', 'MANUAL', 'BATTERY#127', TRUE, '4단계 플랫 컬럼 대신 절차 자식 테이블로 정규화 권장'),
('DISMANTLING_STEP_2_DESCRIPTION', 'BATTERY', 'CIRCULAR', '해체 절차 2단계', 'Dismantling Step 2 Description', 'STRING', NULL, FALSE, FALSE, 'RECYCLER', 14004,
 'T1', '조건부 구속', 'Annex XIII 2(c) 해체 순서', '해체 절차를 단계별로 기재할 때', 'RESTRICTED', 'MANUAL', 'BATTERY#128', TRUE, '4단계 플랫 컬럼 대신 절차 자식 테이블로 정규화 권장'),
('REQUIRED_TOOLS_FOR_DISMANTLING', 'BATTERY', 'CIRCULAR', '해체 필요 공구', 'Required Tools for Dismantling', 'STRING', NULL, TRUE, FALSE, 'RECYCLER', 14005,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 2(c) 필요 공구 (데이터포인트 48)', NULL, 'RESTRICTED', 'MANUAL', 'BATTERY#129', TRUE, NULL),
('SAFETY_MEASURES_DURING_DISMANTLING', 'BATTERY', 'CIRCULAR', '해체 시 안전조치', 'Safety Measures During Dismantling', 'STRING', NULL, TRUE, FALSE, 'RECYCLER', 14006,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 2(d) 안전 조치 (데이터포인트 49)', NULL, 'RESTRICTED', 'MANUAL', 'BATTERY#130', TRUE, NULL),
('RECOMMENDED_FIRE_EXTINGUISHING_AGENT', 'BATTERY', 'CIRCULAR', '권장 소화약제', 'Recommended Fire Extinguishing Agent', 'STRING', NULL, TRUE, FALSE, 'RECYCLER', 14007,
 'T0', '구속(여권 2027-02-18)', 'Annex VI Part A(9) 소화약제 (데이터포인트 14)', NULL, 'PUBLIC', 'MANUAL', 'BATTERY#131', TRUE, NULL),
('SUITABILITY_FOR_REPURPOSING', 'BATTERY', 'CIRCULAR', '재목적화 적합 여부', 'Suitability for Repurposing', 'BOOLEAN', NULL, FALSE, TRUE, NULL, 14008,
 'T1', '조건부 구속', 'Annex XIII 4(c) 배터리 상태 / 재목적 적합성', '2차 사용 판단을 여권에 남길 때', 'RESTRICTED', 'SYSTEM', 'BATTERY#132', TRUE, '대분류가 ''10. 순환성 전개''로 되어 있어 통일 필요'),
('DISMANTLING_STEP_3_DESCRIPTION', 'BATTERY', 'CIRCULAR', '해체 절차 3단계', 'Dismantling Step 3 Description', 'STRING', NULL, FALSE, FALSE, 'RECYCLER', 14009,
 'T1', '조건부 구속', 'Annex XIII 2(c) 해체 순서', '해체 절차를 단계별로 기재할 때', 'RESTRICTED', 'MANUAL', 'BATTERY#171', TRUE, '4단계 플랫 컬럼 대신 절차 자식 테이블로 정규화 권장'),
('DISMANTLING_STEP_4_DESCRIPTION', 'BATTERY', 'CIRCULAR', '해체 절차 4단계', 'Dismantling Step 4 Description', 'STRING', NULL, FALSE, FALSE, 'RECYCLER', 14010,
 'T1', '조건부 구속', 'Annex XIII 2(c) 해체 순서', '해체 절차를 단계별로 기재할 때', 'RESTRICTED', 'MANUAL', 'BATTERY#172', TRUE, '4단계 플랫 컬럼 대신 절차 자식 테이블로 정규화 권장'),
('DISCHARGE_PROCEDURE_BEFORE_RECYCLING', 'BATTERY', 'CIRCULAR', '재활용 전 방전 절차', 'Discharge Procedure Before Recycling', 'STRING', NULL, FALSE, FALSE, 'RECYCLER', 14011,
 'T1', '조건부 구속', 'Annex XIII 2(d) 안전 조치 — 방전 절차', NULL, 'RESTRICTED', 'MANUAL', 'BATTERY#173', TRUE, NULL),
('TOXIC_GAS_RELEASE_RISK_ASSESSMENT_URL', 'BATTERY', 'CIRCULAR', '유독가스 방출 위험평가서 URL', 'Toxic Gas Release Risk Assessment URL', 'URL', NULL, FALSE, FALSE, 'RECYCLER', 14012,
 'T1', '조건부 구속', 'Annex XIII 2(d) 안전 조치', '유독가스 위험이 있는 화학조성일 때', 'RESTRICTED', 'PARSER', 'BATTERY#209', FALSE, NULL),
('RECYCLABILITY_NOTE', 'COMMON', 'CIRCULAR', '소비자 분리배출 안내', 'Consumer Sorting Instructions', 'STRING', NULL, FALSE, FALSE, 'RECYCLER', 14013,
 'T1', '조건부 구속', '폐기물기본지침 Art.11(1) 섬유 분리배출(2025-01-01 시행)', 'EU 시장 출시 제품', 'PUBLIC', 'MANUAL', 'TEXTILE#173', TRUE, '분리배출 자체는 회원국 의무. 제품 표시 의무와는 구분 필요'),
('PRIMARY_PACKAGING_TYPE', 'TEXTILE', 'PACKAGING', '1차 포장 형태', 'Primary Packaging Type', 'CODE', NULL, FALSE, FALSE, 'MANUFACTURER', 15001,
 'T1', '조건부 구속', 'PPWR(EU)2025/40 (2026-08-12 적용) 포장 유형', '포장재를 함께 출시할 때', 'PUBLIC', 'MANUAL', 'TEXTILE#203', TRUE, NULL),
('PRIMARY_PACKAGING_MATERIAL_1', 'TEXTILE', 'PACKAGING', '1차 포장 재질', 'Primary Packaging Material 1', 'CODE', NULL, FALSE, FALSE, 'MANUFACTURER', 15002,
 'T1', '조건부 구속', 'PPWR Art.12 재질·분리배출 라벨(2028-08-12)', NULL, 'PUBLIC', 'MANUAL', 'TEXTILE#204', TRUE, NULL),
('PRIMARY_PACKAGING_RECYCLED_CONTENT_PCT', 'TEXTILE', 'PACKAGING', '1차 포장 재생원료 함량', 'Primary Packaging Recycled Content %', 'NUMBER', '%', FALSE, FALSE, 'MANUFACTURER', 15003,
 'T1', '조건부 구속', 'PPWR Art.7 플라스틱 포장 재생원료 함량 — 2030-01-01 적용', '플라스틱 포장재', 'PUBLIC', 'MANUAL', 'TEXTILE#205', FALSE, '현시점 미적용. 2030년 기준(비접촉 30% 등)'),
('PRIMARY_PACKAGING_RECYCLABILITY_PCT', 'TEXTILE', 'PACKAGING', '1차 포장 재활용성', 'Primary Packaging Recyclability %', 'NUMBER', '%', FALSE, FALSE, 'MANUFACTURER', 15004,
 'T1', '조건부 구속', 'PPWR Art.6 재활용 설계 등급 — 2030-01-01(C등급) / 2038(A·B)', NULL, 'PUBLIC', 'MANUAL', 'TEXTILE#206', FALSE, '현시점 미적용'),
('SECONDARY_PACKAGING_TYPE', 'TEXTILE', 'PACKAGING', '2차 포장 형태', 'Secondary Packaging Type', 'CODE', NULL, FALSE, FALSE, 'MANUFACTURER', 15005,
 'T1', '조건부 구속', 'PPWR(EU)2025/40 (2026-08-12 적용) 포장 유형', '포장재를 함께 출시할 때', 'PUBLIC', 'MANUAL', 'TEXTILE#207', TRUE, NULL),
('SECONDARY_PACKAGING_MATERIAL_1', 'TEXTILE', 'PACKAGING', '2차 포장 재질', 'Secondary Packaging Material 1', 'CODE', NULL, FALSE, FALSE, 'MANUFACTURER', 15006,
 'T1', '조건부 구속', 'PPWR Art.12 재질·분리배출 라벨(2028-08-12)', NULL, 'PUBLIC', 'MANUAL', 'TEXTILE#208', TRUE, NULL),
('SECONDARY_PACKAGING_RECYCLED_CONTENT_PCT', 'TEXTILE', 'PACKAGING', '2차 포장 재생원료 함량', 'Secondary Packaging Recycled Content %', 'NUMBER', '%', FALSE, FALSE, 'MANUFACTURER', 15007,
 'T1', '조건부 구속', 'PPWR Art.7 플라스틱 포장 재생원료 함량 — 2030-01-01 적용', '플라스틱 포장재', 'PUBLIC', 'MANUAL', 'TEXTILE#209', FALSE, '현시점 미적용. 2030년 기준(비접촉 30% 등)'),
('SECONDARY_PACKAGING_RECYCLABILITY_PCT', 'TEXTILE', 'PACKAGING', '2차 포장 재활용성', 'Secondary Packaging Recyclability %', 'NUMBER', '%', FALSE, FALSE, 'MANUFACTURER', 15008,
 'T1', '조건부 구속', 'PPWR Art.6 재활용 설계 등급 — 2030-01-01(C등급) / 2038(A·B)', NULL, 'PUBLIC', 'MANUAL', 'TEXTILE#210', FALSE, '현시점 미적용'),
('PACKAGING_HEAVY_METAL_TESTED', 'TEXTILE', 'PACKAGING', '포장재 중금속 시험 여부', 'Packaging Heavy Metal Tested', 'BOOLEAN', NULL, FALSE, FALSE, 'MANUFACTURER', 15009,
 'T1', '조건부 구속', 'PPWR(EU)2025/40 Art.5(2) — 실체적 한계값 규정', '포장재를 함께 출시할 때', 'PUBLIC', 'PARSER', 'TEXTILE#297', TRUE, '⚠Art.5(2)는 한계값이며 ''시험 여부'' 플래그 필드를 요구하지는 않음'),
('PACKAGING_LEAD_PB_CONCENTRATION_PPM', 'TEXTILE', 'PACKAGING', '포장재 납(Pb) 농도', 'Packaging Lead Pb Concentration ppm', 'NUMBER', 'ppm', FALSE, FALSE, 'MANUFACTURER', 15010,
 'T1', '조건부 구속', 'PPWR(EU)2025/40 Art.5(2) — Pb+Cd+Hg+Cr(VI) ''합계'' 100mg/kg (2026-08-12 적용)', '포장재를 함께 출시할 때', 'PUBLIC', 'PARSER', 'TEXTILE#298', TRUE, '⚠설계 오류: 한계값은 4종 합계인데 Hg·Cr(VI) 필드가 없고 합계 산출 필드도 없음. 현 구조로는 적합 판정 불가'),
('PACKAGING_CADMIUM_CD_CONCENTRATION_PPM', 'TEXTILE', 'PACKAGING', '포장재 카드뮴(Cd) 농도', 'Packaging Cadmium Cd Concentration ppm', 'NUMBER', 'ppm', FALSE, FALSE, 'MANUFACTURER', 15011,
 'T1', '조건부 구속', 'PPWR(EU)2025/40 Art.5(2) — 4종 합계 100mg/kg (2026-08-12 적용)', '포장재를 함께 출시할 때', 'PUBLIC', 'PARSER', 'TEXTILE#299', TRUE, '⚠개별 금속 농도 보고 의무는 없음. 합계 판정용 입력값으로만 의미 있음'),
('STATE_OF_HEALTH_SOH_PCT', 'BATTERY', 'BMS', '건전성(SoH)', 'State of Health SoH %', 'NUMBER', '%', FALSE, TRUE, NULL, 16001,
 'T0', '구속(여권 2027-02-18)', 'Art.14(1)~(2) + Annex VII (2024-08-18 시행) / Annex XIII 4(b) 건전성 (데이터포인트 61~62)', NULL, 'RESTRICTED', 'SYSTEM', 'BATTERY#115', TRUE, '⚠데이터포인트 61(SOCE)과 62(잔존용량)는 상호배타적이다. EV는 61만 기재하고 62는 ''기재하지 않음'', LMT는 반대다. 단일 SoH 필드로는 구현 불가 — 카테고리별 2개 필드로 분리할 것'),
('STATE_OF_CHARGE_SOC_PCT', 'BATTERY', 'BMS', '충전상태(SoC)', 'State of Charge SoC %', 'NUMBER', '%', FALSE, TRUE, NULL, 16002,
 'T1', '조건부 구속', 'Annex XIII 4(d) 충전상태 기록 (데이터포인트 71) — ''해당시''', '주기적 SoC 기록을 남길 때', 'RESTRICTED', 'SYSTEM', 'BATTERY#116', TRUE, '⚠SoC는 Annex VII 건전성 파라미터 목록에 없음'),
('TOTAL_ENERGY_THROUGHPUT_KWH', 'BATTERY', 'BMS', '누적 에너지 처리량', 'Total Energy Throughput kWh', 'NUMBER', 'kWh', FALSE, TRUE, NULL, 16003,
 'T1', '조건부 구속', 'Art.14(1) + Annex VII Part B (2024-08-18 시행) — BMS 데이터 의무', '정치형 ESS·LMT·EV 배터리', 'RESTRICTED', 'SYSTEM', 'BATTERY#117', TRUE, '⚠여권 데이터포인트가 아님. Art.14의 BMS 탑재·읽기전용 접근 의무이며 Art.77 여권 항목과는 별개 체계다'),
('TOTAL_CAPACITY_THROUGHPUT_AH', 'BATTERY', 'BMS', '누적 용량 처리량', 'Total Capacity Throughput Ah', 'NUMBER', 'Ah', FALSE, TRUE, NULL, 16004,
 'T1', '조건부 구속', 'Art.14(1) + Annex VII Part B (2024-08-18 시행) — BMS 데이터 의무', '정치형 ESS·LMT·EV 배터리', 'RESTRICTED', 'SYSTEM', 'BATTERY#118', TRUE, '⚠여권 데이터포인트가 아님. No.117 참조'),
('TIME_SPENT_IN_EXTREME_TEMPERATURE_MINUTES', 'BATTERY', 'BMS', '극한온도 노출 시간', 'Time Spent in Extreme Temperature Minutes', 'NUMBER', 'min', FALSE, TRUE, NULL, 16005,
 'T1', '조건부 구속', 'Annex XIII 4(d) 운영 환경조건(온도 포함) (데이터포인트 70)', NULL, 'RESTRICTED', 'SYSTEM', 'BATTERY#119', TRUE, NULL),
('NUMBER_OF_DEEP_DISCHARGE_EVENTS', 'BATTERY', 'BMS', '과방전 발생 횟수', 'Number of Deep Discharge Events', 'NUMBER', NULL, FALSE, TRUE, NULL, 16006,
 'T1', '조건부 구속', 'Annex XIII 4(d) 부정적 사건 (데이터포인트 69)', NULL, 'RESTRICTED', 'SYSTEM', 'BATTERY#120', TRUE, NULL),
('NUMBER_OF_OVERCHARGE_EVENTS', 'BATTERY', 'BMS', '과충전 발생 횟수', 'Number of Overcharge Events', 'NUMBER', NULL, FALSE, TRUE, NULL, 16007,
 'T1', '조건부 구속', 'Annex XIII 4(d) 부정적 사건 (데이터포인트 69)', NULL, 'RESTRICTED', 'SYSTEM', 'BATTERY#121', TRUE, NULL),
('DAYS_IN_OPERATION', 'BATTERY', 'BMS', '가동 일수', 'Days in Operation', 'NUMBER', NULL, FALSE, TRUE, NULL, 16008,
 'T1', '조건부 구속', 'Annex VII Part B 사용 개시일 기준 경과', NULL, 'RESTRICTED', 'SYSTEM', 'BATTERY#122', TRUE, NULL),
('REMAINING_CAPACITY_AH', 'BATTERY', 'BMS', '잔여 용량', 'Remaining Capacity Ah', 'NUMBER', 'Ah', FALSE, TRUE, NULL, 16009,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 4(b) 잔존 용량 (데이터포인트 62)', NULL, 'RESTRICTED', 'SYSTEM', 'BATTERY#123', TRUE, NULL),
('EVOLUTION_OF_INTERNAL_RESISTANCE_MOHM', 'BATTERY', 'BMS', '내부저항 변화량', 'Evolution of Internal Resistance mOhm', 'NUMBER', 'mΩ', FALSE, TRUE, NULL, 16010,
 'T0', '구속(여권 2027-02-18)', 'Annex XIII 4(b) 옴 저항 (데이터포인트 66)', NULL, 'RESTRICTED', 'SYSTEM', 'BATTERY#124', TRUE, '⚠명칭(''Evolution'')과 단위(mOhm)가 불일치. 저항 ''수준''이면 Annex XIII 4(b) 데이터포인트 66(옴 저항), 증가율(%)이면 4(a) 데이터포인트 56(내부저항 증가율)로 서로 다른 항목이다'),
('MAX_RECORDED_CELL_TEMP_C', 'BATTERY', 'BMS', '셀 최고 기록온도', 'Max Recorded Cell Temp C', 'NUMBER', '℃', FALSE, TRUE, NULL, 16011,
 'T1', '조건부 구속', 'Annex XIII 4(d) 운영 환경조건', '온도 이력을 남길 때', 'RESTRICTED', 'SYSTEM', 'BATTERY#165', FALSE, NULL),
('MIN_RECORDED_CELL_TEMP_C', 'BATTERY', 'BMS', '셀 최저 기록온도', 'Min Recorded Cell Temp C', 'NUMBER', '℃', FALSE, TRUE, NULL, 16012,
 'T1', '조건부 구속', 'Annex XIII 4(d) 운영 환경조건', '온도 이력을 남길 때', 'RESTRICTED', 'SYSTEM', 'BATTERY#166', FALSE, NULL),
('AVERAGE_OPERATING_TEMP_C', 'BATTERY', 'BMS', '평균 사용온도', 'Average Operating Temp C', 'NUMBER', '℃', FALSE, TRUE, NULL, 16013,
 'T1', '조건부 구속', 'Annex XIII 4(d) 운영 환경조건', '온도 이력을 남길 때', 'RESTRICTED', 'SYSTEM', 'BATTERY#167', FALSE, NULL),
('INTERNAL_SHORT_CIRCUIT_EVENTS', 'BATTERY', 'BMS', '내부 단락 발생 횟수', 'Internal Short Circuit Events', 'NUMBER', NULL, FALSE, TRUE, NULL, 16014,
 'T1', '조건부 구속', 'Annex XIII 4(d) 부정적 사건', NULL, 'RESTRICTED', 'SYSTEM', 'BATTERY#168', FALSE, NULL),
('THERMAL_RUNAWAY_WARNING_COUNT', 'BATTERY', 'BMS', '열폭주 경고 횟수', 'Thermal Runaway Warning Count', 'NUMBER', '회', FALSE, TRUE, NULL, 16015,
 'T1', '조건부 구속', 'Annex XIII 4(d) 부정적 사건', NULL, 'RESTRICTED', 'SYSTEM', 'BATTERY#169', FALSE, NULL),
('FAST_CHARGING_SESSION_COUNT', 'BATTERY', 'BMS', '급속충전 횟수', 'Fast Charging Session Count', 'NUMBER', '회', FALSE, TRUE, NULL, 16016,
 'T1', '조건부 구속', 'Annex XIII 4(d) 충방전 사이클 (데이터포인트 68)', NULL, 'RESTRICTED', 'SYSTEM', 'BATTERY#170', FALSE, NULL),
('TOTAL_OPERATING_HOURS', 'BATTERY', 'BMS', '누적 가동시간', 'Total Operating Hours', 'NUMBER', 'h', FALSE, TRUE, NULL, 16017,
 'T1', '조건부 구속', 'Annex VII Part B 운전 이력', NULL, 'RESTRICTED', 'SYSTEM', 'BATTERY#204', FALSE, NULL),
('TOTAL_ACTIVE_CHARGING_HOURS', 'BATTERY', 'BMS', '누적 충전시간', 'Total Active Charging Hours', 'NUMBER', 'h', FALSE, TRUE, NULL, 16018,
 'T1', '조건부 구속', 'Annex VII Part B 운전 이력', NULL, 'RESTRICTED', 'SYSTEM', 'BATTERY#205', FALSE, NULL),
('AC_IMPEDANCE_AT_1KHZ_MOHM', 'BATTERY', 'BMS', 'AC 임피던스(1kHz)', 'AC Impedance at 1kHz mOhm', 'NUMBER', 'mΩ', FALSE, TRUE, NULL, 16019,
 'T1', '조건부 구속', 'Annex VII Part A 전기화학 임피던스', '임피던스로 건전성을 산정할 때', 'RESTRICTED', 'SYSTEM', 'BATTERY#223', FALSE, NULL),
('SUPPLY_CHAIN_AUDIT_BODY_NAME', 'BATTERY', 'DUE_DILIGENCE', '공급망 실사기관명', 'Supply Chain Audit Body Name', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 17001,
 'T1', '조건부 구속', 'Art.51 인증기관 제3자 검증', '실사 대상 사업자(순매출 4천만 유로 이상)일 때', 'RESTRICTED', 'PARSER', 'BATTERY#22', FALSE, 'Omnibus IV(미채택)는 기준을 1억 5천만 유로로 상향 예정'),
('SUPPLY_CHAIN_AUDIT_DATE', 'BATTERY', 'DUE_DILIGENCE', '공급망 실사일', 'Supply Chain Audit Date', 'DATE', NULL, FALSE, FALSE, 'MANUFACTURER', 17002,
 'T1', '조건부 구속', 'Art.51 인증기관 제3자 검증', '실사 대상 사업자(순매출 4천만 유로 이상)일 때', 'RESTRICTED', 'PARSER', 'BATTERY#23', FALSE, 'Omnibus IV(미채택)는 기준을 1억 5천만 유로로 상향 예정'),
('OECD_DUE_DILIGENCE_GUIDANCE_ALIGNED', 'BATTERY', 'DUE_DILIGENCE', 'OECD 실사지침 부합 여부', 'OECD Due Diligence Guidance Aligned', 'BOOLEAN', NULL, FALSE, FALSE, 'MANUFACTURER', 17003,
 'T1', '조건부 구속', 'Annex X Part III — OECD 실사 지침 준거', '실사 정책 수립 시(회사 단위)', 'PUBLIC', 'MANUAL', 'BATTERY#216', FALSE, NULL),
('CONFLICT_AFFECTED_HIGH_RISK_AREAS_CAHRA', 'BATTERY', 'DUE_DILIGENCE', '분쟁·고위험지역(CAHRA) 해당 여부', 'Conflict Affected High Risk Areas CAHRA', 'BOOLEAN', NULL, FALSE, FALSE, 'MANUFACTURER', 17004,
 'T1', '조건부 구속', 'Annex X Part III / OECD CAHRA 개념', '분쟁·고위험지역 조달이 있을 때', 'RESTRICTED', 'MANUAL', 'BATTERY#227', FALSE, NULL),
('BATTERY_PACKAGING_RECYCLABLE_PCT', 'BATTERY', 'TRADE', '배터리 포장재 재활용 가능 비율', 'Battery Packaging Recyclable %', 'NUMBER', '%', FALSE, FALSE, 'MANUFACTURER', 18001,
 'T1', '조건부 구속', 'PPWR(EU)2025/40 — 포장재 대상', '배터리 포장재를 함께 출시할 때', 'PUBLIC', 'MANUAL', 'BATTERY#180', FALSE, NULL),
('ORIGIN_COUNTRY', 'COMMON', 'TRADE', '원산지 국가코드', 'Country of Origin Code', 'STRING', NULL, TRUE, FALSE, 'MANUFACTURER', 18002,
 'T0', '구속', 'UCC(EU)952/2013 Art.60 + Del.Reg.(EU)2015/2446 Annex B 신고 데이터요소', NULL, 'PUBLIC', 'MANUAL', 'STEEL#219', TRUE, NULL),
('CERTIFICATE_OF_ORIGIN_URL', 'STEEL', 'TRADE', '원산지증명서 URL', 'Certificate of Origin URL', 'URL', NULL, FALSE, FALSE, 'MANUFACTURER', 18003,
 'T1', '계약·표준', '특혜관세 적용 시 원산지증명', '특혜 적용을 받을 때', 'RESTRICTED', 'PARSER', 'STEEL#220', FALSE, NULL),
('IMPORTER_COMPANY_NAME', 'STEEL', 'TRADE', '수입자 상호', 'Importer Company Name', 'STRING', NULL, TRUE, FALSE, 'MANUFACTURER', 18004,
 'T0', '구속', 'CBAM Art.5(5)(a) 인가 CBAM 신고인 정보', NULL, 'RESTRICTED', 'MANUAL', 'STEEL#223', TRUE, NULL),
('IMPORTER_EORI_NUMBER', 'STEEL', 'TRADE', '수입자 EORI 번호', 'Importer EORI Number', 'STRING', NULL, TRUE, FALSE, 'MANUFACTURER', 18005,
 'T0', '구속', 'CBAM Art.5(5)(b) EORI / 등록부 Impl.Reg.(EU)2024/3210(2025/2550 개정)', NULL, 'RESTRICTED', 'MANUAL', 'STEEL#224', TRUE, NULL),
('TEST_REPORT_UN38_3_TRANSPORTATION', 'BATTERY', 'DOCUMENT', 'UN 38.3 운송시험 보고서', 'Test Report UN38 3 Transportation', 'URL', NULL, FALSE, FALSE, 'MANUFACTURER', 19001,
 'T1', '조건부 구속', 'UN 38.3 — 운송 위험물 규정(ADR·IMDG·IATA / Dir.2008/68/EC)', 'EU 역내외 운송 시', 'PUBLIC', 'PARSER', 'BATTERY#135', TRUE, '⚠배터리규정 요건이 아님. ''배터리규정 준수'' 버킷과 분리할 것'),
('MANUFACTURER_WARRANTY_PERIOD_MONTHS', 'BATTERY', 'DOCUMENT', '제조사 보증기간', 'Manufacturer Warranty Period Months', 'NUMBER', '개월', FALSE, FALSE, 'MANUFACTURER', 19002,
 'T1', '조건부 구속', 'Annex XIII 1(m) 달력수명 상업적 보증기간 (데이터포인트 35) — ''해당시''', '보증을 제공하는 경우', 'PUBLIC', 'MANUAL', 'BATTERY#249', TRUE, NULL),
('NATIONAL_COMPETENT_AUTHORITY_REGISTRY_ID', 'BATTERY', 'DOCUMENT', '회원국 관할당국 등록번호', 'National Competent Authority Registry ID', 'STRING', NULL, FALSE, FALSE, 'MANUFACTURER', 19003,
 'T1', '조건부 구속', 'Art.55·Art.79 회원국 관할당국 등록(생산자책임)', 'EU 시장 출시 시', 'RESTRICTED', 'MANUAL', 'BATTERY#297', FALSE, NULL),
('MILL_TEST_CERTIFICATE_TYPE', 'STEEL', 'DOCUMENT', '성적서 종류(EN 10204)', 'Mill Test Certificate Type', 'CODE', NULL, FALSE, FALSE, 'MANUFACTURER', 19004,
 'T1', '조건부 구속', 'EN 10204 3.1/3.2 성적서(계약·제품표준) / ESPR Annex III (e) 준수문서', NULL, 'PUBLIC', 'PARSER', 'STEEL#199', TRUE, 'EU 법령이 직접 요구하는 것은 아니나 ESPR Annex III ''준수문서''의 실질 담체'),
('MILL_TEST_CERTIFICATE_DOCUMENT_URL', 'STEEL', 'DOCUMENT', '제강 성적서 URL', 'Mill Test Certificate Document URL', 'URL', NULL, FALSE, FALSE, 'MANUFACTURER', 19005,
 'T1', '조건부 구속', 'EN 10204 3.1/3.2 성적서(계약·제품표준) / ESPR Annex III (e) 준수문서', NULL, 'PUBLIC', 'PARSER', 'STEEL#200', TRUE, 'EU 법령이 직접 요구하는 것은 아니나 ESPR Annex III ''준수문서''의 실질 담체'),
('DECLARATION_OF_CONFORMITY_URL', 'TEXTILE', 'DOCUMENT', '적합성선언서 URL', 'Declaration of Conformity URL', 'URL', NULL, FALSE, FALSE, 'MANUFACTURER', 19006,
 'T1', '조건부 구속', 'PPE 규정(EU)2016/425 Art.15 EU 적합성선언', '해당 제품이 PPE일 때', 'PUBLIC', 'PARSER', 'TEXTILE#175', TRUE, '⚠일반 의류에는 EU 적합성선언 의무 없음. 원본 ''필수''는 과잉'),
('DATA_SCHEMA_VERSION', 'BATTERY', 'SYSTEM', '데이터 스키마 버전', 'Data Schema Version', 'STRING', NULL, FALSE, TRUE, NULL, 20001,
 'T1', '조건부 구속', 'Art.77(8) 여권 기술설계 위임법(미채택) / 운영 필요', NULL, 'PUBLIC', 'SYSTEM', 'BATTERY#181', TRUE, NULL),
('LAST_MODIFIED_TIMESTAMP', 'BATTERY', 'SYSTEM', '최종 수정 시각', 'Last Modified Timestamp', 'DATETIME', NULL, FALSE, TRUE, NULL, 20002,
 'T1', '조건부 구속', 'Art.77 여권 데이터의 최신성 유지', NULL, 'PUBLIC', 'SYSTEM', 'BATTERY#182', TRUE, NULL),
('RESPONSIBLE_DATA_AUDITOR_ID', 'BATTERY', 'SYSTEM', '데이터 감사 책임자 ID', 'Responsible Data Auditor ID', 'STRING', NULL, FALSE, TRUE, NULL, 20003,
 'T1', '조건부 구속', 'Art.77(9) 시행법(미채택) — 접근권한·수정권한', NULL, 'RESTRICTED', 'SYSTEM', 'BATTERY#183', TRUE, NULL),
('API_ACCESS_SECURITY_TOKEN_ID', 'BATTERY', 'SYSTEM', 'API 접근 토큰 ID', 'API Access Security Token ID', 'STRING', NULL, FALSE, TRUE, NULL, 20004,
 'T1', '조건부 구속', 'Art.77(9) 시행법 대기 / 보안 설계', 'API 접근 통제를 구현할 때', 'RESTRICTED', 'SYSTEM', 'BATTERY#237', FALSE, NULL),
('DATA_INTEGRITY_CRYPTOGRAPHIC_SIGNATURE', 'BATTERY', 'SYSTEM', '데이터 무결성 전자서명', 'Data Integrity Cryptographic Signature', 'STRING', NULL, FALSE, TRUE, NULL, 20005,
 'T1', '조건부 구속', 'Art.77 데이터 진정성 / 자사 아키텍처', '블록체인 원장 채택 시', 'PUBLIC', 'SYSTEM', 'BATTERY#250', TRUE, '⚠본 프로젝트의 핵심 차별화 요소. MVP 필수 승격 권장'),
('LAST_DATA_UPDATE_TIMESTAMP', 'COMMON', 'SYSTEM', '최종 데이터 갱신 시각', 'Last Data Update Timestamp', 'DATETIME', NULL, FALSE, TRUE, NULL, 20006,
 'T1', '위임법 대기', 'ESPR Art.9(1) 데이터의 정확·완전·최신성', 'ESPR 제품군 위임법 채택 시(철강 지시적 2026년, 2026-08 현재 미채택)', 'PUBLIC', 'SYSTEM', 'STEEL#225,TEXTILE#246', TRUE, '⚠Art.9(1)은 데이터 품질 의무이며 ''타임스탬프 필드''를 명시적으로 요구하지는 않음'),
('DATA_UPDATE_RESPONSIBLE_PERSON_ID', 'COMMON', 'SYSTEM', '데이터 갱신 책임자 ID', 'Data Update Responsible Person ID', 'STRING', NULL, FALSE, TRUE, NULL, 20007,
 'T1', '위임법 대기', 'ESPR Art.11(1)(f) 입력·수정 ''권한''의 제한', 'ESPR 제품군 위임법 채택 시(철강 지시적 2026년, 2026-08 현재 미채택)', 'RESTRICTED', 'SYSTEM', 'STEEL#226,TEXTILE#247', TRUE, '⚠수정 권한을 제한하라는 규정이며 ''담당자 ID 저장''을 요구하지는 않음'),
('PASSPORT_PRIMARY_LANGUAGE', 'COMMON', 'SYSTEM', '여권 기본 언어', 'Passport Primary Language', 'STRING', NULL, FALSE, TRUE, NULL, 20008,
 'T1', '위임법 대기', 'ESPR Art.9(2)(e)·Art.11(1)(b) 접근성', '다국어 제공 정책 채택 시', 'PUBLIC', 'SYSTEM', 'STEEL#227,TEXTILE#244', FALSE, NULL),
('FINAL_APPROVAL_OFFICER', 'COMMON', 'SYSTEM', '품질책임자 검증자명', 'Data Verified by QA Manager Name', 'STRING', NULL, FALSE, TRUE, NULL, 20009,
 'T1', '위임법 대기', 'ESPR Art.11(1)(g) 데이터 진정성·무결성', '승인 절차를 여권에 남길 때', 'RESTRICTED', 'SYSTEM', 'STEEL#305,TEXTILE#300', TRUE, NULL),
('FINAL_APPROVAL_AT', 'COMMON', 'SYSTEM', '품질 승인 시각', 'QA Approval Timestamp', 'DATETIME', NULL, FALSE, TRUE, NULL, 20010,
 'T1', '위임법 대기', 'ESPR Art.11(1)(g) 데이터 진정성·무결성', '승인 절차를 여권에 남길 때', 'RESTRICTED', 'SYSTEM', 'STEEL#306,TEXTILE#301', TRUE, NULL),
('LEDGER_TX_HASH', 'COMMON', 'SYSTEM', '원장 트랜잭션 해시', 'Immutable Ledger Transaction Hash', 'STRING', NULL, FALSE, TRUE, NULL, 20011,
 'T1', '위임법 대기', 'ESPR Art.11(1)(g) 무결성 보장 수단', '블록체인 원장 채택 시(자사 아키텍처)', 'PUBLIC', 'SYSTEM', 'STEEL#307,TEXTILE#243', TRUE, '⚠원본 ''선택''이나 본 프로젝트의 핵심 차별화 요소. MVP 필수로 승격 권장'),
('FINAL_PASSPORT_AUTHORIZATION_SIGNATURE', 'BATTERY', 'APPROVAL', '최종 여권 승인 서명', 'Final Passport Authorization Signature', 'STRING', NULL, FALSE, TRUE, NULL, 21001,
 'T1', '조건부 구속', 'Art.77 데이터 진정성·책임 소재', '승인 절차를 여권에 남길 때', 'RESTRICTED', 'SYSTEM', 'BATTERY#300', TRUE, NULL),
('FINAL_AUTHORIZATION_TIMESTAMP', 'BATTERY', 'APPROVAL', '최종 승인 시각', 'Final Authorization Timestamp', 'DATETIME', NULL, FALSE, TRUE, NULL, 21002,
 'T1', '조건부 구속', 'Art.77 데이터 진정성·책임 소재', '승인 절차를 여권에 남길 때', 'RESTRICTED', 'SYSTEM', 'BATTERY#301', TRUE, NULL)
ON CONFLICT (field_code) DO UPDATE SET
    domain           = EXCLUDED.domain,
    section          = EXCLUDED.section,
    label_ko         = EXCLUDED.label_ko,
    label_en         = EXCLUDED.label_en,
    data_type        = EXCLUDED.data_type,
    unit             = COALESCE(EXCLUDED.unit, requirement_field.unit),
    is_required      = EXCLUDED.is_required,
    responsible_role = EXCLUDED.responsible_role,
    sort_order       = EXCLUDED.sort_order,
    tier             = EXCLUDED.tier,
    binding_strength = EXCLUDED.binding_strength,
    legal_basis      = EXCLUDED.legal_basis,
    t1_condition     = EXCLUDED.t1_condition,
    disclosure_scope = EXCLUDED.disclosure_scope,
    data_source      = EXCLUDED.data_source,
    spec_ref         = EXCLUDED.spec_ref,
    is_mvp           = EXCLUDED.is_mvp,
    review_note      = EXCLUDED.review_note;
-- is_auto / field_kind / storage_target 는 일부러 덮어쓰지 않는다. 기존 행에서 이 셋은
-- 화면 배치(입력폼 vs 문서슬롯 vs 자재구성)를 결정하는데, 분류표에는 그 구분이 없어서
-- 덮어쓰면 CHEM_COMPOSITION 같은 자재구성 필드가 일반 입력칸으로 튀어나온다.

-- ── 기존 80개 행 sort_order 를 새 밴드로 재배치 ────────────────────────
UPDATE requirement_field rf
   SET sort_order = s.band * 1000 + 500 + (rf.sort_order % 100)
  FROM (VALUES
        ('IDENTIFIER', 1),
        ('OPERATOR', 2),
        ('SPEC', 3),
        ('COMPOSITION', 4),
        ('MATERIAL', 5),
        ('CHEMISTRY', 6),
        ('MECHANICAL', 7),
        ('PERFORMANCE', 8),
        ('PROCESS', 9),
        ('RESOURCE', 10),
        ('CRM', 11),
        ('CARBON', 12),
        ('HAZARD', 13),
        ('CIRCULAR', 14),
        ('PACKAGING', 15),
        ('BMS', 16),
        ('DUE_DILIGENCE', 17),
        ('TRADE', 18),
        ('DOCUMENT', 19),
        ('SYSTEM', 20),
        ('APPROVAL', 21)
       ) AS s(section, band)
 WHERE rf.section = s.section
   AND rf.sort_order < 1000;

-- ── 새 필드의 티어별 노출 규칙 ────────────────────────────────────────
-- disclosure_scope 에서 기계적으로 만든다. 지금까지는 V4/V16/V17 이 필드코드를 손으로
-- 나열해서 심었는데(V13 은 아예 빠뜨렸다), 300개를 손으로 적을 수는 없다.
--   PUBLIC       : 1/2/3 전부 FULL
--   RESTRICTED   : 티어1 HIDDEN, 티어2 MASKED, 티어3 FULL
--   TRADE_SECRET : 티어1·2 HIDDEN, 티어3 MASKED (값 자체는 티어3에도 안 준다)
INSERT INTO field_visibility (field_code, tier_level, visibility)
SELECT rf.field_code, t.lvl,
       CASE rf.disclosure_scope
         WHEN 'PUBLIC'       THEN 'FULL'
         WHEN 'RESTRICTED'   THEN CASE t.lvl WHEN 1 THEN 'HIDDEN' WHEN 2 THEN 'MASKED' ELSE 'FULL' END
         ELSE                     CASE t.lvl WHEN 3 THEN 'MASKED' ELSE 'HIDDEN' END
       END
  FROM requirement_field rf
 CROSS JOIN (VALUES (1),(2),(3)) AS t(lvl)
    ON CONFLICT (field_code, tier_level) DO UPDATE
   SET visibility = EXCLUDED.visibility;

-- ── 섹션 라벨을 code_master 로 ────────────────────────────────────────
-- 섹션이 8개에서 21개로 늘었다. FE(dppVals.js)는 섹션 코드->한글 이름 매핑을 파일 안에
-- 하드코딩한 8칸짜리 map으로 갖고 있어서, 새 섹션은 전부 'HAZARD' 같은 영문 코드가 그대로
-- 화면에 뜬다. 라벨을 여기 넣고 BE가 폼 응답에 실어 보내면 그 map이 필요 없어진다.
INSERT INTO code_master (code_group, code, name_ko, name_en, sort_order) VALUES
('FIELD_SECTION','IDENTIFIER','식별자','Identifiers',1000),
('FIELD_SECTION','OPERATOR','경제운영자·제조시설','Economic Operator / Facility',2000),
('FIELD_SECTION','SPEC','제품 사양','Product Specification',3000),
('FIELD_SECTION','COMPOSITION','셀 화학·구성','Cell Chemistry / Composition',4000),
('FIELD_SECTION','MATERIAL','재질 구성(BOM)','Material Composition (BOM)',5000),
('FIELD_SECTION','CHEMISTRY','화학 성분','Chemical Composition',6000),
('FIELD_SECTION','MECHANICAL','기계적 물성','Mechanical Properties',7000),
('FIELD_SECTION','PERFORMANCE','성능·내구성','Performance and Durability',8000),
('FIELD_SECTION','PROCESS','공정 정보','Process Information',9000),
('FIELD_SECTION','RESOURCE','자원·에너지','Resources and Energy',10000),
('FIELD_SECTION','CRM','핵심 원자재(CRM)','Critical Raw Materials',11000),
('FIELD_SECTION','CARBON','탄소·CBAM','Carbon and CBAM',12000),
('FIELD_SECTION','HAZARD','유해물질·SVHC','Hazardous Substances / SVHC',13000),
('FIELD_SECTION','CIRCULAR','순환성·해체','Circularity and Dismantling',14000),
('FIELD_SECTION','PACKAGING','포장재','Packaging',15000),
('FIELD_SECTION','BMS','동적 데이터(BMS)','Dynamic Data (BMS)',16000),
('FIELD_SECTION','DUE_DILIGENCE','공급망 실사','Supply Chain Due Diligence',17000),
('FIELD_SECTION','TRADE','원산지·통관','Origin and Customs',18000),
('FIELD_SECTION','DOCUMENT','증빙·문서','Evidence and Documents',19000),
('FIELD_SECTION','SYSTEM','시스템 관리','System Management',20000),
('FIELD_SECTION','APPROVAL','최종 승인','Final Approval',21000)
ON CONFLICT (code_group, code) DO UPDATE
   SET name_ko = EXCLUDED.name_ko, name_en = EXCLUDED.name_en, sort_order = EXCLUDED.sort_order;
