# -*- coding: utf-8 -*-
"""문서에서 뽑아 DPP 필드로 바로 들어가는 항목표 (data_source='PARSER').

출처는 requirement_field 시드(V21__seed_requirement_t0_t1.sql)이고, 그 시드의 출처는
'DPP_데이터항목_분류.xlsx'의 T0·T1 항목이다. 여기 있는 192개는 그중 데이터 출처가 '파서'로
판정된 것만 추린 것 - 수기 입력(MANUAL)이나 서버 생성(SYSTEM) 항목은 들어있지 않다.

■ 왜 라벨 사전 방식인가
extractor.py 위쪽 주석에 적혀 있듯, 이 프로젝트는 예전에 "완전 범용 라벨/값 페어링"을
한 번 시도했다가 표·줄바꿈이 섞인 문서에서 그럴듯한 오답을 뽑아내는 문제로 폐기했다.
그 교훈을 지키기 위해 여기서도 자유 휴리스틱은 쓰지 않는다. 대신
  (1) 라벨 어휘를 이 표로 닫아두고 (아는 라벨이 아니면 아예 안 본다)
  (2) 한 줄이 '라벨 <구분자> 값' 꼴로 딱 떨어질 때만 인정하고
  (3) 뽑은 값이 그 필드의 data_type으로 파싱되지 않으면 버린다
세 조건을 전부 통과한 것만 돌려준다. 못 뽑으면 조용히 빠지는 게 정상이고, 틀린 값을
채우는 것보다 비는 게 낫다.

■ 이 표를 고치는 방법
이 파일은 손으로 고치지 말고 requirement_field 시드를 고친 뒤 다시 생성한다. 시드와
어긋나면 파서가 존재하지 않는 field_code를 채우려 들고, BE가 FK 위반으로 죽는다.
"""

SPEC_FIELDS = [
    dict(code='BATTERY_NET_WEIGHT_KG', domain='BATTERY', section='IDENTIFIER', label_ko='총 중량', label_en='Total Weight kg', data_type='NUMBER', unit='kg'),
    dict(code='EU_DECLARATION_OF_CONFORMITY_ID', domain='BATTERY', section='IDENTIFIER', label_ko='EU 적합성선언서 번호', label_en='EU Declaration of Conformity ID', data_type='STRING', unit=None),
    dict(code='BATTERY_CHEMISTRY', domain='BATTERY', section='COMPOSITION', label_ko='셀 화학 계열', label_en='Cell Chemistry Class', data_type='CODE', unit=None),
    dict(code='NUMBER_OF_CELLS', domain='BATTERY', section='COMPOSITION', label_ko='셀 수', label_en='Number of Cells', data_type='NUMBER', unit=None),
    dict(code='NUMBER_OF_MODULES', domain='BATTERY', section='COMPOSITION', label_ko='모듈 수', label_en='Number of Modules', data_type='NUMBER', unit=None),
    dict(code='CATHODE_ACTIVE_MATERIAL_FAMILY', domain='BATTERY', section='COMPOSITION', label_ko='양극 활물질 계열', label_en='Cathode Active Material Family', data_type='STRING', unit=None),
    dict(code='CATHODE_COMPOSITION_DETAILS', domain='BATTERY', section='COMPOSITION', label_ko='양극 조성 상세', label_en='Cathode Composition Details', data_type='STRING', unit=None),
    dict(code='CATHODE_BINDER_MATERIAL', domain='BATTERY', section='COMPOSITION', label_ko='양극 바인더', label_en='Cathode Binder Material', data_type='STRING', unit=None),
    dict(code='CATHODE_CONDUCTIVE_ADDITIVE', domain='BATTERY', section='COMPOSITION', label_ko='양극 도전재', label_en='Cathode Conductive Additive', data_type='STRING', unit=None),
    dict(code='ANODE_ACTIVE_MATERIAL_FAMILY', domain='BATTERY', section='COMPOSITION', label_ko='음극 활물질 계열', label_en='Anode Active Material Family', data_type='STRING', unit=None),
    dict(code='ANODE_COMPOSITION_DETAILS', domain='BATTERY', section='COMPOSITION', label_ko='음극 조성 상세', label_en='Anode Composition Details', data_type='STRING', unit=None),
    dict(code='ANODE_BINDER_MATERIAL', domain='BATTERY', section='COMPOSITION', label_ko='음극 바인더', label_en='Anode Binder Material', data_type='STRING', unit=None),
    dict(code='ANODE_CONDUCTIVE_ADDITIVE', domain='BATTERY', section='COMPOSITION', label_ko='음극 도전재', label_en='Anode Conductive Additive', data_type='STRING', unit=None),
    dict(code='ELECTROLYTE_TYPE', domain='BATTERY', section='COMPOSITION', label_ko='전해질 유형', label_en='Electrolyte Type', data_type='CODE', unit=None),
    dict(code='ELECTROLYTE_SOLVENT', domain='BATTERY', section='COMPOSITION', label_ko='전해질 용매', label_en='Electrolyte Solvent', data_type='STRING', unit=None),
    dict(code='ELECTROLYTE_SALT', domain='BATTERY', section='COMPOSITION', label_ko='전해질 염', label_en='Electrolyte Salt', data_type='STRING', unit=None),
    dict(code='SEPARATOR_MATERIAL', domain='BATTERY', section='COMPOSITION', label_ko='분리막 재질', label_en='Separator Material', data_type='STRING', unit=None),
    dict(code='PACK_ENCLOSURE_PROTECTION_RATING', domain='BATTERY', section='COMPOSITION', label_ko='팩 외함 보호등급(IP)', label_en='Pack Enclosure Protection Rating', data_type='STRING', unit=None),
    dict(code='RATED_CAPACITY_AH', domain='BATTERY', section='PERFORMANCE', label_ko='정격 용량', label_en='Rated Capacity Ah', data_type='NUMBER', unit='Ah'),
    dict(code='RATED_CAPACITY_MEASUREMENT_METHOD', domain='BATTERY', section='PERFORMANCE', label_ko='정격 용량 측정방법', label_en='Rated Capacity Measurement Method', data_type='STRING', unit=None),
    dict(code='NOMINAL_ENERGY_WH', domain='BATTERY', section='PERFORMANCE', label_ko='공칭 에너지', label_en='Nominal Energy Wh', data_type='NUMBER', unit='Wh'),
    dict(code='NOMINAL_VOLTAGE_V', domain='BATTERY', section='PERFORMANCE', label_ko='공칭 전압', label_en='Nominal Voltage V', data_type='NUMBER', unit='V'),
    dict(code='MAXIMUM_VOLTAGE_V', domain='BATTERY', section='PERFORMANCE', label_ko='최대 전압', label_en='Maximum Voltage V', data_type='NUMBER', unit='V'),
    dict(code='MINIMUM_VOLTAGE_V', domain='BATTERY', section='PERFORMANCE', label_ko='최소 전압', label_en='Minimum Voltage V', data_type='NUMBER', unit='V'),
    dict(code='MAXIMUM_ALLOWED_DISCHARGE_POWER_W', domain='BATTERY', section='PERFORMANCE', label_ko='허용 최대 방전출력', label_en='Maximum Allowed Discharge Power W', data_type='NUMBER', unit='W'),
    dict(code='MAXIMUM_ALLOWED_CHARGE_POWER_W', domain='BATTERY', section='PERFORMANCE', label_ko='허용 최대 충전출력', label_en='Maximum Allowed Charge Power W', data_type='NUMBER', unit='W'),
    dict(code='OPERATING_TEMPERATURE_MAX_C', domain='BATTERY', section='PERFORMANCE', label_ko='사용 온도 상한', label_en='Operating Temperature Max C', data_type='NUMBER', unit='℃'),
    dict(code='OPERATING_TEMPERATURE_MIN_C', domain='BATTERY', section='PERFORMANCE', label_ko='사용 온도 하한', label_en='Operating Temperature Min C', data_type='NUMBER', unit='℃'),
    dict(code='STORAGE_TEMPERATURE_MAX_C', domain='BATTERY', section='PERFORMANCE', label_ko='보관 온도 상한', label_en='Storage Temperature Max C', data_type='NUMBER', unit='℃'),
    dict(code='STORAGE_TEMPERATURE_MIN_C', domain='BATTERY', section='PERFORMANCE', label_ko='보관 온도 하한', label_en='Storage Temperature Min C', data_type='NUMBER', unit='℃'),
    dict(code='INITIAL_INTERNAL_RESISTANCE_MOHM', domain='BATTERY', section='PERFORMANCE', label_ko='초기 내부저항', label_en='Initial Internal Resistance mOhm', data_type='NUMBER', unit='mΩ'),
    dict(code='INTERNAL_RESISTANCE_MEASUREMENT_METHOD', domain='BATTERY', section='PERFORMANCE', label_ko='내부저항 측정방법', label_en='Internal Resistance Measurement Method', data_type='STRING', unit=None),
    dict(code='EXPECTED_CYCLE_LIFE_COUNT', domain='BATTERY', section='PERFORMANCE', label_ko='기대 사이클 수명', label_en='Expected Cycle Life Count', data_type='NUMBER', unit='회'),
    dict(code='REFERENCE_TEST_CONDITIONS_FOR_CYCLE_LIFE', domain='BATTERY', section='PERFORMANCE', label_ko='사이클 수명 기준 시험조건', label_en='Reference Test Conditions for Cycle Life', data_type='STRING', unit=None),
    dict(code='CAPACITY_FADE_THRESHOLD_PCT', domain='BATTERY', section='PERFORMANCE', label_ko='용량 감소 임계값', label_en='Capacity Fade Threshold %', data_type='NUMBER', unit='%'),
    dict(code='MAXIMUM_CONTINUOUS_DISCHARGE_CURRENT_A', domain='BATTERY', section='PERFORMANCE', label_ko='최대 연속 방전전류', label_en='Maximum Continuous Discharge Current A', data_type='NUMBER', unit='A'),
    dict(code='MAXIMUM_PULSE_DISCHARGE_CURRENT_A', domain='BATTERY', section='PERFORMANCE', label_ko='최대 펄스 방전전류', label_en='Maximum Pulse Discharge Current A', data_type='NUMBER', unit='A'),
    dict(code='RECOMMENDED_CUT_OFF_VOLTAGE_V', domain='BATTERY', section='PERFORMANCE', label_ko='권장 차단 전압', label_en='Recommended Cut off Voltage V', data_type='NUMBER', unit='V'),
    dict(code='ENERGY_EFFICIENCY_ROUND_TRIP_PCT', domain='BATTERY', section='PERFORMANCE', label_ko='왕복 에너지효율', label_en='Energy Efficiency Round Trip %', data_type='NUMBER', unit='%'),
    dict(code='CALENDAR_LIFE_EXPECTANCY_YEARS', domain='BATTERY', section='PERFORMANCE', label_ko='달력수명 기대치', label_en='Calendar Life Expectancy Years', data_type='NUMBER', unit='년'),
    dict(code='VIBRATION_TEST_STANDARD_UN38_3_PASSED', domain='BATTERY', section='PERFORMANCE', label_ko='UN 38.3 진동시험 합격 여부', label_en='Vibration Test Standard UN38 3 Passed', data_type='BOOLEAN', unit=None),
    dict(code='MECHANICAL_SHOCK_TEST_PASSED', domain='BATTERY', section='PERFORMANCE', label_ko='기계적 충격시험 합격 여부', label_en='Mechanical Shock Test Passed', data_type='BOOLEAN', unit=None),
    dict(code='CRM_COBALT_WEIGHT_KG', domain='BATTERY', section='CRM', label_ko='CRM 코발트 함유중량', label_en='CRM Cobalt Weight kg', data_type='NUMBER', unit='kg'),
    dict(code='CRM_COBALT_PERCENTAGE', domain='BATTERY', section='CRM', label_ko='CRM 코발트 함유비율', label_en='CRM Cobalt Percentage', data_type='NUMBER', unit=None),
    dict(code='CRM_LITHIUM_WEIGHT_KG', domain='BATTERY', section='CRM', label_ko='CRM 리튬 함유중량', label_en='CRM Lithium Weight kg', data_type='NUMBER', unit='kg'),
    dict(code='CRM_LITHIUM_PERCENTAGE', domain='BATTERY', section='CRM', label_ko='CRM 리튬 함유비율', label_en='CRM Lithium Percentage', data_type='NUMBER', unit=None),
    dict(code='CRM_NICKEL_WEIGHT_KG', domain='BATTERY', section='CRM', label_ko='CRM 니켈 함유중량', label_en='CRM Nickel Weight kg', data_type='NUMBER', unit='kg'),
    dict(code='CRM_NICKEL_PERCENTAGE', domain='BATTERY', section='CRM', label_ko='CRM 니켈 함유비율', label_en='CRM Nickel Percentage', data_type='NUMBER', unit=None),
    dict(code='CRM_MANGANESE_WEIGHT_KG', domain='BATTERY', section='CRM', label_ko='CRM 망간 함유중량', label_en='CRM Manganese Weight kg', data_type='NUMBER', unit='kg'),
    dict(code='CRM_MANGANESE_PERCENTAGE', domain='BATTERY', section='CRM', label_ko='CRM 망간 함유비율', label_en='CRM Manganese Percentage', data_type='NUMBER', unit=None),
    dict(code='CRM_NATURAL_GRAPHITE_WEIGHT_KG', domain='BATTERY', section='CRM', label_ko='CRM 천연흑연 함유중량', label_en='CRM Natural Graphite Weight kg', data_type='NUMBER', unit='kg'),
    dict(code='CRM_NATURAL_GRAPHITE_PERCENTAGE', domain='BATTERY', section='CRM', label_ko='CRM 천연흑연 함유비율', label_en='CRM Natural Graphite Percentage', data_type='NUMBER', unit=None),
    dict(code='CRM_LEAD_WEIGHT_KG', domain='BATTERY', section='CRM', label_ko='CRM 납 함유중량', label_en='CRM Lead Weight kg', data_type='NUMBER', unit='kg'),
    dict(code='CRM_LEAD_PERCENTAGE', domain='BATTERY', section='CRM', label_ko='CRM 납 함유비율', label_en='CRM Lead Percentage', data_type='NUMBER', unit=None),
    dict(code='CRM_COPPER_WEIGHT_KG', domain='BATTERY', section='CRM', label_ko='CRM 구리 함유중량', label_en='CRM Copper Weight kg', data_type='NUMBER', unit='kg'),
    dict(code='CRM_ALUMINUM_WEIGHT_KG', domain='BATTERY', section='CRM', label_ko='CRM 알루미늄 함유중량', label_en='CRM Aluminum Weight kg', data_type='NUMBER', unit='kg'),
    dict(code='CRM_IRON_WEIGHT_KG', domain='BATTERY', section='CRM', label_ko='CRM 철 함유중량', label_en='CRM Iron Weight kg', data_type='NUMBER', unit='kg'),
    dict(code='CRM_PHOSPHORUS_WEIGHT_KG', domain='BATTERY', section='CRM', label_ko='CRM 인 함유중량', label_en='CRM Phosphorus Weight kg', data_type='NUMBER', unit='kg'),
    dict(code='CRM_TANTALUM_WEIGHT_KG', domain='BATTERY', section='CRM', label_ko='CRM 탄탈럼 함유중량', label_en='CRM Tantalum Weight kg', data_type='NUMBER', unit='kg'),
    dict(code='CRM_SILICON_WEIGHT_KG', domain='BATTERY', section='CRM', label_ko='CRM 실리콘 함유중량', label_en='CRM Silicon Weight kg', data_type='NUMBER', unit='kg'),
    dict(code='SVHC_PRESENT', domain='BATTERY', section='HAZARD', label_ko='SVHC 함유 여부', label_en='SVHC Present', data_type='BOOLEAN', unit=None),
    dict(code='SVHC_SUBSTANCE_NAME_1', domain='BATTERY', section='HAZARD', label_ko='SVHC 1 물질명', label_en='SVHC Substance Name 1', data_type='STRING', unit=None),
    dict(code='SVHC_SUBSTANCE_CAS_NUMBER_1', domain='BATTERY', section='HAZARD', label_ko='SVHC 1 CAS 번호', label_en='SVHC Substance CAS Number 1', data_type='STRING', unit=None),
    dict(code='SVHC_CONCENTRATION_PCT_1', domain='BATTERY', section='HAZARD', label_ko='SVHC 1 농도', label_en='SVHC Concentration % 1', data_type='NUMBER', unit=None),
    dict(code='SVHC_LOCATION_IN_BATTERY_1', domain='BATTERY', section='HAZARD', label_ko='SVHC 1 함유 부위', label_en='SVHC Location in Battery 1', data_type='STRING', unit=None),
    dict(code='SVHC_SUBSTANCE_NAME_2', domain='BATTERY', section='HAZARD', label_ko='SVHC 2 물질명', label_en='SVHC Substance Name 2', data_type='STRING', unit=None),
    dict(code='SVHC_SUBSTANCE_CAS_NUMBER_2', domain='BATTERY', section='HAZARD', label_ko='SVHC 2 CAS 번호', label_en='SVHC Substance CAS Number 2', data_type='STRING', unit=None),
    dict(code='SVHC_CONCENTRATION_PCT_2', domain='BATTERY', section='HAZARD', label_ko='SVHC 2 농도', label_en='SVHC Concentration % 2', data_type='NUMBER', unit=None),
    dict(code='SVHC_LOCATION_IN_BATTERY_2', domain='BATTERY', section='HAZARD', label_ko='SVHC 2 함유 부위', label_en='SVHC Location in Battery 2', data_type='STRING', unit=None),
    dict(code='SVHC_SUBSTANCE_NAME_3', domain='BATTERY', section='HAZARD', label_ko='SVHC 3 물질명', label_en='SVHC Substance Name 3', data_type='STRING', unit=None),
    dict(code='SVHC_SUBSTANCE_CAS_NUMBER_3', domain='BATTERY', section='HAZARD', label_ko='SVHC 3 CAS 번호', label_en='SVHC Substance CAS Number 3', data_type='STRING', unit=None),
    dict(code='SVHC_CONCENTRATION_PCT_3', domain='BATTERY', section='HAZARD', label_ko='SVHC 3 농도', label_en='SVHC Concentration % 3', data_type='NUMBER', unit=None),
    dict(code='TOXIC_GAS_RELEASE_RISK_ASSESSMENT_URL', domain='BATTERY', section='CIRCULAR', label_ko='유독가스 방출 위험평가서 URL', label_en='Toxic Gas Release Risk Assessment URL', data_type='URL', unit=None),
    dict(code='SUPPLY_CHAIN_AUDIT_BODY_NAME', domain='BATTERY', section='DUE_DILIGENCE', label_ko='공급망 실사기관명', label_en='Supply Chain Audit Body Name', data_type='STRING', unit=None),
    dict(code='SUPPLY_CHAIN_AUDIT_DATE', domain='BATTERY', section='DUE_DILIGENCE', label_ko='공급망 실사일', label_en='Supply Chain Audit Date', data_type='DATE', unit=None),
    dict(code='TEST_REPORT_UN38_3_TRANSPORTATION', domain='BATTERY', section='DOCUMENT', label_ko='UN 38.3 운송시험 보고서', label_en='Test Report UN38 3 Transportation', data_type='URL', unit=None),
    dict(code='PRODUCTION_DATE', domain='COMMON', section='IDENTIFIER', label_ko='제조일', label_en='Date of Manufacture', data_type='DATE', unit=None),
    dict(code='PCF_VALUE', domain='COMMON', section='CARBON', label_ko='단위당 내재배출량', label_en='Specific Embedded Emissions tCO2e per t', data_type='NUMBER', unit=None),
    dict(code='HEAT_NO', domain='STEEL', section='IDENTIFIER', label_ko='용강 배치/히트 번호', label_en='Steel Batch or Heat Number', data_type='STRING', unit=None),
    dict(code='LOT_NO', domain='STEEL', section='IDENTIFIER', label_ko='코일·후판·강관 ID', label_en='Coil Plate or Pipe ID', data_type='STRING', unit=None),
    dict(code='STEEL_GRADE', domain='STEEL', section='IDENTIFIER', label_ko='강종명', label_en='Steel Grade Name', data_type='STRING', unit=None),
    dict(code='STEEL_STANDARD', domain='STEEL', section='IDENTIFIER', label_ko='적용 표준', label_en='Applied Standard 1', data_type='STRING', unit=None),
    dict(code='NET_WEIGHT_T', domain='STEEL', section='IDENTIFIER', label_ko='제품 순중량', label_en='Product Net Weight kg', data_type='NUMBER', unit='t'),
    dict(code='CHEMICAL_ANALYSIS_TYPE', domain='STEEL', section='CHEMISTRY', label_ko='화학분석 구분(레이들/제품)', label_en='Chemical Analysis Type', data_type='CODE', unit=None),
    dict(code='CHEMICAL_TEST_STANDARD', domain='STEEL', section='CHEMISTRY', label_ko='화학시험 표준', label_en='Chemical Test Standard', data_type='STRING', unit=None),
    dict(code='CHEM_MN_ACTUAL_PCT', domain='STEEL', section='CHEMISTRY', label_ko='화학성분 Mn 실측', label_en='Chem Mn Actual %', data_type='NUMBER', unit='%'),
    dict(code='CHEM_CR_ACTUAL_PCT', domain='STEEL', section='CHEMISTRY', label_ko='화학성분 Cr 실측', label_en='Chem Cr Actual %', data_type='NUMBER', unit='%'),
    dict(code='CHEM_NI_ACTUAL_PCT', domain='STEEL', section='CHEMISTRY', label_ko='화학성분 Ni 실측', label_en='Chem Ni Actual %', data_type='NUMBER', unit='%'),
    dict(code='CHEM_MO_ACTUAL_PCT', domain='STEEL', section='CHEMISTRY', label_ko='화학성분 Mo 실측', label_en='Chem Mo Actual %', data_type='NUMBER', unit='%'),
    dict(code='CHEM_ZR_ACTUAL_PCT', domain='STEEL', section='CHEMISTRY', label_ko='화학성분 Zr 실측', label_en='Chem Zr Actual %', data_type='NUMBER', unit='%'),
    dict(code='CHEM_CE_ACTUAL_PCT', domain='STEEL', section='CHEMISTRY', label_ko='화학성분 Ce 실측', label_en='Chem Ce Actual %', data_type='NUMBER', unit='%'),
    dict(code='CHEM_W_ACTUAL_PCT', domain='STEEL', section='CHEMISTRY', label_ko='화학성분 W 실측', label_en='Chem W Actual %', data_type='NUMBER', unit='%'),
    dict(code='CHEM_CO_ACTUAL_PCT', domain='STEEL', section='CHEMISTRY', label_ko='화학성분 Co 실측', label_en='Chem Co Actual %', data_type='NUMBER', unit='%'),
    dict(code='CHEM_SB_ACTUAL_PCT', domain='STEEL', section='CHEMISTRY', label_ko='화학성분 Sb 실측', label_en='Chem Sb Actual %', data_type='NUMBER', unit='%'),
    dict(code='CHEM_ZN_ACTUAL_PCT', domain='STEEL', section='CHEMISTRY', label_ko='화학성분 Zn 실측', label_en='Chem Zn Actual %', data_type='NUMBER', unit='%'),
    dict(code='TENSILE_TEST_STANDARD', domain='STEEL', section='MECHANICAL', label_ko='인장시험 표준', label_en='Tensile Test Standard', data_type='STRING', unit=None),
    dict(code='TEST_DIRECTION', domain='STEEL', section='MECHANICAL', label_ko='시편 채취 방향', label_en='Test Direction', data_type='CODE', unit=None),
    dict(code='YIELD_STRENGTH_ACTUAL_MPA', domain='STEEL', section='MECHANICAL', label_ko='항복강도 실측', label_en='Yield Strength Actual MPa', data_type='NUMBER', unit='MPa'),
    dict(code='YIELD_STRENGTH_MIN_MPA', domain='STEEL', section='MECHANICAL', label_ko='항복강도 규격 하한', label_en='Yield Strength Min MPa', data_type='NUMBER', unit='MPa'),
    dict(code='TENSILE_STRENGTH_ACTUAL_MPA', domain='STEEL', section='MECHANICAL', label_ko='인장강도 실측', label_en='Tensile Strength Actual MPa', data_type='NUMBER', unit='MPa'),
    dict(code='TENSILE_STRENGTH_MIN_MPA', domain='STEEL', section='MECHANICAL', label_ko='인장강도 규격 하한', label_en='Tensile Strength Min MPa', data_type='NUMBER', unit='MPa'),
    dict(code='TENSILE_STRENGTH_MAX_MPA', domain='STEEL', section='MECHANICAL', label_ko='인장강도 규격 상한', label_en='Tensile Strength Max MPa', data_type='NUMBER', unit='MPa'),
    dict(code='ELONGATION_ACTUAL_PCT', domain='STEEL', section='MECHANICAL', label_ko='연신율 실측', label_en='Elongation Actual %', data_type='NUMBER', unit='%'),
    dict(code='ELONGATION_MIN_PCT', domain='STEEL', section='MECHANICAL', label_ko='연신율 규격 하한', label_en='Elongation Min %', data_type='NUMBER', unit='%'),
    dict(code='GAUGE_LENGTH_MM', domain='STEEL', section='MECHANICAL', label_ko='연신율 측정 표점거리', label_en='Gauge Length mm', data_type='NUMBER', unit='mm'),
    dict(code='SURFACE_TREATMENT_TYPE', domain='STEEL', section='PROCESS', label_ko='표면처리 방식', label_en='Surface Treatment Type', data_type='CODE', unit=None),
    dict(code='CBAM_DIRECT_EMISSIONS_TCO2E_PER_T', domain='STEEL', section='CARBON', label_ko='CBAM 직접배출량', label_en='CBAM Direct Emissions tCO2e per t', data_type='NUMBER', unit='tCO2e/t'),
    dict(code='CBAM_INDIRECT_EMISSIONS_TCO2E_PER_T', domain='STEEL', section='CARBON', label_ko='CBAM 간접배출량', label_en='CBAM Indirect Emissions tCO2e per t', data_type='NUMBER', unit='tCO2e/t'),
    dict(code='CBAM_ACTUAL_DATA_USED_RATIO_PCT', domain='STEEL', section='CARBON', label_ko='CBAM 실측데이터 사용비율', label_en='CBAM Actual Data Used Ratio %', data_type='NUMBER', unit='%'),
    dict(code='CBAM_DEFAULT_VALUE_USED_RATIO_PCT', domain='STEEL', section='CARBON', label_ko='CBAM 기본값 사용비율', label_en='CBAM Default Value Used Ratio %', data_type='NUMBER', unit='%'),
    dict(code='ELECTRICITY_EMISSION_FACTOR_TCO2E_PER_MWH', domain='STEEL', section='CARBON', label_ko='전력 배출계수', label_en='Electricity Emission Factor tCO2e per MWh', data_type='NUMBER', unit='tCO2e/MWh'),
    dict(code='ELECTRICITY_SOURCE', domain='STEEL', section='CARBON', label_ko='전력 조달 방식', label_en='Electricity Source', data_type='CODE', unit=None),
    dict(code='PRECURSOR_1_NAME', domain='STEEL', section='CARBON', label_ko='전구체 1 명칭', label_en='Precursor 1 Name', data_type='STRING', unit=None),
    dict(code='PRECURSOR_1_QUANTITY_T_PER_T', domain='STEEL', section='CARBON', label_ko='전구체 1 투입량', label_en='Precursor 1 Quantity t per t', data_type='NUMBER', unit='t/t'),
    dict(code='PRECURSOR_1_SPECIFIC_EMISSIONS', domain='STEEL', section='CARBON', label_ko='전구체 1 단위 배출량', label_en='Precursor 1 Specific Emissions', data_type='NUMBER', unit=None),
    dict(code='PRECURSOR_2_NAME', domain='STEEL', section='CARBON', label_ko='전구체 2 명칭', label_en='Precursor 2 Name', data_type='STRING', unit=None),
    dict(code='PRECURSOR_2_QUANTITY_T_PER_T', domain='STEEL', section='CARBON', label_ko='전구체 2 투입량', label_en='Precursor 2 Quantity t per t', data_type='NUMBER', unit='t/t'),
    dict(code='PRECURSOR_2_SPECIFIC_EMISSIONS', domain='STEEL', section='CARBON', label_ko='전구체 2 단위 배출량', label_en='Precursor 2 Specific Emissions', data_type='NUMBER', unit=None),
    dict(code='PRECURSOR_3_NAME', domain='STEEL', section='CARBON', label_ko='전구체 3 명칭', label_en='Precursor 3 Name', data_type='STRING', unit=None),
    dict(code='PRECURSOR_3_QUANTITY_T_PER_T', domain='STEEL', section='CARBON', label_ko='전구체 3 투입량', label_en='Precursor 3 Quantity t per t', data_type='NUMBER', unit='t/t'),
    dict(code='PRECURSOR_3_SPECIFIC_EMISSIONS', domain='STEEL', section='CARBON', label_ko='전구체 3 단위 배출량', label_en='Precursor 3 Specific Emissions', data_type='NUMBER', unit=None),
    dict(code='CBAM_EMISSIONS_VERIFIED_BY_THIRD_PARTY', domain='STEEL', section='CARBON', label_ko='CBAM 배출량 제3자 검증 여부', label_en='CBAM Emissions Verified By Third Party', data_type='BOOLEAN', unit=None),
    dict(code='CBAM_VERIFICATION_BODY_NAME', domain='STEEL', section='CARBON', label_ko='CBAM 검증기관명', label_en='CBAM Verification Body Name', data_type='STRING', unit=None),
    dict(code='CBAM_VERIFICATION_REPORT_URL', domain='STEEL', section='CARBON', label_ko='CBAM 검증보고서 URL', label_en='CBAM Verification Report URL', data_type='URL', unit=None),
    dict(code='SVHC_PRESENCE_IN_COATING', domain='STEEL', section='HAZARD', label_ko='도금·도장층 SVHC 함유 여부', label_en='SVHC Presence in Coating', data_type='BOOLEAN', unit=None),
    dict(code='SVHC_SUBSTANCE_NAME', domain='STEEL', section='HAZARD', label_ko='SVHC 물질명', label_en='SVHC Substance Name', data_type='STRING', unit=None),
    dict(code='SVHC_CAS_NUMBER', domain='STEEL', section='HAZARD', label_ko='SVHC CAS 번호', label_en='SVHC CAS Number', data_type='STRING', unit=None),
    dict(code='SVHC_CONCENTRATION_PCT', domain='STEEL', section='HAZARD', label_ko='SVHC 농도', label_en='SVHC Concentration %', data_type='NUMBER', unit='%'),
    dict(code='ROHS_COMPLIANT_STATUS', domain='STEEL', section='HAZARD', label_ko='RoHS 적합 여부', label_en='RoHS Compliant Status', data_type='BOOLEAN', unit=None),
    dict(code='HEXAVALENT_CHROMIUM_CR6_PRESENCE', domain='STEEL', section='HAZARD', label_ko='6가크롬 함유 여부', label_en='Hexavalent Chromium Cr6 Presence', data_type='BOOLEAN', unit=None),
    dict(code='CERTIFICATE_OF_ORIGIN_URL', domain='STEEL', section='TRADE', label_ko='원산지증명서 URL', label_en='Certificate of Origin URL', data_type='URL', unit=None),
    dict(code='MILL_TEST_CERTIFICATE_TYPE', domain='STEEL', section='DOCUMENT', label_ko='성적서 종류(EN 10204)', label_en='Mill Test Certificate Type', data_type='CODE', unit=None),
    dict(code='MILL_TEST_CERTIFICATE_DOCUMENT_URL', domain='STEEL', section='DOCUMENT', label_ko='제강 성적서 URL', label_en='Mill Test Certificate Document URL', data_type='URL', unit=None),
    dict(code='SHELL_COMPONENT_NAME', domain='TEXTILE', section='MATERIAL', label_ko='겉감 부품명', label_en='Shell Component Name', data_type='STRING', unit=None),
    dict(code='SHELL_MATERIAL_1_TYPE', domain='TEXTILE', section='MATERIAL', label_ko='겉감 소재 1 종류', label_en='Shell Material 1 Type', data_type='CODE', unit=None),
    dict(code='SHELL_MATERIAL_1_PERCENTAGE_PCT', domain='TEXTILE', section='MATERIAL', label_ko='겉감 소재 1 혼용률', label_en='Shell Material 1 Percentage %', data_type='NUMBER', unit='%'),
    dict(code='SHELL_MATERIAL_2_TYPE', domain='TEXTILE', section='MATERIAL', label_ko='겉감 소재 2 종류', label_en='Shell Material 2 Type', data_type='CODE', unit=None),
    dict(code='SHELL_MATERIAL_2_PERCENTAGE_PCT', domain='TEXTILE', section='MATERIAL', label_ko='겉감 소재 2 혼용률', label_en='Shell Material 2 Percentage %', data_type='NUMBER', unit='%'),
    dict(code='SHELL_MATERIAL_3_TYPE', domain='TEXTILE', section='MATERIAL', label_ko='겉감 소재 3 종류', label_en='Shell Material 3 Type', data_type='CODE', unit=None),
    dict(code='SHELL_MATERIAL_3_PERCENTAGE_PCT', domain='TEXTILE', section='MATERIAL', label_ko='겉감 소재 3 혼용률', label_en='Shell Material 3 Percentage %', data_type='NUMBER', unit='%'),
    dict(code='LINING_COMPONENT_NAME', domain='TEXTILE', section='MATERIAL', label_ko='안감 부품명', label_en='Lining Component Name', data_type='STRING', unit=None),
    dict(code='LINING_MATERIAL_1_TYPE', domain='TEXTILE', section='MATERIAL', label_ko='안감 소재 1 종류', label_en='Lining Material 1 Type', data_type='CODE', unit=None),
    dict(code='LINING_MATERIAL_1_PERCENTAGE_PCT', domain='TEXTILE', section='MATERIAL', label_ko='안감 소재 1 혼용률', label_en='Lining Material 1 Percentage %', data_type='NUMBER', unit='%'),
    dict(code='LINING_MATERIAL_2_TYPE', domain='TEXTILE', section='MATERIAL', label_ko='안감 소재 2 종류', label_en='Lining Material 2 Type', data_type='CODE', unit=None),
    dict(code='LINING_MATERIAL_2_PERCENTAGE_PCT', domain='TEXTILE', section='MATERIAL', label_ko='안감 소재 2 혼용률', label_en='Lining Material 2 Percentage %', data_type='NUMBER', unit='%'),
    dict(code='PADDING_COMPONENT_NAME', domain='TEXTILE', section='MATERIAL', label_ko='충전재 부품명', label_en='Padding Component Name', data_type='STRING', unit=None),
    dict(code='PADDING_MATERIAL_TYPE', domain='TEXTILE', section='MATERIAL', label_ko='충전재 종류', label_en='Padding Material Type', data_type='CODE', unit=None),
    dict(code='PADDING_PERCENTAGE_PCT', domain='TEXTILE', section='MATERIAL', label_ko='충전재 혼용률', label_en='Padding Percentage %', data_type='NUMBER', unit='%'),
    dict(code='PADDING_ANIMAL_WELFARE_CERT', domain='TEXTILE', section='MATERIAL', label_ko='충전재 동물복지 인증', label_en='Padding Animal Welfare Cert', data_type='STRING', unit=None),
    dict(code='SVHC_1_SUBSTANCE_NAME', domain='TEXTILE', section='HAZARD', label_ko='SVHC 1 물질명', label_en='SVHC 1 Substance Name', data_type='STRING', unit=None),
    dict(code='SVHC_1_CAS_NUMBER', domain='TEXTILE', section='HAZARD', label_ko='SVHC 1 CAS 번호', label_en='SVHC 1 CAS Number', data_type='STRING', unit=None),
    dict(code='SVHC_1_CONCENTRATION_PCT', domain='TEXTILE', section='HAZARD', label_ko='SVHC 1 농도', label_en='SVHC 1 Concentration %', data_type='NUMBER', unit='%'),
    dict(code='SVHC_1_LOCATION_IN_PRODUCT', domain='TEXTILE', section='HAZARD', label_ko='SVHC 1 함유 부위', label_en='SVHC 1 Location in Product', data_type='STRING', unit=None),
    dict(code='SVHC_1_TEST_REPORT_URL', domain='TEXTILE', section='HAZARD', label_ko='SVHC 1 시험성적서 URL', label_en='SVHC 1 Test Report URL', data_type='URL', unit=None),
    dict(code='SVHC_2_SUBSTANCE_NAME', domain='TEXTILE', section='HAZARD', label_ko='SVHC 2 물질명', label_en='SVHC 2 Substance Name', data_type='STRING', unit=None),
    dict(code='SVHC_2_CAS_NUMBER', domain='TEXTILE', section='HAZARD', label_ko='SVHC 2 CAS 번호', label_en='SVHC 2 CAS Number', data_type='STRING', unit=None),
    dict(code='SVHC_2_CONCENTRATION_PCT', domain='TEXTILE', section='HAZARD', label_ko='SVHC 2 농도', label_en='SVHC 2 Concentration %', data_type='NUMBER', unit='%'),
    dict(code='SVHC_2_LOCATION_IN_PRODUCT', domain='TEXTILE', section='HAZARD', label_ko='SVHC 2 함유 부위', label_en='SVHC 2 Location in Product', data_type='STRING', unit=None),
    dict(code='SVHC_2_TEST_REPORT_URL', domain='TEXTILE', section='HAZARD', label_ko='SVHC 2 시험성적서 URL', label_en='SVHC 2 Test Report URL', data_type='URL', unit=None),
    dict(code='SVHC_3_SUBSTANCE_NAME', domain='TEXTILE', section='HAZARD', label_ko='SVHC 3 물질명', label_en='SVHC 3 Substance Name', data_type='STRING', unit=None),
    dict(code='SVHC_3_CAS_NUMBER', domain='TEXTILE', section='HAZARD', label_ko='SVHC 3 CAS 번호', label_en='SVHC 3 CAS Number', data_type='STRING', unit=None),
    dict(code='PFAS_PRESENCE', domain='TEXTILE', section='HAZARD', label_ko='PFAS 함유 여부', label_en='PFAS Presence', data_type='BOOLEAN', unit=None),
    dict(code='AZO_DYES_PRESENCE', domain='TEXTILE', section='HAZARD', label_ko='아조염료 함유 여부', label_en='Azo Dyes Presence', data_type='BOOLEAN', unit=None),
    dict(code='PHTHALATES_PRESENCE', domain='TEXTILE', section='HAZARD', label_ko='프탈레이트 함유 여부', label_en='Phthalates Presence', data_type='BOOLEAN', unit=None),
    dict(code='FORMALDEHYDE_PRESENCE', domain='TEXTILE', section='HAZARD', label_ko='폼알데하이드 함유 여부', label_en='Formaldehyde Presence', data_type='BOOLEAN', unit=None),
    dict(code='SVHC_4_SUBSTANCE_NAME', domain='TEXTILE', section='HAZARD', label_ko='SVHC 4 물질명', label_en='SVHC 4 Substance Name', data_type='STRING', unit=None),
    dict(code='SVHC_4_CAS_NUMBER', domain='TEXTILE', section='HAZARD', label_ko='SVHC 4 CAS 번호', label_en='SVHC 4 CAS Number', data_type='STRING', unit=None),
    dict(code='SVHC_4_CONCENTRATION_PCT', domain='TEXTILE', section='HAZARD', label_ko='SVHC 4 농도', label_en='SVHC 4 Concentration %', data_type='NUMBER', unit='%'),
    dict(code='SVHC_4_LOCATION_IN_PRODUCT', domain='TEXTILE', section='HAZARD', label_ko='SVHC 4 함유 부위', label_en='SVHC 4 Location in Product', data_type='STRING', unit=None),
    dict(code='SVHC_5_SUBSTANCE_NAME', domain='TEXTILE', section='HAZARD', label_ko='SVHC 5 물질명', label_en='SVHC 5 Substance Name', data_type='STRING', unit=None),
    dict(code='SVHC_5_CAS_NUMBER', domain='TEXTILE', section='HAZARD', label_ko='SVHC 5 CAS 번호', label_en='SVHC 5 CAS Number', data_type='STRING', unit=None),
    dict(code='SVHC_5_CONCENTRATION_PCT', domain='TEXTILE', section='HAZARD', label_ko='SVHC 5 농도', label_en='SVHC 5 Concentration %', data_type='NUMBER', unit='%'),
    dict(code='SVHC_5_LOCATION_IN_PRODUCT', domain='TEXTILE', section='HAZARD', label_ko='SVHC 5 함유 부위', label_en='SVHC 5 Location in Product', data_type='STRING', unit=None),
    dict(code='SVHC_6_SUBSTANCE_NAME', domain='TEXTILE', section='HAZARD', label_ko='SVHC 6 물질명', label_en='SVHC 6 Substance Name', data_type='STRING', unit=None),
    dict(code='SVHC_6_CAS_NUMBER', domain='TEXTILE', section='HAZARD', label_ko='SVHC 6 CAS 번호', label_en='SVHC 6 CAS Number', data_type='STRING', unit=None),
    dict(code='SVHC_6_CONCENTRATION_PCT', domain='TEXTILE', section='HAZARD', label_ko='SVHC 6 농도', label_en='SVHC 6 Concentration %', data_type='NUMBER', unit='%'),
    dict(code='SVHC_7_SUBSTANCE_NAME', domain='TEXTILE', section='HAZARD', label_ko='SVHC 7 물질명', label_en='SVHC 7 Substance Name', data_type='STRING', unit=None),
    dict(code='SVHC_7_CAS_NUMBER', domain='TEXTILE', section='HAZARD', label_ko='SVHC 7 CAS 번호', label_en='SVHC 7 CAS Number', data_type='STRING', unit=None),
    dict(code='SVHC_7_CONCENTRATION_PCT', domain='TEXTILE', section='HAZARD', label_ko='SVHC 7 농도', label_en='SVHC 7 Concentration %', data_type='NUMBER', unit='%'),
    dict(code='SVHC_8_SUBSTANCE_NAME', domain='TEXTILE', section='HAZARD', label_ko='SVHC 8 물질명', label_en='SVHC 8 Substance Name', data_type='STRING', unit=None),
    dict(code='SVHC_8_CAS_NUMBER', domain='TEXTILE', section='HAZARD', label_ko='SVHC 8 CAS 번호', label_en='SVHC 8 CAS Number', data_type='STRING', unit=None),
    dict(code='SVHC_8_CONCENTRATION_PCT', domain='TEXTILE', section='HAZARD', label_ko='SVHC 8 농도', label_en='SVHC 8 Concentration %', data_type='NUMBER', unit='%'),
    dict(code='SVHC_9_SUBSTANCE_NAME', domain='TEXTILE', section='HAZARD', label_ko='SVHC 9 물질명', label_en='SVHC 9 Substance Name', data_type='STRING', unit=None),
    dict(code='SVHC_9_CAS_NUMBER', domain='TEXTILE', section='HAZARD', label_ko='SVHC 9 CAS 번호', label_en='SVHC 9 CAS Number', data_type='STRING', unit=None),
    dict(code='SVHC_9_CONCENTRATION_PCT', domain='TEXTILE', section='HAZARD', label_ko='SVHC 9 농도', label_en='SVHC 9 Concentration %', data_type='NUMBER', unit='%'),
    dict(code='SVHC_10_SUBSTANCE_NAME', domain='TEXTILE', section='HAZARD', label_ko='SVHC 10 물질명', label_en='SVHC 10 Substance Name', data_type='STRING', unit=None),
    dict(code='SVHC_10_CAS_NUMBER', domain='TEXTILE', section='HAZARD', label_ko='SVHC 10 CAS 번호', label_en='SVHC 10 CAS Number', data_type='STRING', unit=None),
    dict(code='SVHC_10_CONCENTRATION_PCT', domain='TEXTILE', section='HAZARD', label_ko='SVHC 10 농도', label_en='SVHC 10 Concentration %', data_type='NUMBER', unit='%'),
    dict(code='PACKAGING_HEAVY_METAL_TESTED', domain='TEXTILE', section='PACKAGING', label_ko='포장재 중금속 시험 여부', label_en='Packaging Heavy Metal Tested', data_type='BOOLEAN', unit=None),
    dict(code='PACKAGING_LEAD_PB_CONCENTRATION_PPM', domain='TEXTILE', section='PACKAGING', label_ko='포장재 납(Pb) 농도', label_en='Packaging Lead Pb Concentration ppm', data_type='NUMBER', unit='ppm'),
    dict(code='PACKAGING_CADMIUM_CD_CONCENTRATION_PPM', domain='TEXTILE', section='PACKAGING', label_ko='포장재 카드뮴(Cd) 농도', label_en='Packaging Cadmium Cd Concentration ppm', data_type='NUMBER', unit='ppm'),
    dict(code='DECLARATION_OF_CONFORMITY_URL', domain='TEXTILE', section='DOCUMENT', label_ko='적합성선언서 URL', label_en='Declaration of Conformity URL', data_type='URL', unit=None),
]
